{
 "title": "EVCC: Mes",
 "tags": [ "PV" ],
 "time": { "from": "now/M", "to": "now/M" },
 "templating": {
  "list": [
   { "name": "timezone", "label": "Zona horaria", "query": "${VAR_TIMEZONE}" },
   {
    "name": "peakPowerLimit",
    "label": "Filtro para potencia máxima / W",
    "query": "${VAR_PEAKPOWERLIMIT}"
   },
   { "name": "installedWattPeak", "label": "Capacidad instalada en Wp", "query": "${VAR_INSTALLEDWATTPEAK}" },
   {
    "name": "loadpointBlocklist",
    "label": "Lista de bloqueo para puntos de carga",
    "query": "${VAR_LOADPOINTBLOCKLIST}"
   }
  ]
 },
 "panels": [
  { "title": "fotovoltaica", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 } },
  {
   "title": "Energía",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM pvDailyEnergy WHERE $timeFilter  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Netzbezug",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM gridDailyEnergy WHERE $timeFilter  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Haus",
     "query": "SELECT value * (-1) FROM homeDailyEnergy WHERE $timeFilter  tz('$timezone')"
    },
    {
     "alias": "$tag_loadpoint",
     "query": "SELECT value * (-1) FROM loadpointDailyEnergy WHERE $timeFilter AND \"loadpoint\"::tag !~ $loadpointBlocklist GROUP BY (\"loadpoint\"::tag) tz('$timezone')"
    },
    {
     "alias": "Einspeisung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value * (-1) FROM feedInDailyEnergy WHERE $timeFilter  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rendimiento específico",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kWh/kWp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$pvEnergy/$installedWattPeak", "type": "math" }
   ]
  },
  { "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 } },
  {
   "title": "Métrica",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "1-$zugekaufteEnergie/($energieLoadpoints + $energieHaus)",
     "type": "math"
    },
    {
     "expression": "($energiePV - $eingespeisteEnergie)/$energiePV",
     "type": "math"
    }
   ]
  },
  { "title": "Hogar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Inicio: Distribución de energía",
   "type": "piechart",
   "description": "La fórmula para 'Otros' debe ajustarse según la disponibilidad de medidores AUX y EXT. Consulte https://github.com/ha-puzzles/evcc-grafana-dashboards/tree/main/dashboards#formel-für-sonstige-anpassen para obtener más detalles.",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expression": "$homeTotal - $extEnergiesSum", "type": "math" },
    {
     "alias": "$tag_title",
     "query": "SELECT value FROM extDailyEnergy WHERE $timeFilter AND \"title\"::tag !~ $loadpointBlocklist GROUP BY (\"title\"::tag) tz('$timezone')"
    },
    {
     "alias": "$tag_title",
     "query": "SELECT value FROM auxDailyEnergy WHERE $timeFilter AND \"title\"::tag !~ $loadpointBlocklist GROUP BY (\"title\"::tag) tz('$timezone')"
    }
   ]
  },
  {
   "title": "Hogar: Consumo de energía",
   "type": "barchart",
   "description": "La fórmula para 'Otros' debe ajustarse según la disponibilidad de medidores AUX y EXT. Consulte https://github.com/ha-puzzles/evcc-grafana-dashboards/tree/main/dashboards#formel-für-sonstige-anpassen para obtener más detalles.",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expression": "$homeTotal - $extEnergiesSum", "type": "math" },
    {
     "alias": "$tag_title",
     "query": "SELECT value FROM extDailyEnergy WHERE $timeFilter AND \"title\"::tag !~ $loadpointBlocklist GROUP BY (\"title\"::tag) tz('$timezone')"
    },
    {
     "alias": "$tag_title",
     "query": "SELECT value FROM auxDailyEnergy WHERE $timeFilter AND \"title\"::tag !~ $loadpointBlocklist GROUP BY (\"title\"::tag) tz('$timezone')"
    }
   ]
  },
  {
   "title": "Total: Distribución de energía",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Haus",
     "query": "SELECT value FROM homeDailyEnergy WHERE $timeFilter  tz('$timezone')"
    },
    {
     "alias": "$tag_loadpoint",
     "query": "SELECT value FROM loadpointDailyEnergy WHERE $timeFilter AND \"loadpoint\"::tag !~ $loadpointBlocklist GROUP BY (\"loadpoint\"::tag) tz('$timezone')"
    },
    {
     "expression": "$chargeEnergy - $dischargeEnergy",
     "type": "math"
    }
   ]
  },
  {
   "title": "Total: Distribución de energía",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expression": "$chargeEnergy-$dischargeEnergy", "type": "math" },
    {
     "alias": "Haus",
     "query": "SELECT value FROM homeDailyEnergy WHERE $timeFilter  tz('$timezone')"
    },
    {
     "alias": "$tag_loadpoint",
     "query": "SELECT value FROM loadpointDailyEnergy WHERE $timeFilter AND \"loadpoint\"::tag !~ $loadpointBlocklist GROUP BY (\"loadpoint\"::tag) tz('$timezone')"
    }
   ]
  },
  { "gridPos": { "h": 18, "w": 5, "x": 0, "y": 43 } },
  { "gridPos": { "h": 11, "w": 19, "x": 5, "y": 43 } },
  {
   "title": "Costos de electricidad",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "alias": "Einkauf",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvPower",
     "query": "SELECT value FROM energyPurchasedDailyPrice WHERE $timeFilter  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Verkauf",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvPower",
     "query": "SELECT value FROM energySoldDailyPrice WHERE $timeFilter  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Batería", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  { "gridPos": { "h": 7, "w": 5, "x": 0, "y": 62 } },
  {
   "title": "Niveles de batería del hogar",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 62 },
   "targets": [
    {
     "alias": "Speicher max",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT \"value\" FROM \"batteryMaxSoc\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Speicher min",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT \"value\" FROM \"batteryMinSoc\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}