{
 "title": "EVCC: Todos los tiempos",
 "tags": [ "PV" ],
 "time": { "from": "2023-02-28T23:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "purchasePricePv",
    "label": "Costos totales de inversión fotovoltaica",
    "query": "24884"
   },
   { "name": "batteryPurchasePrice", "label": "Costo de inversión en batería", "query": "5500" },
   { "name": "runningCosts", "label": "Costos continuos", "query": "100" },
   { "name": "vVerbrauch", "label": "Consumo de HIELO l/100km", "query": "6" },
   { "name": "spritKosten", "label": "Precio del combustible/litro", "query": "1.75" },
   { "name": "timezone", "query": "Europe/Berlin" },
   {
    "name": "speicherkapazitaet",
    "label": "Capacidad de la batería doméstica / Wh",
    "query": "${VAR_SPEICHERKAPAZITAET}"
   },
   {
    "name": "vehicle",
    "label": "Vehículo",
    "query": {
     "query": "show tag values from vehicleMonthlyEnergy with key = \"vehicle\" where \"vehicle\" !~ $vehicleBlocklist"
    }
   },
   {
    "name": "vehicleBlocklist",
    "label": "Lista de bloqueo para vehículos",
    "query": "${VAR_VEHICLEBLOCKLIST}"
   },
   {
    "name": "loadpointBlocklist",
    "label": "Lista de bloqueo para puntos de carga",
    "query": "${VAR_LOADPOINTBLOCKLIST}"
   }
  ]
 },
 "panels": [
  { "title": "Energía", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "gridPos": { "h": 11, "w": 3, "x": 0, "y": 1 } },
  {
   "title": "Rendimiento anual",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "year::tag" ], "type": "tag" }
     ],
     "measurement": "pvMonthlyEnergy",
     "query": "SELECT value, year FROM \"pvMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rendimiento mensual/año",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_month]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT year, month, value FROM \"pvMonthlyEnergy\" tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "gridPos": { "h": 12, "w": 3, "x": 0, "y": 12 } },
  {
   "title": "Consumo doméstico anual",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "year::tag" ], "type": "tag" }
     ],
     "measurement": "pvMonthlyEnergy",
     "query": "SELECT value, year FROM \"homeMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumo doméstico mensual/año",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT year, month, value FROM \"homeMonthlyEnergy\"  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Importación anual de cuadrícula",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "year::tag" ], "type": "tag" }
     ],
     "measurement": "pvMonthlyEnergy",
     "query": "SELECT value, year FROM \"gridMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Importación mensual de grid/año",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT year, month, value FROM \"gridMonthlyEnergy\"  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 } },
  {
   "title": "Alimentación anual",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "year::tag" ], "type": "tag" }
     ],
     "measurement": "pvMonthlyEnergy",
     "query": "SELECT value, year FROM \"feedInMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alimentación mensual/año",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT year, month, value FROM \"feedInMonthlyEnergy\"  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Días con mayor rendimiento",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "PV Energie",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvPower",
     "query": "SELECT value FROM \"pvDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value::field", "operator": "<", "value": "10000" }
     ]
    }
   ]
  },
  {
   "title": "Alimentación más alta",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Einspeisung",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gridPower",
     "query": "SELECT value FROM \"feedInDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / -3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value::field", "operator": "<", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Mayor consumo doméstico",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Hausverbrauch",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "homePower",
     "query": "SELECT value FROM \"homeDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value::field", "operator": "<", "value": "10000" }
     ]
    }
   ]
  },
  { "title": "Finanzas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Costos mensuales",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "SELECT value FROM energyPurchasedMonthlyPrice WHERE $timeFilter  tz('$timezone')"
    },
    {
     "query": "SELECT value FROM energySoldMonthlyPrice WHERE $timeFilter  tz('$timezone')"
    },
    {
     "expression": "(abs($purchased + $sold) + ($purchased + $sold)) /2",
     "type": "math"
    },
    {
     "expression": "-(abs($purchased + $sold)- ($purchased + $sold)) /2",
     "type": "math"
    }
   ]
  },
  { "gridPos": { "h": 9, "w": 8, "x": 0, "y": 55 } },
  {
   "title": "Amortización del sistema fotovoltaico",
   "type": "stat",
   "description": "Para datos de menos de 365 días, los valores se extrapolan a un año completo con la correspondiente inexactitud según el período capturado.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$potentialHomePrice + $potentialLoadpointPrice",
     "type": "math"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyPurchasedDailyPrice",
     "query": "SELECT sum(\"value\") FROM \"energyPurchasedDailyPrice\" WHERE $timeFilter TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyPurchasedDailyPrice",
     "query": "SELECT sum(\"value\") * (-1) FROM \"energySoldDailyPrice\" WHERE $timeFilter TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "$energyPurchasedPrice - $energySoldPrice",
     "type": "math"
    },
    {
     "expression": "$potentialTotalPrice - $energyTotalPrice",
     "type": "math"
    },
    { "expression": "dailyMeasurement", "reducer": "count", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "$refluxOfCapital*365/$numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$purchasePricePv / ($refluxOfCapitalYearly - $runningCosts)",
     "type": "math"
    },
    {
     "expression": "($refluxOfCapitalYearly - $runningCosts) / $purchasePricePv",
     "type": "math"
    }
   ]
  },
  {
   "title": "Amortización de la batería",
   "type": "stat",
   "description": "Para datos de menos de 365 días, los valores se extrapolan a un año completo con la correspondiente inexactitud según el período capturado.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") from chargeDailyEnergy WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") from dischargeDailyEnergy WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "1-($dischargedEnergy/$chargedEnergy)",
     "type": "math"
    },
    {
     "expression": "($chargedEnergy/$speicherkapazitaet) * 365/$numberOfMeasuredDays",
     "type": "math"
    },
    { "expression": "dailyMeasurement", "reducer": "count", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "($batteryDischargeCost - $batteryChargeFeedInCost) * 365/$numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$batteryPurchasePrice/$batteryPayback",
     "type": "math"
    },
    {
     "expression": "$batteryPayback/$batteryPurchasePrice",
     "type": "math"
    }
   ]
  },
  {
   "title": "Costos de viaje $vehículo",
   "type": "stat",
   "description": "Los valores son estimaciones aproximadas basadas en promedios.\n\nSupuesto: el vehículo se carga principalmente en casa. La carga externa no está incluida.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "repeat": "vehicle",
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "drivenKm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT spread(\"value\") FROM \"vehicleOdometerDailyMax\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expression": "$chargedEnergy/($drivenKm/100)", "type": "math" },
    {
     "alias": "Solaranteil",
     "measurement": "sessionSolarPercentage",
     "query": "SELECT mean(\"value\") FROM \"sessionSolarPercentage\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Effektiver, durchschnittlicher Preis",
     "measurement": "sessionPricePerKWh",
     "query": "SELECT mean(\"value\") FROM \"sessionPricePerKWh\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"potentialVehicleChargeDailyPrice\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"vehicleChargeDailyPrice\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "$electricDriveCostNoPV - $electricDriveCost",
     "type": "math"
    },
    {
     "expression": "$drivenKm / 100 * $vVerbrauch * $spritKosten",
     "type": "math"
    },
    {
     "expression": "$iceDriveCost - $electricDriveCost",
     "type": "math"
    }
   ]
  },
  { "title": "Salud del sistema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Promedio de los 30 mejores días/año",
   "type": "barchart",
   "description": "Utiliza el rendimiento promedio de los mejores 30 días del año. Puede ayudar a detectar una posible degradación, pero debe interpretarse de manera integral. Los años individuales no son concluyentes.",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(value, 30) FROM (\n        SELECT * FROM \"pvDailyEnergy\"  TZ('$timezone')\n) GROUP BY year TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promedio de los 5 mejores días/mes",
   "type": "barchart",
   "description": "Utiliza el rendimiento promedio de los mejores 5 días del mes. Puede ayudar a detectar una posible degradación, pero debe interpretarse de manera integral. Los meses individuales no son concluyentes.",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(top) FROM (\n    SELECT top(value, 5) FROM (\n        SELECT year, month, value FROM \"pvDailyEnergy\"  TZ('$timezone')\n    ) GROUP BY month, year TZ('$timezone')\n) GROUP BY month, year TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}