{
 "title": "VM: EVCC: Hoy - Detalles",
 "tags": [ "EVCC" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "peakPowerLimit",
    "label": "Filtro para potencia máxima / W",
    "query": "25000"
   },
   {
    "name": "loadpointBlocklist",
    "label": "Lista de bloqueo para puntos de carga",
    "query": "^none$"
   },
   { "name": "extBlocklist", "query": ".*Car.*|.*Haupt.*" },
   { "name": "auxBlocklist", "query": "^none$" },
   {
    "name": "loadpoint",
    "label": "punto de carga",
    "query": "label_values(chargePower_value{db=\"evcc\"}, loadpoint)"
   },
   {
    "name": "energySampleInterval",
    "label": "Intervalo de muestra de energía",
    "query": "30s"
   },
   { "name": "tariffPriceInterval", "label": "Intervalo tarifario", "query": "15m" }
  ]
 },
 "panels": [
  { "title": "fotovoltaica", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "energía fotovoltaica",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "sort_by_label(range_sum(integrate(avg by (title)(pvPower_value{id!=\"\"}) < $peakPowerLimit)) / 3600000, \"title\")",
     "legendFormat": "{{title}}"
    },
    { "expr": "min(chargePower_value)", "legendFormat": "Energía" },
    {
     "expr": "range_sum(integrate(avg(pvPower_value{id=\"\"}) < $peakPowerLimit)) / 3600000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Potencia FV",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sort_by_label(avg by (title)(pvPower_value{title!=\"\"}), \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Nivel de batería",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(avg by (title) (batterySoc_value{id!=\"\", title!=\"\"}), \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "batterySoc_value{id=\"\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Potencia de la batería",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg by (title)(batteryPower_value{id!=\"\"})",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Pronóstico",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "range_sum(integrate(avg(tariffSolar_value))) / 3600000",
     "legendFormat": "Pronóstico"
    },
    {
     "expr": "range_sum(integrate(avg(pvPower_value{id=\"\"}) < $peakPowerLimit)) / 3600000",
     "legendFormat": "Real"
    },
    { "expr": "min(chargePower_value)", "legendFormat": "Energía" }
   ]
  },
  {
   "title": "Pronóstico",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "avg(tariffSolar_value)", "legendFormat": "Pronóstico" },
    {
     "expr": "avg(pvPower_value{id=\"\"})",
     "legendFormat": "Real"
    }
   ]
  },
  { "title": "Consumo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Hogar: Potencia actual",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(homePower_value) - avg(sum(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))",
     "legendFormat": "Otros"
    },
    {
     "expr": "avg(homePower_value) - avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))",
     "legendFormat": "Otros"
    },
    {
     "expr": "avg(homePower_value) - avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))  - avg(sum(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))",
     "legendFormat": "Otros"
    },
    {
     "expr": "sort_by_label(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Hogar: Potencia",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(homePower_value) - avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))",
     "legendFormat": "Otros"
    },
    {
     "expr": "avg(homePower_value) - avg(sum(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))",
     "legendFormat": "Otros"
    },
    {
     "expr": "avg(homePower_value) - avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"})) - avg(sum(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))",
     "legendFormat": "Otros"
    },
    {
     "expr": "sort_by_label(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Hogar: Distribución de energía",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_sum(integrate(avg(homePower_value)))/3600 - range_sum(integrate(avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))))/3600 - range_sum(integrate(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"})))/3600",
     "legendFormat": "Otros"
    },
    {
     "expr": "range_sum(integrate(avg(homePower_value)))/3600 - range_sum(integrate(avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))))/3600 ",
     "legendFormat": "Otros"
    },
    {
     "expr": "range_sum(integrate(avg(homePower_value)))/3600 - range_sum(integrate(avg(sum(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))))/3600 ",
     "legendFormat": "Otros"
    },
    {
     "expr": "sort_by_label(range_sum(integrate(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"})))/3600, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(range_sum(integrate(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"})))/3600, \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Casa: Energía",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(integrate(homePower_value offset -1h))/3600 - sum(integrate(extPower_value{title!=\"\", title !~ \"$extBlocklist\"} offset -1h))/3600 - sum(integrate(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"} offset -1h))/3600",
     "legendFormat": "Otros"
    },
    {
     "expr": "sum(integrate(homePower_value offset -1h))/3600 - sum(integrate(extPower_value{title!=\"\", title !~ \"$extBlocklist\"} offset -1h))/3600",
     "legendFormat": "Otros"
    },
    {
     "expr": "sum(integrate(homePower_value offset -1h))/3600 - sum(integrate(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"} offset -1h))/3600",
     "legendFormat": "Otros"
    },
    {
     "expr": "sort_by_label(integrate(extPower_value{title!=\"\", title !~ \"$extBlocklist\"} offset -1h)/3600, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(integrate(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}offset -1h)/3600, \"title\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total: Distribución de energía",
   "type": "piechart",
   "description": "La fórmula para 'Otros' debe ajustarse según la disponibilidad de medidores AUX y EXT. Consulte https://github.com/ha-puzzles/evcc-grafana-dashboards/tree/main/dashboards#formel-für-sonstige-anpassen para obtener más detalles.",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_sum(integrate(avg(homePower_value)))/3600",
     "legendFormat": "Hogar"
    },
    {
     "expr": "sort_by_label(sum by (loadpoint)(range_sum (integrate(chargePower_value{loadpoint!=\"\", loadpoint !~ \"$loadpointBlocklist\"})) / 3600), \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    }
   ]
  },
  {
   "title": "Total: Energía",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(integrate(homePower_value offset -1h))/3600",
     "legendFormat": "Hogar"
    },
    {
     "expr": "sort_by_label(avg by(loadpoint)(integrate(chargePower_value{loadpoint!=\"\"} offset -1h))/3600, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    }
   ]
  },
  { "title": "Tarifas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Precio de la electricidad",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(avg(tariffGrid_value)[1d])",
     "legendFormat": "Max"
    },
    {
     "expr": "avg_over_time(avg(tariffGrid_value)[1d])",
     "legendFormat": "Promedio"
    },
    {
     "expr": "min_over_time(avg(tariffGrid_value)[1d])",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Precio de la electricidad",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 56 },
   "targets": [
    {
     "expr": "avg(tariffGrid_value offset -$tariffPriceInterval)",
     "legendFormat": "Precio"
    },
    {
     "expr": "clamp_min(avg(gridPower_value offset -$tariffPriceInterval), 0)",
     "legendFormat": "Consumo de red"
    }
   ]
  },
  {
   "title": "Costos",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_sum(avg(tariffGrid_value) * integrate(clamp_min(avg(gridPower_value), 0)) /3600000)",
     "legendFormat": "Compra"
    },
    {
     "expr": "range_sum(avg(tariffFeedIn_value) * integrate(clamp_max(avg(gridPower_value), 0)) /3600000)",
     "legendFormat": "Venta"
    },
    { "expression": "$bought + $sold", "type": "math" }
   ]
  },
  {
   "title": "Costos",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "avg(tariffGrid_value offset -$tariffPriceInterval) * integrate(clamp_min(avg(gridPower_value offset -$tariffPriceInterval), 0)) /3600000",
     "legendFormat": "Compra"
    },
    {
     "expr": "avg(tariffFeedIn_value offset -$tariffPriceInterval) * integrate(clamp_max(avg(gridPower_value offset -$tariffPriceInterval), 0)) /3600000",
     "legendFormat": "Venta"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "g/kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(avg(tariffCo2_value)[1d])",
     "legendFormat": "Max"
    },
    {
     "expr": "avg_over_time(avg(tariffCo2_value)[1d])",
     "legendFormat": "Promedio"
    },
    {
     "expr": "min_over_time(avg(tariffCo2_value)[1d])",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 74 },
   "targets": [
    {
     "expr": "tariffCo2_value offset -$tariffPriceInterval",
     "legendFormat": "CO2"
    },
    { "expr": "clamp_min(gridPower_value, 0)", "legendFormat": "Consumo de red" }
   ]
  },
  { "title": "Red", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Corrientes/fase",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(avg(gridCurrents_l1))",
     "legendFormat": "Corriente L1"
    },
    {
     "expr": "last_over_time(avg(gridCurrents_l2))",
     "legendFormat": "Corriente L2"
    },
    {
     "expr": "last_over_time(avg(gridCurrents_l3))",
     "legendFormat": "Corriente L3"
    }
   ]
  },
  {
   "title": "Corrientes/fase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "avg(gridCurrents_l1)", "legendFormat": "Corriente L1" },
    { "expr": "avg(gridCurrents_l2)", "legendFormat": "Corriente L2" },
    { "expr": "avg(gridCurrents_l3)", "legendFormat": "Corriente L3" }
   ]
  },
  {
   "title": "Potencia/fase",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(avg(gridPowers_l1))",
     "legendFormat": "Potencia L1"
    },
    {
     "expr": "last_over_time(avg(gridPowers_l2))",
     "legendFormat": "Potencia L2"
    },
    {
     "expr": "last_over_time(avg(gridPowers_l3))",
     "legendFormat": "Potencia L3"
    }
   ]
  },
  {
   "title": "Potencia/fase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "avg(gridPowers_l1)", "legendFormat": "Potencia L1" },
    { "expr": "avg(gridPowers_l2)", "legendFormat": "Potencia L2" },
    { "expr": "avg(gridPowers_l3)", "legendFormat": "Potencia L3" }
   ]
  },
  { "title": "Punto de carga $punto de carga", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }, "repeat": "loadpoint" },
  {
   "title": "Corrientes de carga/fase: $loadpoint",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(avg(chargeCurrents_l1{loadpoint=\"$loadpoint\"}))",
     "legendFormat": "Corriente L1"
    },
    {
     "expr": "last_over_time(avg(chargeCurrents_l2{loadpoint=\"$loadpoint\"}))",
     "legendFormat": "Corriente L2"
    },
    {
     "expr": "last_over_time(avg(chargeCurrents_l2{loadpoint=\"$loadpoint\"}))",
     "legendFormat": "Corriente L3"
    }
   ]
  },
  {
   "title": "Corrientes de carga/fase: $loadpoint",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "avg(chargeCurrents_l1 {loadpoint=\"$loadpoint\"})",
     "legendFormat": "Corriente L1"
    },
    {
     "expr": "avg(chargeCurrents_l2 {loadpoint=\"$loadpoint\"})",
     "legendFormat": "Corriente L2"
    },
    {
     "expr": "avg(chargeCurrents_l3 {loadpoint=\"$loadpoint\"})",
     "legendFormat": "Corriente L3"
    }
   ]
  },
  {
   "title": "Fases: $loadpoint",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 112 },
   "targets": [
    {
     "expr": "avg(phasesActive_value{loadpoint=\"$loadpoint\"}) < 2",
     "legendFormat": "1 fase"
    },
    {
     "expr": "avg(phasesActive_value{loadpoint=\"$loadpoint\"}) > 2",
     "legendFormat": "3 fases"
    }
   ]
  },
  {
   "title": "Potencia de carga: $loadpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(chargePower_value {loadpoint=\"$loadpoint\"})",
     "legendFormat": "Potencia de carga"
    }
   ]
  }
 ]
}