{
 "title": "VM: EVCC: Todo el tiempo",
 "tags": [ "EVCC" ],
 "time": { "from": "now-2y/y", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "dbLabel", "label": "Etiqueta DB", "query": "evcc" },
   { "name": "peakPowerLimit", "label": "Límite de potencia máxima", "query": "30000" },
   {
    "name": "energySampleInterval",
    "label": "Intervalo de muestreo de energía",
    "query": "30s"
   },
   { "name": "tariffPriceInterval", "label": "Intervalo de tarifa", "query": "15m" },
   {
    "name": "loadpointBlocklist",
    "label": "Lista de bloqueo punto de carga",
    "query": "^none$"
   },
   { "name": "extBlocklist", "label": "Lista de bloqueo EXT", "query": "^none$" },
   { "name": "auxBlocklist", "label": "Lista de bloqueo AUX", "query": "^none$" },
   { "name": "installedWattPeak", "label": "installedWattPeak", "query": "20" },
   { "name": "vehicleBlocklist", "label": "Lista de bloqueo vehículo", "query": "^Altherma-3$" },
   {
    "name": "vehicle",
    "label": "Vehículo",
    "query": {
     "query": "label_values(sessionPricePerKWh_value{db=\"$dbLabel\",vehicle!=\"\",vehicle!~\"$vehicleBlocklist\"}, vehicle)"
    }
   },
   { "name": "vVerbrauch", "label": "Consumo térmico l/100km", "query": "6" },
   { "name": "spritKosten", "label": "Precio combustible/l", "query": "1.75" },
   { "name": "purchasePricePv", "label": "Precio de compra FV", "query": "24884" },
   { "name": "batteryPurchasePrice", "label": "Precio de compra batería", "query": "5500" },
   { "name": "runningCosts", "label": "Costes corrientes", "query": "100" },
   { "name": "speicherkapazitaet", "label": "Capacidad de batería / Wh", "query": "9500" },
   { "name": "evccUrl", "label": "URL de EVCC", "query": "${VAR_EVCCURL}" },
   { "name": "inverterPortalTitle", "label": "Nombre del portal del inversor", "query": "${VAR_INVERTERPORTALTITLE}" },
   { "name": "inverterPortalUrl", "label": "URL del portal del inversor", "query": "${VAR_INVERTERPORTALURL}" }
  ]
 },
 "panels": [
  { "title": "Energía", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Totales de energía",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Importación de red"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "fotovoltaica"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Casa"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{db=\"$dbLabel\",loadpoint!~\"$loadpointBlocklist\"}[1d]))[$__range:1d])) by (loadpoint) / 1000, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Vertido"
    }
   ]
  },
  {
   "title": "Rendimiento anual",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Rendimiento mensual/año",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "Indicadores",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1 - $gridEnergyIn / ($homeEnergy + $loadpointEnergy)",
     "type": "math"
    },
    {
     "expression": "($pvEnergy - $gridEnergyOut) / $pvEnergy",
     "type": "math"
    }
   ]
  },
  {
   "title": "Consumo anual de la casa",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Consumo de la casa mensual/año",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "Importación de red anual",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Importación de red mensual/año",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "Batería",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "batteryChargeTotal"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "batteryDischargeTotal"
    },
    {
     "expression": "$batteryDischargeTotal / $batteryChargeTotal",
     "type": "math"
    },
    {
     "expr": "sum(avg_over_time((last_over_time(evcc_battery_soc_daily_max_pct{db=\"$dbLabel\"}[1d]))[$__range:1d])) / count(avg_over_time((last_over_time(evcc_battery_soc_daily_max_pct{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "maxSoc"
    },
    {
     "expr": "sum(avg_over_time((last_over_time(evcc_battery_soc_daily_min_pct{db=\"$dbLabel\"}[1d]))[$__range:1d])) / count(avg_over_time((last_over_time(evcc_battery_soc_daily_min_pct{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "minSoc"
    }
   ]
  },
  {
   "title": "Vertido anual",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Vertido mensual/año",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "Días con mayor rendimiento",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "max without(local_year,local_month)(evcc_pv_energy_daily_wh{db=\"$dbLabel\"}) / 1000",
     "legendFormat": "Energía FV"
    }
   ]
  },
  {
   "title": "Mayores vertidos",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "max without(local_year,local_month)(evcc_grid_export_daily_wh{db=\"$dbLabel\"}) / 1000",
     "legendFormat": "Vertido"
    }
   ]
  },
  {
   "title": "Mayores consumos de la casa",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "max without(local_year,local_month)(evcc_home_energy_daily_wh{db=\"$dbLabel\"}) / 1000",
     "legendFormat": "Consumo de la casa"
    }
   ]
  },
  { "title": "Salud de la instalación", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Promedio de los 30 mejores días/año",
   "type": "barchart",
   "description": "Usa el rendimiento medio de los 30 mejores días por año. Esto puede ayudar a identificar una posible degradación, pero debe interpretarse en contexto. Los años individuales por sí solos no son concluyentes.",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "last_over_time(evcc_pv_top30_mean_yearly_wh{db=\"$dbLabel\"}[$__range])",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Promedio de los 5 mejores días/mes",
   "type": "barchart",
   "description": "Usa el rendimiento medio de los 5 mejores días por mes. Esto puede ayudar a identificar una posible degradación, pero debe interpretarse en contexto. Los meses individuales por sí solos no son concluyentes.",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "last_over_time(evcc_pv_top5_mean_monthly_wh{db=\"$dbLabel\"}[$__range])",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  { "title": "Finanzas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Costes mensuales",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "label_join(label_set(clamp_min((sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month) - sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)), 0), \"kind\", \"Costs\"), \"series\", \" \", \"local_year\", \"kind\") or (label_join(label_set(clamp_min((sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month) - sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)), 0), \"kind\", \"Income\"), \"series\", \" \", \"local_year\", \"kind\") and on (local_year) (sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year) > 0))"
    }
   ]
  },
  { "title": "Balance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Balance eléctrico",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / sum(count_over_time((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "averagePrice"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) * -1",
     "legendFormat": "Comprado"
    },
    {
     "expression": "($purchased * -100) / ($energyPurchased / 1000)",
     "type": "math"
    },
    {
     "expression": "$averagePrice - $weightedAveragePrice",
     "type": "math"
    },
    {
     "expression": "$averagePrice * ($energyPurchased / 1000) / -100",
     "type": "math"
    },
    {
     "expression": "$purchased - $potentialPurchased",
     "type": "math"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "Vendido"
    },
    { "expression": "$purchased + $sold", "type": "math" }
   ]
  },
  {
   "title": "Amortización instalación FV",
   "type": "stat",
   "description": "Con menos de 365 días de datos, los valores se extrapolan a un año completo con la inexactitud correspondiente según el período capturado.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$potentialHomePrice + $potentialLoadpointPrice",
     "type": "math"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "energyPurchasedPrice"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "energySoldPrice"
    },
    {
     "expression": "$energyPurchasedPrice - $energySoldPrice",
     "type": "math"
    },
    {
     "expression": "$potentialTotalPrice - $energyTotalPrice",
     "type": "math"
    },
    {
     "expr": "sum(count_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "numberOfMeasuredDays"
    },
    {
     "expression": "$refluxOfCapital * 365 / $numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$purchasePricePv / ($refluxOfCapitalYearly - $runningCosts)",
     "type": "math"
    },
    {
     "expression": "($refluxOfCapitalYearly - $runningCosts) / $purchasePricePv",
     "type": "math"
    }
   ]
  },
  {
   "title": "Amortización batería",
   "type": "stat",
   "description": "Con menos de 365 días de datos, los valores se extrapolan a un año completo con la inexactitud correspondiente según el período capturado.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "chargedEnergy"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "dischargedEnergy"
    },
    {
     "expression": "1 - ($dischargedEnergy / $chargedEnergy)",
     "type": "math"
    },
    {
     "expr": "sum(count_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "numberOfMeasuredDays"
    },
    {
     "expression": "($chargedEnergy / $speicherkapazitaet) * 365 / $numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "($batteryDischargeCost - $batteryChargeFeedInCost) * 365 / $numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$batteryPurchasePrice / $batteryPayback",
     "type": "math"
    },
    {
     "expression": "$batteryPayback / $batteryPurchasePrice",
     "type": "math"
    }
   ]
  },
  { "title": "Vehículos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Costes de conducción $vehicle",
   "type": "stat",
   "description": "Los valores son estimaciones aproximadas basadas en promedios. Las sesiones de carga externas no están incluidas.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 93 },
   "repeat": "vehicle",
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_vehicle_distance_daily_km{db=\"$dbLabel\",vehicle=\"$vehicle\"}[1d]))[$__range:1d]))",
     "legendFormat": "drivenKm"
    },
    {
     "expression": "$chargedEnergy / ($drivenKm / 100)",
     "type": "math"
    },
    {
     "expr": "avg(avg_over_time(sessionSolarPercentage_value{db=\"$dbLabel\",vehicle=\"$vehicle\"}[$__range]))",
     "legendFormat": "solarPercent"
    },
    {
     "expr": "avg(avg_over_time(sessionPricePerKWh_value{db=\"$dbLabel\",vehicle=\"$vehicle\"}[$__range]))",
     "legendFormat": "chargePrice"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_potential_vehicle_charge_cost_daily_eur{db=\"$dbLabel\",vehicle=\"$vehicle\"}[1d]))[$__range:1d]))",
     "legendFormat": "electricDriveCostNoPV"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_vehicle_charge_cost_daily_eur{db=\"$dbLabel\",vehicle=\"$vehicle\"}[1d]))[$__range:1d]))",
     "legendFormat": "electricDriveCost"
    },
    {
     "expression": "$electricDriveCostNoPV - $electricDriveCost",
     "type": "math"
    },
    {
     "expression": "$drivenKm / 100 * $vVerbrauch * $spritKosten",
     "type": "math"
    },
    {
     "expression": "$iceDriveCost - $electricDriveCost",
     "type": "math"
    }
   ]
  }
 ]
}