{
 "title": "VM: EVCC: Hoy indicadores",
 "tags": [ "EVCC" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "dashboardBuild", "label": "Build", "query": "info" },
   { "name": "peakPowerLimit", "label": "Filtro de potencia máxima / W", "query": "${VAR_PEAKPOWERLIMIT}" },
   { "name": "evccUrl", "label": "URL de EVCC", "query": "${VAR_EVCCURL}" },
   { "name": "inverterPortalTitle", "label": "Nombre del portal del inversor", "query": "${VAR_INVERTERPORTALTITLE}" },
   { "name": "inverterPortalUrl", "label": "URL del portal del inversor", "query": "${VAR_INVERTERPORTALURL}" },
   {
    "name": "loadpointBlocklist",
    "label": "Lista de bloqueo de puntos de carga",
    "query": "${VAR_LOADPOINTBLOCKLIST}"
   },
   { "name": "vehicleBlocklist", "label": "Lista de bloqueo de vehículos", "query": "${VAR_VEHICLEBLOCKLIST}" },
   {
    "name": "energySampleInterval",
    "label": "Intervalo de muestreo de energía",
    "query": "${VAR_ENERGYSAMPLEINTERVAL}"
   },
   { "name": "tariffPriceInterval", "label": "Intervalo de tarifa", "query": "${VAR_TARIFFPRICEINTERVAL}" }
  ]
 },
 "panels": [
  {
   "title": "Potencia",
   "type": "gauge",
   "gridPos": { "h": 24, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kW" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(pvPower_value{id=\"\"} / 1000)",
     "legendFormat": "fotovoltaica"
    },
    { "expr": "avg(gridPower_value / 1000)", "legendFormat": "Red" },
    { "expr": "avg(homePower_value / -1000)", "legendFormat": "Casa" },
    {
     "expr": "avg(batteryPower_value{id=\"\"} / 1000)",
     "legendFormat": "Batería"
    },
    {
     "expr": "sort_by_label(avg by(loadpoint) (chargePower_value / -1000),\"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    }
   ]
  },
  {
   "title": "Power history",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 16, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "max_over_time(pvPower_value{id=\"\"}[$__interval]) < $peakPowerLimit",
     "legendFormat": "fotovoltaica"
    },
    {
     "expr": "avg_over_time(gridPower_value[$__interval]) < $peakPowerLimit",
     "legendFormat": "Red"
    },
    {
     "expr": "max_over_time(homePower_value[$__interval]) * (-1) > (-$peakPowerLimit)",
     "legendFormat": "Casa"
    },
    {
     "expr": "avg_over_time(batteryPower_value{id=\"\"}[$__interval]) < $peakPowerLimit",
     "legendFormat": "Batería"
    },
    {
     "expr": "max by (loadpoint) (max_over_time(chargePower_value{id=\"\", loadpoint!~\"$loadpointBlocklist\"}[$__interval])) * (-1) > (-$peakPowerLimit)",
     "legendFormat": "{{loadpoint}}"
    },
    { "expr": "avg(tariffSolar_value)", "legendFormat": "Pronóstico FV" }
   ]
  },
  {
   "title": "Niveles de batería",
   "type": "timeseries",
   "description": "Negro: umbral de prioridad para la carga del vehículo",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(batterySoc_value{id=\"\"}) < 100",
     "legendFormat": "Batería"
    },
    {
     "expr": "sort_by_label(avg by(vehicle) (vehicleSoc_value{vehicle!=\"\", vehicle!~\"$vehicleBlocklist\"}), \"vehicle\")",
     "legendFormat": "{{vehicle}}"
    },
    {
     "expr": "last_over_time(prioritySoc_value[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Métricas",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1 - $gridEnergyIn/($homeEnergy+$loadpointEnergy)",
     "type": "math"
    },
    {
     "expr": "clamp_max(clamp_min((sum(integrate(((pvPower_value{id=\"\"} < $peakPowerLimit) default 0)[$__range:$energySampleInterval]) / 3600) - sum(integrate((((gridPower_value < 0 <$peakPowerLimit) default 0)[$__range:$energySampleInterval]) / -3600))) / clamp_min(sum(integrate(((pvPower_value{id=\"\"} < $peakPowerLimit) default 0)[$__range:$energySampleInterval]) / 3600), 0.001), 0), 1)",
     "legendFormat": "Autoconsumo"
    },
    {
     "expr": "avg(batterySoc_value{id=\"\"})",
     "legendFormat": "SOC batería"
    }
   ]
  },
  {
   "title": "Metric history",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "1 - $gridEnergyIn/($homeEnergy+$loadpointEnergy)",
     "type": "math"
    },
    {
     "expression": "($pvEnergy - $gridEnergyOut) / $pvEnergy",
     "type": "math"
    }
   ]
  },
  {
   "title": "Energía",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 14 },
   "targets": [
    {
     "expr": "sum without(host) (integrate(((pvPower_value{id=\"\"} < $peakPowerLimit) default 0)[$__range:$energySampleInterval]) / 3600000)",
     "legendFormat": "fotovoltaica"
    },
    {
     "expr": "sum without(host) (integrate(\n  ((gridPower_value > 0 <$peakPowerLimit) default 0) [$__range:$energySampleInterval]\n) / 3600000)",
     "legendFormat": "Importación de red"
    },
    {
     "expr": "sum without(host) (integrate(\n  ((gridPower_value < 0 <$peakPowerLimit) default 0) [$__range:$energySampleInterval]\n) / 3600000)",
     "legendFormat": "Vertido"
    },
    {
     "expr": "sum without(host) (integrate(((homePower_value{id=\"\"} < $peakPowerLimit) default 0)[$__range:$energySampleInterval]) / -3600000)",
     "legendFormat": "Casa"
    },
    {
     "expr": "sum without(host) (integrate(\n  ((batteryPower_value {id=\"\"} > 0 <$peakPowerLimit) default 0) [$__range:$energySampleInterval]\n) / 3600000)",
     "legendFormat": "Descarga de batería"
    },
    {
     "expr": "sum without(host) (integrate(\n  ((batteryPower_value {id=\"\"} < 0 <$peakPowerLimit) default 0) [$__range:$energySampleInterval]\n) / 3600000)",
     "legendFormat": "Carga de batería"
    },
    {
     "expr": "sort_by_label(\n  sum without(host) (\n    integrate(\n      ((chargePower_value{vehicle!=\"\", vehicle !~ \"$vehicleBlocklist\"}) default 0) [$__range:$energySampleInterval]\n    ) / -3600000\n  )\n, \"vehicle\")",
     "legendFormat": "{{vehicle}}"
    },
    {
     "expr": "sum without(host) ((integrate((chargePower_value{vehicle=\"\", loadpoint !~ \"$loadpointBlocklist\"} default 0)[$__range:$energySampleInterval]) / -3600000))",
     "legendFormat": "Invitado: {{loadpoint}}"
    },
    { "expr": "1", "legendFormat": "__panel_axis" }
   ]
  },
  {
   "title": "Power distribution",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 16, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "clamp_min(avg(gridPower_value) < $peakPowerLimit,0)",
     "legendFormat": "Importación de red"
    },
    {
     "expr": "clamp_max(avg(batteryPower_value{id=\"\"}) *(-1) > (-$peakPowerLimit),0) * (-1)",
     "legendFormat": "Descarga de batería"
    },
    {
     "expr": "avg(pvPower_value{id=\"\"}) < $peakPowerLimit",
     "legendFormat": "fotovoltaica"
    },
    {
     "expr": "clamp_max(avg(gridPower_value) < $peakPowerLimit,0)",
     "legendFormat": "Vertido"
    },
    {
     "expr": "clamp_min(avg(batteryPower_value{id=\"\"}) *(-1) > (-$peakPowerLimit),0) * (-1)",
     "legendFormat": "Carga de batería"
    },
    {
     "expr": "avg by (loadpoint) (chargePower_value{id=\"\"}) * (-1) > (-$peakPowerLimit)",
     "legendFormat": "{{loadpoint}}"
    },
    {
     "expr": "avg(homePower_value) * (-1) > (-$peakPowerLimit)",
     "legendFormat": "Casa"
    }
   ]
  },
  {
   "title": "Costes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_sum(avg(tariffGrid_value) * integrate(clamp_min(avg(gridPower_value), 0)) /3600000)",
     "legendFormat": "Comprado"
    },
    {
     "expr": "range_sum(avg(tariffFeedIn_value) * integrate(clamp_max(avg(gridPower_value), 0)) /3600000)",
     "legendFormat": "Vendido"
    },
    { "expression": "$boughtTotal + $soldTotal", "type": "math" }
   ]
  }
 ]
}