{
 "title": "VM: EVCC: Año",
 "tags": [ "EVCC" ],
 "time": { "from": "now/y", "to": "now/y" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "dashboardBuild", "label": "Build", "query": "info" },
   {
    "name": "loadpointBlocklist",
    "label": "Lista de bloqueo punto de carga",
    "query": "^none$"
   },
   { "name": "vehicleBlocklist", "label": "Lista de bloqueo de vehículos", "query": "^none$" },
   { "name": "extBlocklist", "label": "Lista de bloqueo EXT", "query": "^none$" },
   { "name": "auxBlocklist", "label": "Lista de bloqueo AUX", "query": "^none$" },
   {
    "name": "heatPumpLoadpointRegex",
    "label": "Coincidencia del punto de carga de la bomba de calor",
    "query": "(?i).*(daikin-wp|wp|warmepumpe|wärmepumpe|heat pump).*"
   },
   { "name": "installedWattPeak", "label": "installedWattPeak", "query": "20" },
   { "name": "evccUrl", "label": "URL de EVCC", "query": "${VAR_EVCCURL}" },
   { "name": "inverterPortalTitle", "label": "Nombre del portal del inversor", "query": "${VAR_INVERTERPORTALTITLE}" },
   { "name": "inverterPortalUrl", "label": "URL del portal del inversor", "query": "${VAR_INVERTERPORTALURL}" }
  ]
 },
 "panels": [
  { "title": "fotovoltaica", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Totales de energía",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Casa"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "fotovoltaica"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Importación de red"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Vertido"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (loadpoint) / 1000, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    }
   ]
  },
  {
   "title": "Energía",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "label_set((sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)) /1000, \"series\", \"PV\") or label_set((sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)) /1000, \"series\", \"Grid import\") or label_set(((sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)) * -1) /1000, \"series\", \"Home\") or label_copy(((sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{local_year=\"${__from:date:YYYY}\",loadpoint!~\"$loadpointBlocklist\"}[1d]))[$__range:1d])) by (local_month, loadpoint)) * -1) /1000, \"loadpoint\", \"series\") or label_set(((sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)) * -1) /1000, \"series\", \"Feed-in\")"
    }
   ]
  },
  {
   "title": "Rendimiento específico",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kWh/kWp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$pvEnergy / $installedWattPeak", "type": "math" }
   ]
  },
  {
   "title": "Indicadores",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1 - $gridEnergyIn / ($homeEnergy + $loadpointEnergy)",
     "type": "math"
    },
    {
     "expression": "($pvEnergy - $gridEnergyOut) / $pvEnergy",
     "type": "math"
    }
   ]
  },
  {
   "title": "Métricas",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "WITH (\n  gridImport = sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month),\n  homeEnergy = sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month),\n  loadpointEnergy = sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month),\n  pvEnergy = sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month),\n  gridExport = sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month),\n  autarky = label_set(1 - gridImport / (homeEnergy + loadpointEnergy), \"series\", \"Autarky\"),\n  selfConsumption = label_set((pvEnergy - gridExport) / pvEnergy, \"series\", \"Self-consumption\")\n)\nautarky or selfConsumption"
    }
   ]
  },
  {
   "title": "Energía media diaria",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_set((avg(avg_over_time((last_over_time(evcc_pv_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000), \"series\", \"PV/day\")",
     "legendFormat": "{{series}}"
    },
    {
     "expr": "label_set(((avg(avg_over_time((last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) + avg(avg_over_time(sum(last_over_time(evcc_loadpoint_energy_daily_wh{loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))) / 1000), \"series\", \"Consumption/day\")",
     "legendFormat": "{{series}}"
    },
    {
     "expr": "label_set((avg(avg_over_time((last_over_time(evcc_grid_import_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000), \"series\", \"Grid import/day\")",
     "legendFormat": "{{series}}"
    }
   ]
  },
  {
   "title": "Energía/día",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "max without(local_year,local_month)(evcc_pv_energy_daily_wh{local_year=\"${__from:date:YYYY}\"})",
     "legendFormat": "fotovoltaica"
    },
    { "expression": "$homeEnergy + $loadpointEnergy", "type": "math" },
    {
     "expr": "max without(local_year,local_month)(evcc_grid_import_daily_wh{local_year=\"${__from:date:YYYY}\"})",
     "legendFormat": "Importación de red"
    }
   ]
  },
  { "title": "Casa", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Casa: distribución de energía",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$homeTotalPie - $extSum", "type": "math" },
    {
     "expr": "sort_by_label(sum(sum_over_time(((last_over_time(evcc_ext_energy_daily_wh{title!=\"\",title!~\"$extBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d])))[$__range:1d])) by (title) / 1000, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time(((last_over_time(evcc_aux_energy_daily_wh{title!=\"\",title!~\"$auxBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d])))[$__range:1d])) by (title) / 1000, \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Casa: consumo de energía",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "WITH (\n  other = label_set((sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month) - sum(sum_over_time((last_over_time(evcc_ext_energy_daily_wh{title!=\"\",title!~\"$extBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)) / 1000, \"series\", \"Other\"),\n  ext = label_copy((sum(sum_over_time((last_over_time(evcc_ext_energy_daily_wh{local_year=\"${__from:date:YYYY}\",title!=\"\",title!~\"$extBlocklist\"}[1d]))[$__range:1d])) by (local_month, title)) / 1000, \"title\", \"series\"),\n  aux = label_copy((sum(sum_over_time((last_over_time(evcc_aux_energy_daily_wh{local_year=\"${__from:date:YYYY}\",title!=\"\",title!~\"$auxBlocklist\"}[1d]))[$__range:1d])) by (local_month, title)) / 1000, \"title\", \"series\")\n)\nother or ext or aux"
    }
   ]
  },
  {
   "title": "Total: distribución de energía",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Casa"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (loadpoint) / 1000, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    },
    {
     "expression": "$chargeEnergy - $dischargeEnergy",
     "type": "math",
     "settings": { "displayName": "Batería" }
    }
   ]
  },
  {
   "title": "Casa: distribución de energía",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "WITH (\n  batteryNet = ((sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)) - (sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month))) / 1000,\n  batteryCharge = label_set((batteryNet > 0), \"series\", \"Battery charge\"),\n  batteryDischarge = label_set((batteryNet < 0), \"series\", \"Battery discharge\"),\n  home = label_set((sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)) / 1000, \"series\", \"Home\"),\n  loadpoints = label_copy((sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{local_year=\"${__from:date:YYYY}\",loadpoint!~\"$loadpointBlocklist\"}[1d]))[$__range:1d])) by (local_month, loadpoint)) / 1000, \"loadpoint\", \"series\")\n)\nhome or sort_by_label(loadpoints, \"series\") or batteryCharge or batteryDischarge"
    }
   ]
  },
  {
   "title": "Balance eléctrico",
   "type": "stat",
   "gridPos": { "h": 18, "w": 5, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / sum(count_over_time((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))",
     "legendFormat": "averagePrice"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) * -1",
     "legendFormat": "Comprado"
    },
    {
     "expression": "($purchased * -100) / ($energyPurchased / 1000)",
     "type": "math"
    },
    {
     "expression": "$averagePrice - $weightedAveragePrice",
     "type": "math"
    },
    {
     "expression": "$averagePrice * ($energyPurchased / 1000) / -100",
     "type": "math"
    },
    {
     "expression": "$purchased - $potentialPurchased",
     "type": "math"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))",
     "legendFormat": "Vendido"
    },
    { "expression": "$purchased + $sold", "type": "math" }
   ]
  },
  {
   "title": "Precio dinámico de la electricidad",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ct" } },
   "targets": [
    {
     "expr": "sum without (local_month) ((last_over_time(evcc_grid_import_price_max_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\"}[1d])))",
     "legendFormat": "Max"
    },
    {
     "expr": "sum without (local_month) ((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\"}[1d])))",
     "legendFormat": "Promedio"
    },
    {
     "expr": "sum without (local_month) ((last_over_time(evcc_grid_import_price_effective_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\"}[1d])))",
     "legendFormat": "Precio efectivo de la electricidad"
    },
    {
     "expr": "sum without (local_month) ((last_over_time(evcc_grid_import_price_min_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\"}[1d])))",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Costes de electricidad",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "label_set((sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)), \"series\", \"Purchased\")"
    },
    {
     "expr": "label_set((sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)), \"series\", \"Sold\") and on() (sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) > 0)"
    }
   ]
  },
  { "title": "Batería", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Batería",
   "type": "stat",
   "gridPos": { "h": 18, "w": 5, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))",
     "legendFormat": "batteryChargeTotal"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))",
     "legendFormat": "batteryDischargeTotal"
    },
    {
     "expression": "$batteryDischargeTotal / $batteryChargeTotal",
     "type": "math"
    },
    {
     "expr": "sum(avg_over_time((last_over_time(evcc_battery_soc_daily_max_pct{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / count(avg_over_time((last_over_time(evcc_battery_soc_daily_max_pct{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))",
     "legendFormat": "maxSoc"
    },
    {
     "expr": "sum(avg_over_time((last_over_time(evcc_battery_soc_daily_min_pct{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / count(avg_over_time((last_over_time(evcc_battery_soc_daily_min_pct{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))",
     "legendFormat": "minSoc"
    }
   ]
  },
  {
   "title": "Batería: valores máximos",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 67 },
   "targets": [
    {
     "expr": "max without(local_month)(evcc_battery_soc_daily_max_pct{local_year=\"${__from:date:YYYY}\"})",
     "legendFormat": "SOC máx"
    }
   ]
  },
  {
   "title": "Carga de batería",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "WITH (\n  charge = label_set(sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month) / 1000, \"series\", \"Charge\"),\n  discharge = label_set(sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month) / 1000, \"series\", \"Discharge\")\n)\ncharge or discharge"
    }
   ]
  },
  {
   "title": "Batería: valores mínimos",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 76 },
   "targets": [
    {
     "expr": "min without(local_month)(evcc_battery_soc_daily_min_pct{local_year=\"${__from:date:YYYY}\"})",
     "legendFormat": "SOC mín"
    }
   ]
  },
  {
   "title": "Eficiencia de batería",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_set((sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)) / (sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)), \"series\", \"Battery efficiency\")"
    }
   ]
  },
  { "title": "Consumidores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Total bomba de calor",
   "type": "stat",
   "description": "Energía anual de la bomba de calor en los puntos de carga coincidentes.",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($hpPvWh + $hpBatteryWh + $hpGridWh) / 1000",
     "type": "math"
    }
   ]
  },
  {
   "title": "Mezcla de fuentes de la bomba de calor",
   "type": "bargauge",
   "description": "Participación estimada de FV, descarga de batería y red para el punto de carga de la bomba de calor.",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$hpPvKwh / $hpTotalKwh", "type": "math" },
    { "expression": "$hpBatteryKwh / $hpTotalKwh", "type": "math" },
    { "expression": "$hpGridKwh / $hpTotalKwh", "type": "math" }
   ]
  },
  {
   "title": "Total estaciones de carga",
   "type": "stat",
   "description": "Energía de carga anual en los puntos de carga visibles, excluyendo el punto de carga de la bomba de calor.",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($lpPvWh + $lpBatteryWh + $lpGridWh) / 1000",
     "type": "math"
    }
   ]
  },
  {
   "title": "Mezcla de fuentes de las estaciones de carga",
   "type": "bargauge",
   "description": "Participación estimada de FV, descarga de batería y red para los puntos de carga visibles, excluyendo la bomba de calor.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$lpPvKwh / $lpTotalKwh", "type": "math" },
    { "expression": "$lpBatteryKwh / $lpTotalKwh", "type": "math" },
    { "expression": "$lpGridKwh / $lpTotalKwh", "type": "math" }
   ]
  },
  { "title": "Vehículos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Vehículos",
   "type": "stat",
   "description": "El consumo solo es significativo tras varios meses. La carga externa se ignora y distorsiona el resultado.",
   "gridPos": { "h": 24, "w": 5, "x": 0, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(max by (vehicle) (max_over_time(vehicleOdometer_value{vehicle!=\"\",vehicle!~\"$vehicleBlocklist\"}[10y])), \"vehicle\")",
     "legendFormat": "Odómetro máx: {{vehicle}}"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_vehicle_distance_daily_km{vehicle!=\"\",vehicle!~\"$vehicleBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (vehicle)",
     "legendFormat": "Recorridos: {{vehicle}}"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_vehicle_energy_daily_wh{vehicle!=\"\",vehicle!~\"$vehicleBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (vehicle) / 1000",
     "legendFormat": "Energía: {{vehicle}}"
    },
    {
     "expression": "$vehicleChargedEnergy / $vehicleDrivenKm * 100",
     "type": "math"
    }
   ]
  },
  {
   "title": "Kilómetros mensuales",
   "type": "barchart",
   "description": "Los kilómetros solo se registran mientras un vehículo está conectado. Si se conecta rara vez, pueden faltar kilómetros.",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_copy(sum(sum_over_time((last_over_time(evcc_vehicle_distance_daily_km{vehicle!=\"\",vehicle!~\"$vehicleBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month, vehicle), \"vehicle\", \"series\")"
    }
   ]
  },
  {
   "title": "Energía cargada mensual",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "label_copy(sum(sum_over_time((last_over_time(evcc_vehicle_energy_daily_wh{vehicle!=\"\",vehicle!~\"$vehicleBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month, vehicle) / 1000, \"vehicle\", \"series\")"
    }
   ]
  },
  {
   "title": "Consumo (kWh/100km)",
   "type": "barchart",
   "description": "Los valores son aproximados. La carga externa no está incluida y los kilómetros registrados dependen de la frecuencia con la que se conecta un vehículo.",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "label_copy((sum(sum_over_time((last_over_time(evcc_vehicle_energy_daily_wh{vehicle!=\"\",vehicle!~\"$vehicleBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month, vehicle) / 1000) / (sum(sum_over_time((last_over_time(evcc_vehicle_distance_daily_km{vehicle!=\"\",vehicle!~\"$vehicleBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month, vehicle)) * 100, \"vehicle\", \"series\")"
    }
   ]
  }
 ]
}