{
 "title": "VM: EVCC: Aujourd’hui - Détails",
 "tags": [ "EVCC" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "peakPowerLimit", "label": "Filtre de puissance max / W", "query": "30000" },
   {
    "name": "loadpointBlocklist",
    "label": "Liste de blocage des points de charge",
    "query": "^none$"
   },
   { "name": "extBlocklist", "query": "^none$" },
   { "name": "auxBlocklist", "query": "^none$" },
   {
    "name": "loadpoint",
    "label": "Point de charge",
    "query": "label_values(chargePower_value{db=\"evcc\"}, loadpoint)"
   },
   {
    "name": "energySampleInterval",
    "label": "Intervalle d’échantillonnage énergie",
    "query": "30s"
   },
   { "name": "tariffPriceInterval", "label": "Intervalle tarifaire", "query": "15m" },
   { "name": "evccUrl", "label": "URL EVCC", "query": "${VAR_EVCCURL}" },
   { "name": "inverterPortalTitle", "label": "Nom du portail de l’onduleur", "query": "${VAR_INVERTERPORTALTITLE}" },
   { "name": "inverterPortalUrl", "label": "URL du portail de l’onduleur", "query": "${VAR_INVERTERPORTALURL}" }
  ]
 },
 "panels": [
  { "title": "PV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Énergie PV",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "sort_by_label(range_sum(integrate(avg by (title)(pvPower_value{id!=\"\"}) < $peakPowerLimit)) / 3600000, \"title\")",
     "legendFormat": "{{title}}"
    },
    { "expr": "min(chargePower_value)", "legendFormat": "Énergie" },
    {
     "expr": "range_sum(integrate(avg(pvPower_value{id=\"\"}) < $peakPowerLimit)) / 3600000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Puissance PV",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sort_by_label(avg by (title)(pvPower_value{title!=\"\"}), \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Niveau batterie",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(avg by (title) (batterySoc_value{id!=\"\", title!=\"\"}), \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "batterySoc_value{id=\"\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Puissance batterie",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg by (title)(batteryPower_value{id!=\"\"})",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Prévision",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "range_sum(integrate(avg(tariffSolar_value))) / 3600000",
     "legendFormat": "Prévision"
    },
    {
     "expr": "range_sum(integrate(avg(pvPower_value{id=\"\"}) < $peakPowerLimit)) / 3600000",
     "legendFormat": "Réel"
    },
    { "expr": "min(chargePower_value)", "legendFormat": "Énergie" }
   ]
  },
  {
   "title": "Prévision",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "avg(tariffSolar_value)", "legendFormat": "Prévision" },
    {
     "expr": "avg(pvPower_value{id=\"\"})",
     "legendFormat": "Réel"
    }
   ]
  },
  { "title": "Consommation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Maison : Puissance actuelle",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(homePower_value) - avg(sum(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))",
     "legendFormat": "Autre"
    },
    {
     "expr": "avg(homePower_value) - avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))",
     "legendFormat": "Autre"
    },
    {
     "expr": "avg(homePower_value) - avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))  - avg(sum(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))",
     "legendFormat": "Autre"
    },
    {
     "expr": "sort_by_label(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Maison : Puissance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(homePower_value) - avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))",
     "legendFormat": "Autre"
    },
    {
     "expr": "avg(homePower_value) - avg(sum(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))",
     "legendFormat": "Autre"
    },
    {
     "expr": "avg(homePower_value) - avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"})) - avg(sum(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))",
     "legendFormat": "Autre"
    },
    {
     "expr": "sort_by_label(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Maison : répartition d’énergie",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_sum(integrate(avg(homePower_value)))/3600 - range_sum(integrate(avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))))/3600 - range_sum(integrate(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"})))/3600",
     "legendFormat": "Autre"
    },
    {
     "expr": "range_sum(integrate(avg(homePower_value)))/3600 - range_sum(integrate(avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))))/3600 ",
     "legendFormat": "Autre"
    },
    {
     "expr": "range_sum(integrate(avg(homePower_value)))/3600 - range_sum(integrate(avg(sum(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))))/3600 ",
     "legendFormat": "Autre"
    },
    {
     "expr": "sort_by_label(range_sum(integrate(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"})))/3600, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(range_sum(integrate(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"})))/3600, \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Maison : Énergie",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(integrate(homePower_value offset -1h))/3600 - sum(integrate(extPower_value{title!=\"\", title !~ \"$extBlocklist\"} offset -1h))/3600 - sum(integrate(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"} offset -1h))/3600",
     "legendFormat": "Autre"
    },
    {
     "expr": "sum(integrate(homePower_value offset -1h))/3600 - sum(integrate(extPower_value{title!=\"\", title !~ \"$extBlocklist\"} offset -1h))/3600",
     "legendFormat": "Autre"
    },
    {
     "expr": "sum(integrate(homePower_value offset -1h))/3600 - sum(integrate(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"} offset -1h))/3600",
     "legendFormat": "Autre"
    },
    {
     "expr": "sort_by_label(integrate(extPower_value{title!=\"\", title !~ \"$extBlocklist\"} offset -1h)/3600, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(integrate(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}offset -1h)/3600, \"title\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total : répartition d’énergie",
   "type": "piechart",
   "description": "La formule pour « Autre » doit être ajustée en fonction de la disponibilité des compteurs AUX et EXT. Voir https://github.com/ha-puzzles/evcc-grafana-dashboards/tree/main/dashboards#formel-für-sonstige-anpassen pour plus de détails.",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_sum(integrate(avg(homePower_value)))/3600",
     "legendFormat": "Maison"
    },
    {
     "expr": "sort_by_label(sum by (loadpoint)(range_sum (integrate(chargePower_value{loadpoint!=\"\", loadpoint !~ \"$loadpointBlocklist\"})) / 3600), \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    }
   ]
  },
  {
   "title": "Total : Énergie",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(integrate(homePower_value offset -1h))/3600",
     "legendFormat": "Maison"
    },
    {
     "expr": "sort_by_label(avg by(loadpoint)(integrate(chargePower_value{loadpoint!=\"\"} offset -1h))/3600, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    }
   ]
  },
  { "title": "Tarifs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Prix de l'électricité",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(avg(tariffGrid_value)[1d])",
     "legendFormat": "Max"
    },
    {
     "expr": "avg_over_time(avg(tariffGrid_value)[1d])",
     "legendFormat": "Moyenne"
    },
    {
     "expr": "min_over_time(avg(tariffGrid_value)[1d])",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Prix de l'électricité",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 56 },
   "targets": [
    {
     "expr": "avg(tariffGrid_value offset -$tariffPriceInterval)",
     "legendFormat": "Prix"
    },
    {
     "expr": "clamp_min(avg(gridPower_value offset -$tariffPriceInterval), 0)",
     "legendFormat": "Import réseau"
    }
   ]
  },
  {
   "title": "Coûts",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_sum(avg(tariffGrid_value) * integrate(clamp_min(avg(gridPower_value), 0)) /3600000)",
     "legendFormat": "Acheté"
    },
    {
     "expr": "range_sum(avg(tariffFeedIn_value) * integrate(clamp_max(avg(gridPower_value), 0)) /3600000)",
     "legendFormat": "Vendu"
    },
    { "expression": "$bought + $sold", "type": "math" }
   ]
  },
  {
   "title": "Coûts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "avg(tariffGrid_value offset -$tariffPriceInterval) * integrate(clamp_min(avg(gridPower_value offset -$tariffPriceInterval), 0)) /3600000",
     "legendFormat": "Acheté"
    },
    {
     "expr": "avg(tariffFeedIn_value offset -$tariffPriceInterval) * integrate(clamp_max(avg(gridPower_value offset -$tariffPriceInterval), 0)) /3600000",
     "legendFormat": "Vendu"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "g/kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(avg(tariffCo2_value)[1d])",
     "legendFormat": "Max"
    },
    {
     "expr": "avg_over_time(avg(tariffCo2_value)[1d])",
     "legendFormat": "Moyenne"
    },
    {
     "expr": "min_over_time(avg(tariffCo2_value)[1d])",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 74 },
   "targets": [
    {
     "expr": "tariffCo2_value offset -$tariffPriceInterval",
     "legendFormat": "CO2"
    },
    { "expr": "clamp_min(gridPower_value, 0)", "legendFormat": "Import réseau" }
   ]
  },
  { "title": "Réseau", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Courants/phase",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(avg(gridCurrents_l1))",
     "legendFormat": "Courant L1"
    },
    {
     "expr": "last_over_time(avg(gridCurrents_l2))",
     "legendFormat": "Courant L2"
    },
    {
     "expr": "last_over_time(avg(gridCurrents_l3))",
     "legendFormat": "Courant L3"
    }
   ]
  },
  {
   "title": "Courants/phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "avg(gridCurrents_l1)", "legendFormat": "Courant L1" },
    { "expr": "avg(gridCurrents_l2)", "legendFormat": "Courant L2" },
    { "expr": "avg(gridCurrents_l3)", "legendFormat": "Courant L3" }
   ]
  },
  {
   "title": "Puissance/phase",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(avg(gridPowers_l1))",
     "legendFormat": "Puissance L1"
    },
    {
     "expr": "last_over_time(avg(gridPowers_l2))",
     "legendFormat": "Puissance L2"
    },
    {
     "expr": "last_over_time(avg(gridPowers_l3))",
     "legendFormat": "Puissance L3"
    }
   ]
  },
  {
   "title": "Puissance/phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "avg(gridPowers_l1)", "legendFormat": "Puissance L1" },
    { "expr": "avg(gridPowers_l2)", "legendFormat": "Puissance L2" },
    { "expr": "avg(gridPowers_l3)", "legendFormat": "Puissance L3" }
   ]
  },
  { "title": "Point de charge $loadpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }, "repeat": "loadpoint" },
  {
   "title": "Courants de charge/phase: $loadpoint",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(avg(chargeCurrents_l1{loadpoint=\"$loadpoint\"}))",
     "legendFormat": "Courant L1"
    },
    {
     "expr": "last_over_time(avg(chargeCurrents_l2{loadpoint=\"$loadpoint\"}))",
     "legendFormat": "Courant L2"
    },
    {
     "expr": "last_over_time(avg(chargeCurrents_l2{loadpoint=\"$loadpoint\"}))",
     "legendFormat": "Courant L3"
    }
   ]
  },
  {
   "title": "Courants de charge/phase: $loadpoint",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "avg(chargeCurrents_l1 {loadpoint=\"$loadpoint\"})",
     "legendFormat": "Courant L1"
    },
    {
     "expr": "avg(chargeCurrents_l2 {loadpoint=\"$loadpoint\"})",
     "legendFormat": "Courant L2"
    },
    {
     "expr": "avg(chargeCurrents_l3 {loadpoint=\"$loadpoint\"})",
     "legendFormat": "Courant L3"
    }
   ]
  },
  {
   "title": "Phases : $loadpoint",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 112 },
   "targets": [
    {
     "expr": "avg(phasesActive_value{loadpoint=\"$loadpoint\"}) < 2",
     "legendFormat": "1 phase"
    },
    {
     "expr": "avg(phasesActive_value{loadpoint=\"$loadpoint\"}) > 2",
     "legendFormat": "3 phases"
    }
   ]
  },
  {
   "title": "Puissance de charge: $loadpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(chargePower_value {loadpoint=\"$loadpoint\"})",
     "legendFormat": "Puissance de charge"
    }
   ]
  }
 ]
}