{
 "title": "VM : EVCC : Année",
 "tags": [ "EVCC" ],
 "time": { "from": "now-1y/y", "to": "now/y" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "dbLabel", "label": "Label DB", "query": "evcc" },
   {
    "name": "loadpointBlocklist",
    "label": "Liste de blocage point de charge",
    "query": "^none$"
   },
   {
    "name": "vehicleBlocklist",
    "label": "Liste de blocage véhicule",
    "query": "^Mr White.*$|^.*\\(offline\\)$|^Altherma.*$"
   },
   { "name": "extBlocklist", "label": "Liste de blocage EXT", "query": "^none$" },
   { "name": "auxBlocklist", "label": "Liste de blocage AUX", "query": "^none$" },
   {
    "name": "heatPumpLoadpointRegex",
    "label": "Correspondance du point de charge de la pompe à chaleur",
    "query": "(?i).*(daikin-wp|wp|warmepumpe|wärmepumpe|heat pump).*"
   },
   { "name": "installedWattPeak", "label": "installedWattPeak", "query": "20" },
   { "name": "evccUrl", "label": "URL EVCC", "query": "${VAR_EVCCURL}" },
   { "name": "inverterPortalTitle", "label": "Nom du portail de l’onduleur", "query": "${VAR_INVERTERPORTALTITLE}" },
   { "name": "inverterPortalUrl", "label": "URL du portail de l’onduleur", "query": "${VAR_INVERTERPORTALURL}" }
  ]
 },
 "panels": [
  { "title": "PV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Totaux énergie",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "PV"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Import réseau"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Maison"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{db=\"$dbLabel\",loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (loadpoint) / 1000, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Injection"
    }
   ]
  },
  {
   "title": "Énergie",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "label_set((sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) by (local_month)) /1000, \"series\", \"PV\") or label_set((sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) by (local_month)) /1000, \"series\", \"Grid import\") or label_set(((sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) by (local_month)) * -1) /1000, \"series\", \"Home\") or label_copy(((sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",loadpoint!~\"$loadpointBlocklist\"}[1d]))[400d:1d])) by (local_month, loadpoint)) * -1) /1000, \"loadpoint\", \"series\") or label_set(((sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) by (local_month)) * -1) /1000, \"series\", \"Feed-in\")"
    }
   ]
  },
  {
   "title": "Jauges indicateurs",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1 - $gridEnergyIn / ($homeEnergy + $loadpointEnergy)",
     "type": "math"
    },
    {
     "expression": "($pvEnergy - $gridEnergyOut) / $pvEnergy",
     "type": "math"
    }
   ]
  },
  {
   "title": "Indicateurs",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_set(1 - (sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) by (local_month)) / ((sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) by (local_month)) + (sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{db=\"$dbLabel\",loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) by (local_month))), \"series\", \"Autarky\") or label_set(((sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) by (local_month)) - (sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) by (local_month))) / (sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) by (local_month)), \"series\", \"Self-consumption\")"
    }
   ]
  },
  {
   "title": "Énergie moyenne/jour",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_set((avg(avg_over_time((last_over_time(evcc_pv_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000), \"series\", \"PV/day\")",
     "legendFormat": "{{series}}"
    },
    {
     "expr": "label_set(((avg(avg_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) + avg(avg_over_time(sum(last_over_time(evcc_loadpoint_energy_daily_wh{db=\"$dbLabel\",loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))) / 1000), \"series\", \"Consumption/day\")",
     "legendFormat": "{{series}}"
    },
    {
     "expr": "label_set((avg(avg_over_time((last_over_time(evcc_grid_import_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000), \"series\", \"Grid import/day\")",
     "legendFormat": "{{series}}"
    }
   ]
  },
  {
   "title": "Énergie/jour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "max without(local_year,local_month)(evcc_pv_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"})",
     "legendFormat": "PV"
    },
    { "expression": "$homeEnergy + $loadpointEnergy", "type": "math" },
    {
     "expr": "max without(local_year,local_month)(evcc_grid_import_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"})",
     "legendFormat": "Import réseau"
    }
   ]
  },
  { "title": "Maison", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Maison : répartition d’énergie",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$homeTotalPie - $extSum", "type": "math" },
    {
     "expr": "sort_by_label(sum(sum_over_time(((last_over_time(evcc_ext_energy_daily_wh{db=\"$dbLabel\",title!=\"\",title!~\"$extBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d])))[$__range:1d])) by (title) / 1000, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time(((last_over_time(evcc_aux_energy_daily_wh{db=\"$dbLabel\",title!=\"\",title!~\"$auxBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d])))[$__range:1d])) by (title) / 1000, \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Maison : consommation d’énergie",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "label_set((sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) by (local_month) - sum(sum_over_time((last_over_time(evcc_ext_energy_daily_wh{db=\"$dbLabel\",title!=\"\",title!~\"$extBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) by (local_month)) / 1000, \"series\", \"Other\") or label_copy(((sum(sum_over_time((last_over_time(evcc_ext_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",title!=\"\",title!~\"$extBlocklist\"}[1d]))[400d:1d])) by (local_month, title)) /1000), \"title\", \"series\") or label_copy(((sum(sum_over_time((last_over_time(evcc_aux_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",title!=\"\",title!~\"$auxBlocklist\"}[1d]))[400d:1d])) by (local_month, title)) /1000), \"title\", \"series\")"
    }
   ]
  },
  {
   "title": "Total : répartition d’énergie",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Maison"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{db=\"$dbLabel\",loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (loadpoint) / 1000, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    },
    {
     "expression": "$chargeEnergy - $dischargeEnergy",
     "type": "math",
     "settings": { "displayName": "Batterie" }
    }
   ]
  },
  {
   "title": "Maison : répartition d’énergie",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "label_set(((sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) by (local_month) ) - (sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) by (local_month))) / 1000, \"series\", \"Battery\") or label_set((sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) by (local_month)) /1000, \"series\", \"Home\") or label_copy(((sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",loadpoint!~\"$loadpointBlocklist\"}[1d]))[400d:1d])) by (local_month, loadpoint)) /1000), \"loadpoint\", \"series\")"
    }
   ]
  },
  {
   "title": "Bilan électrique",
   "type": "stat",
   "gridPos": { "h": 18, "w": 5, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) / sum(count_over_time((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d]))",
     "legendFormat": "averagePrice"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) * -1",
     "legendFormat": "Acheté"
    },
    {
     "expression": "($purchased * -100) / ($energyPurchased / 1000)",
     "type": "math"
    },
    {
     "expression": "$averagePrice - $weightedAveragePrice",
     "type": "math"
    },
    {
     "expression": "$averagePrice * ($energyPurchased / 1000) / -100",
     "type": "math"
    },
    {
     "expression": "$purchased - $potentialPurchased",
     "type": "math"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d]))",
     "legendFormat": "Vendu"
    },
    { "expression": "$purchased + $sold", "type": "math" }
   ]
  },
  {
   "title": "Prix dynamique de l’électricité",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ct" } },
   "targets": [
    {
     "expr": "sum without (local_month) ((last_over_time(evcc_grid_import_price_max_daily_ct_per_kwh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d])))",
     "legendFormat": "Max"
    },
    {
     "expr": "sum without (local_month) ((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d])))",
     "legendFormat": "Moyenne"
    },
    {
     "expr": "sum without (local_month) ((last_over_time(evcc_grid_import_price_effective_daily_ct_per_kwh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d])))",
     "legendFormat": "Prix effectif de l’électricité"
    },
    {
     "expr": "sum without (local_month) ((last_over_time(evcc_grid_import_price_min_daily_ct_per_kwh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d])))",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Coûts d’électricité",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "label_set((sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) by (local_month)), \"series\", \"Purchased\") or (label_set((sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) by (local_month)), \"series\", \"Sold\") and on() (sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[400d:1d])) > 0))"
    }
   ]
  },
  { "title": "Batterie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Batterie",
   "type": "stat",
   "gridPos": { "h": 18, "w": 5, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))",
     "legendFormat": "batteryChargeTotal"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))",
     "legendFormat": "batteryDischargeTotal"
    },
    {
     "expression": "$batteryDischargeTotal / $batteryChargeTotal",
     "type": "math"
    },
    {
     "expr": "sum(avg_over_time((last_over_time(evcc_battery_soc_daily_max_pct{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / count(avg_over_time((last_over_time(evcc_battery_soc_daily_max_pct{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))",
     "legendFormat": "maxSoc"
    },
    {
     "expr": "sum(avg_over_time((last_over_time(evcc_battery_soc_daily_min_pct{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / count(avg_over_time((last_over_time(evcc_battery_soc_daily_min_pct{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))",
     "legendFormat": "minSoc"
    }
   ]
  },
  {
   "title": "Batterie : valeurs maximales",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 67 },
   "targets": [
    {
     "expr": "max without(local_month)(evcc_battery_soc_daily_max_pct{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"})",
     "legendFormat": "SOC max"
    }
   ]
  },
  {
   "title": "Charge batterie",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "label_set(sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month) / 1000, \"series\", \"Charge\") or label_set(sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month) / 1000, \"series\", \"Discharge\")"
    }
   ]
  },
  {
   "title": "Batterie : valeurs minimales",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 76 },
   "targets": [
    {
     "expr": "min without(local_month)(evcc_battery_soc_daily_min_pct{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"})",
     "legendFormat": "SOC min"
    }
   ]
  },
  {
   "title": "Rendement batterie",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_set((sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)) / (sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)), \"series\", \"Battery efficiency\")"
    }
   ]
  },
  { "title": "Consommateurs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Total pompe à chaleur",
   "type": "stat",
   "description": "Énergie annuelle de la pompe à chaleur sur les points de charge correspondants.",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($hpPvWh + $hpBatteryWh + $hpGridWh) / 1000",
     "type": "math"
    }
   ]
  },
  {
   "title": "Répartition des sources de la pompe à chaleur",
   "type": "bargauge",
   "description": "Part estimée du PV, de la décharge batterie et du réseau pour le point de charge de la pompe à chaleur.",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$hpPvKwh / $hpTotalKwh", "type": "math" },
    { "expression": "$hpBatteryKwh / $hpTotalKwh", "type": "math" },
    { "expression": "$hpGridKwh / $hpTotalKwh", "type": "math" }
   ]
  },
  {
   "title": "Total bornes de recharge",
   "type": "stat",
   "description": "Énergie de charge annuelle sur les points de charge visibles, hors point de charge de la pompe à chaleur.",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($lpPvWh + $lpBatteryWh + $lpGridWh) / 1000",
     "type": "math"
    }
   ]
  },
  {
   "title": "Répartition des sources des bornes de recharge",
   "type": "bargauge",
   "description": "Part estimée du PV, de la décharge batterie et du réseau pour les points de charge visibles, hors pompe à chaleur.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$lpPvKwh / $lpTotalKwh", "type": "math" },
    { "expression": "$lpBatteryKwh / $lpTotalKwh", "type": "math" },
    { "expression": "$lpGridKwh / $lpTotalKwh", "type": "math" }
   ]
  },
  { "title": "Véhicules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Véhicules",
   "type": "stat",
   "description": "La consommation n’est pertinente qu’après plusieurs mois. La charge externe est ignorée et fausse le résultat.",
   "gridPos": { "h": 24, "w": 5, "x": 0, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(max by (vehicle) (max_over_time(vehicleOdometer_value{db=\"$dbLabel\",vehicle!=\"\",vehicle!~\"$vehicleBlocklist\"}[10y])), \"vehicle\")",
     "legendFormat": "Kilométrage max : {{vehicle}}"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_vehicle_distance_daily_km{db=\"$dbLabel\",vehicle!=\"\",vehicle!~\"$vehicleBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (vehicle)",
     "legendFormat": "Parcourus: {{vehicle}}"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_vehicle_energy_daily_wh{db=\"$dbLabel\",vehicle!=\"\",vehicle!~\"$vehicleBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (vehicle) / 1000",
     "legendFormat": "Énergie : {{vehicle}}"
    },
    {
     "expression": "$vehicleChargedEnergy / $vehicleDrivenKm * 100",
     "type": "math"
    }
   ]
  },
  {
   "title": "Kilomètres mensuels",
   "type": "barchart",
   "description": "Les kilomètres ne sont relevés que lorsqu’un véhicule est branché. S’il est branché rarement, des kilomètres peuvent manquer.",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_copy(sum(sum_over_time((last_over_time(evcc_vehicle_distance_daily_km{db=\"$dbLabel\",vehicle!=\"\",vehicle!~\"$vehicleBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month, vehicle), \"vehicle\", \"series\")"
    }
   ]
  },
  {
   "title": "Énergie chargée mensuelle",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "label_copy(sum(sum_over_time((last_over_time(evcc_vehicle_energy_daily_wh{db=\"$dbLabel\",vehicle!=\"\",vehicle!~\"$vehicleBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month, vehicle) / 1000, \"vehicle\", \"series\")"
    }
   ]
  },
  {
   "title": "Consommation (kWh/100km)",
   "type": "barchart",
   "description": "Les valeurs sont approximatives. La charge externe n’est pas incluse et les kilomètres relevés dépendent de la fréquence de branchement du véhicule.",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "label_copy((sum(sum_over_time((last_over_time(evcc_vehicle_energy_daily_wh{db=\"$dbLabel\",vehicle!=\"\",vehicle!~\"$vehicleBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month, vehicle) / 1000) / (sum(sum_over_time((last_over_time(evcc_vehicle_distance_daily_km{db=\"$dbLabel\",vehicle!=\"\",vehicle!~\"$vehicleBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month, vehicle)) * 100, \"vehicle\", \"series\")"
    }
   ]
  }
 ]
}