{
 "title": "VM : EVCC : Toute la période",
 "tags": [ "EVCC" ],
 "time": { "from": "now-2y/y", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "dbLabel", "label": "Label DB", "query": "evcc" },
   { "name": "peakPowerLimit", "label": "Limite de puissance max", "query": "30000" },
   {
    "name": "energySampleInterval",
    "label": "Intervalle d’échantillonnage énergie",
    "query": "30s"
   },
   { "name": "tariffPriceInterval", "label": "Intervalle tarifaire", "query": "15m" },
   {
    "name": "loadpointBlocklist",
    "label": "Liste de blocage point de charge",
    "query": "^none$"
   },
   { "name": "extBlocklist", "label": "Liste de blocage EXT", "query": "^none$" },
   { "name": "auxBlocklist", "label": "Liste de blocage AUX", "query": "^none$" },
   { "name": "installedWattPeak", "label": "installedWattPeak", "query": "20" },
   { "name": "vehicleBlocklist", "label": "Liste de blocage véhicule", "query": "^Altherma-3$" },
   {
    "name": "vehicle",
    "label": "Véhicule",
    "query": {
     "query": "label_values(sessionPricePerKWh_value{db=\"$dbLabel\",vehicle!=\"\",vehicle!~\"$vehicleBlocklist\"}, vehicle)"
    }
   },
   { "name": "vVerbrauch", "label": "Consommation thermique l/100km", "query": "6" },
   { "name": "spritKosten", "label": "Prix du carburant/l", "query": "1.75" },
   { "name": "purchasePricePv", "label": "Prix d’achat PV", "query": "24884" },
   { "name": "batteryPurchasePrice", "label": "Prix d’achat batterie", "query": "5500" },
   { "name": "runningCosts", "label": "Coûts courants", "query": "100" },
   { "name": "speicherkapazitaet", "label": "Capacité batterie / Wh", "query": "9500" },
   { "name": "evccUrl", "label": "URL EVCC", "query": "${VAR_EVCCURL}" },
   { "name": "inverterPortalTitle", "label": "Nom du portail de l’onduleur", "query": "${VAR_INVERTERPORTALTITLE}" },
   { "name": "inverterPortalUrl", "label": "URL du portail de l’onduleur", "query": "${VAR_INVERTERPORTALURL}" }
  ]
 },
 "panels": [
  { "title": "Énergie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Totaux énergie",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Import réseau"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "PV"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Maison"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{db=\"$dbLabel\",loadpoint!~\"$loadpointBlocklist\"}[1d]))[$__range:1d])) by (loadpoint) / 1000, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Injection"
    }
   ]
  },
  {
   "title": "Rendement annuel",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Rendement mensuel/an",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "Jauges indicateurs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1 - $gridEnergyIn / ($homeEnergy + $loadpointEnergy)",
     "type": "math"
    },
    {
     "expression": "($pvEnergy - $gridEnergyOut) / $pvEnergy",
     "type": "math"
    }
   ]
  },
  {
   "title": "Consommation maison annuelle",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Consommation maison mensuelle/an",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "Import réseau annuel",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Import réseau mensuel/an",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "batteryChargeTotal"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "batteryDischargeTotal"
    },
    {
     "expression": "$batteryDischargeTotal / $batteryChargeTotal",
     "type": "math"
    },
    {
     "expr": "sum(avg_over_time((last_over_time(evcc_battery_soc_daily_max_pct{db=\"$dbLabel\"}[1d]))[$__range:1d])) / count(avg_over_time((last_over_time(evcc_battery_soc_daily_max_pct{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "maxSoc"
    },
    {
     "expr": "sum(avg_over_time((last_over_time(evcc_battery_soc_daily_min_pct{db=\"$dbLabel\"}[1d]))[$__range:1d])) / count(avg_over_time((last_over_time(evcc_battery_soc_daily_min_pct{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "minSoc"
    }
   ]
  },
  {
   "title": "Injection annuelle",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Injection mensuelle/an",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "Jours avec le meilleur rendement",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "max without(local_year,local_month)(evcc_pv_energy_daily_wh{db=\"$dbLabel\"}) / 1000",
     "legendFormat": "Énergie PV"
    }
   ]
  },
  {
   "title": "Injections maximales",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "max without(local_year,local_month)(evcc_grid_export_daily_wh{db=\"$dbLabel\"}) / 1000",
     "legendFormat": "Injection"
    }
   ]
  },
  {
   "title": "Consommations maison maximales",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "max without(local_year,local_month)(evcc_home_energy_daily_wh{db=\"$dbLabel\"}) / 1000",
     "legendFormat": "Consommation maison"
    }
   ]
  },
  { "title": "Santé de l’installation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Moyenne des 30 meilleurs jours/an",
   "type": "barchart",
   "description": "Utilise le rendement moyen des 30 meilleurs jours par an. Cela peut aider à identifier une dégradation possible, mais doit être interprété dans son contexte. Une année isolée n’est pas concluante.",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "last_over_time(evcc_pv_top30_mean_yearly_wh{db=\"$dbLabel\"}[$__range])",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Moyenne des 5 meilleurs jours/mois",
   "type": "barchart",
   "description": "Utilise le rendement moyen des 5 meilleurs jours par mois. Cela peut aider à identifier une dégradation possible, mais doit être interprété dans son contexte. Un mois isolé n’est pas concluant.",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "last_over_time(evcc_pv_top5_mean_monthly_wh{db=\"$dbLabel\"}[$__range])",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  { "title": "Finances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Coûts mensuels",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "label_join(label_set(clamp_min((sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month) - sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)), 0), \"kind\", \"Costs\"), \"series\", \" \", \"local_year\", \"kind\") or (label_join(label_set(clamp_min((sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month) - sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)), 0), \"kind\", \"Income\"), \"series\", \" \", \"local_year\", \"kind\") and on (local_year) (sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year) > 0))"
    }
   ]
  },
  { "title": "Bilan", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Bilan électrique",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / sum(count_over_time((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "averagePrice"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) * -1",
     "legendFormat": "Acheté"
    },
    {
     "expression": "($purchased * -100) / ($energyPurchased / 1000)",
     "type": "math"
    },
    {
     "expression": "$averagePrice - $weightedAveragePrice",
     "type": "math"
    },
    {
     "expression": "$averagePrice * ($energyPurchased / 1000) / -100",
     "type": "math"
    },
    {
     "expression": "$purchased - $potentialPurchased",
     "type": "math"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "Vendu"
    },
    { "expression": "$purchased + $sold", "type": "math" }
   ]
  },
  {
   "title": "Amortissement installation PV",
   "type": "stat",
   "description": "Pour moins de 365 jours de données, les valeurs sont extrapolées sur une année complète avec une imprécision dépendant de la période couverte.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$potentialHomePrice + $potentialLoadpointPrice",
     "type": "math"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "energyPurchasedPrice"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "energySoldPrice"
    },
    {
     "expression": "$energyPurchasedPrice - $energySoldPrice",
     "type": "math"
    },
    {
     "expression": "$potentialTotalPrice - $energyTotalPrice",
     "type": "math"
    },
    {
     "expr": "sum(count_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "numberOfMeasuredDays"
    },
    {
     "expression": "$refluxOfCapital * 365 / $numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$purchasePricePv / ($refluxOfCapitalYearly - $runningCosts)",
     "type": "math"
    },
    {
     "expression": "($refluxOfCapitalYearly - $runningCosts) / $purchasePricePv",
     "type": "math"
    }
   ]
  },
  {
   "title": "Amortissement batterie",
   "type": "stat",
   "description": "Pour moins de 365 jours de données, les valeurs sont extrapolées sur une année complète avec une imprécision dépendant de la période couverte.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "chargedEnergy"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "dischargedEnergy"
    },
    {
     "expression": "1 - ($dischargedEnergy / $chargedEnergy)",
     "type": "math"
    },
    {
     "expr": "sum(count_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "numberOfMeasuredDays"
    },
    {
     "expression": "($chargedEnergy / $speicherkapazitaet) * 365 / $numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "($batteryDischargeCost - $batteryChargeFeedInCost) * 365 / $numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$batteryPurchasePrice / $batteryPayback",
     "type": "math"
    },
    {
     "expression": "$batteryPayback / $batteryPurchasePrice",
     "type": "math"
    }
   ]
  },
  { "title": "Véhicules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Coûts de conduite $vehicle",
   "type": "stat",
   "description": "Les valeurs sont des estimations approximatives basées sur des moyennes. Les sessions de charge externes ne sont pas incluses.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 93 },
   "repeat": "vehicle",
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_vehicle_distance_daily_km{db=\"$dbLabel\",vehicle=\"$vehicle\"}[1d]))[$__range:1d]))",
     "legendFormat": "drivenKm"
    },
    {
     "expression": "$chargedEnergy / ($drivenKm / 100)",
     "type": "math"
    },
    {
     "expr": "avg(avg_over_time(sessionSolarPercentage_value{db=\"$dbLabel\",vehicle=\"$vehicle\"}[$__range]))",
     "legendFormat": "solarPercent"
    },
    {
     "expr": "avg(avg_over_time(sessionPricePerKWh_value{db=\"$dbLabel\",vehicle=\"$vehicle\"}[$__range]))",
     "legendFormat": "chargePrice"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_potential_vehicle_charge_cost_daily_eur{db=\"$dbLabel\",vehicle=\"$vehicle\"}[1d]))[$__range:1d]))",
     "legendFormat": "electricDriveCostNoPV"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_vehicle_charge_cost_daily_eur{db=\"$dbLabel\",vehicle=\"$vehicle\"}[1d]))[$__range:1d]))",
     "legendFormat": "electricDriveCost"
    },
    {
     "expression": "$electricDriveCostNoPV - $electricDriveCost",
     "type": "math"
    },
    {
     "expression": "$drivenKm / 100 * $vVerbrauch * $spritKosten",
     "type": "math"
    },
    {
     "expression": "$iceDriveCost - $electricDriveCost",
     "type": "math"
    }
   ]
  }
 ]
}