{
 "title": "VM: EVCC: Aujourd’hui",
 "tags": [ "EVCC" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "dashboardBuild", "label": "Build", "query": "info" },
   { "name": "peakPowerLimit", "label": "Filtre de puissance max / W", "query": "${VAR_PEAKPOWERLIMIT}" },
   { "name": "evccUrl", "label": "URL EVCC", "query": "${VAR_EVCCURL}" },
   { "name": "inverterPortalTitle", "label": "Nom du portail de l’onduleur", "query": "${VAR_INVERTERPORTALTITLE}" },
   { "name": "inverterPortalUrl", "label": "URL du portail de l’onduleur", "query": "${VAR_INVERTERPORTALURL}" },
   {
    "name": "loadpointBlocklist",
    "label": "Liste de blocage des points de charge",
    "query": "${VAR_LOADPOINTBLOCKLIST}"
   },
   { "name": "vehicleBlocklist", "label": "Liste de blocage des véhicules", "query": "${VAR_VEHICLEBLOCKLIST}" },
   {
    "name": "energySampleInterval",
    "label": "Intervalle d’échantillonnage énergie",
    "query": "${VAR_ENERGYSAMPLEINTERVAL}"
   },
   { "name": "tariffPriceInterval", "label": "Intervalle tarifaire", "query": "${VAR_TARIFFPRICEINTERVAL}" }
  ]
 },
 "panels": [
  {
   "title": "Puissance",
   "type": "gauge",
   "gridPos": { "h": 24, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kW" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(pvPower_value{id=\"\"} / 1000)",
     "legendFormat": "PV"
    },
    { "expr": "avg(gridPower_value / 1000)", "legendFormat": "Réseau" },
    { "expr": "avg(homePower_value / -1000)", "legendFormat": "Maison" },
    {
     "expr": "avg(batteryPower_value{id=\"\"} / 1000)",
     "legendFormat": "Batterie"
    },
    {
     "expr": "sort_by_label(avg by(loadpoint) (chargePower_value / -1000),\"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    }
   ]
  },
  {
   "title": "Power history",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 16, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "max_over_time(pvPower_value{id=\"\"}[$__interval]) < $peakPowerLimit",
     "legendFormat": "PV"
    },
    {
     "expr": "avg_over_time(gridPower_value[$__interval]) < $peakPowerLimit",
     "legendFormat": "Réseau"
    },
    {
     "expr": "max_over_time(homePower_value[$__interval]) * (-1) > (-$peakPowerLimit)",
     "legendFormat": "Maison"
    },
    {
     "expr": "avg_over_time(batteryPower_value{id=\"\"}[$__interval]) < $peakPowerLimit",
     "legendFormat": "Batterie"
    },
    {
     "expr": "max by (loadpoint) (max_over_time(chargePower_value{id=\"\", loadpoint!~\"$loadpointBlocklist\"}[$__interval])) * (-1) > (-$peakPowerLimit)",
     "legendFormat": "{{loadpoint}}"
    },
    { "expr": "avg(tariffSolar_value)", "legendFormat": "Prévision PV" }
   ]
  },
  {
   "title": "Niveaux batterie",
   "type": "timeseries",
   "description": "Noir : seuil de priorité pour la charge du véhicule",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(batterySoc_value{id=\"\"}) < 100",
     "legendFormat": "Batterie"
    },
    {
     "expr": "sort_by_label(avg by(vehicle) (vehicleSoc_value{vehicle!=\"\", vehicle!~\"$vehicleBlocklist\"}), \"vehicle\")",
     "legendFormat": "{{vehicle}}"
    },
    {
     "expr": "last_over_time(prioritySoc_value[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indicateurs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1 - $gridEnergyIn/($homeEnergy+$loadpointEnergy)",
     "type": "math"
    },
    {
     "expr": "clamp_max(clamp_min((sum(integrate(((pvPower_value{id=\"\"} < $peakPowerLimit) default 0)[$__range:$energySampleInterval]) / 3600) - sum(integrate((((gridPower_value < 0 <$peakPowerLimit) default 0)[$__range:$energySampleInterval]) / -3600))) / clamp_min(sum(integrate(((pvPower_value{id=\"\"} < $peakPowerLimit) default 0)[$__range:$energySampleInterval]) / 3600), 0.001), 0), 1)",
     "legendFormat": "Autoconsommation"
    }
   ]
  },
  {
   "title": "Metric history",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "1 - $gridEnergyIn/($homeEnergy+$loadpointEnergy)",
     "type": "math"
    },
    {
     "expression": "($pvEnergy - $gridEnergyOut) / $pvEnergy",
     "type": "math"
    }
   ]
  },
  {
   "title": "Énergie",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 13 },
   "targets": [
    {
     "expr": "sum without(host) (integrate(((pvPower_value{id=\"\"} < $peakPowerLimit) default 0)[$__range:$energySampleInterval]) / 3600000)",
     "legendFormat": "PV"
    },
    {
     "expr": "sum without(host) (integrate(\n  ((gridPower_value > 0 <$peakPowerLimit) default 0) [$__range:$energySampleInterval]\n) / 3600000)",
     "legendFormat": "Import réseau"
    },
    {
     "expr": "sum without(host) (integrate(\n  ((gridPower_value < 0 <$peakPowerLimit) default 0) [$__range:$energySampleInterval]\n) / 3600000)",
     "legendFormat": "Injection"
    },
    {
     "expr": "sum without(host) (integrate(((homePower_value{id=\"\"} < $peakPowerLimit) default 0)[$__range:$energySampleInterval]) / -3600000)",
     "legendFormat": "Maison"
    },
    {
     "expr": "sum without(host) (integrate(\n  ((batteryPower_value {id=\"\"} > 0 <$peakPowerLimit) default 0) [$__range:$energySampleInterval]\n) / 3600000)",
     "legendFormat": "Décharge batterie"
    },
    {
     "expr": "sum without(host) (integrate(\n  ((batteryPower_value {id=\"\"} < 0 <$peakPowerLimit) default 0) [$__range:$energySampleInterval]\n) / 3600000)",
     "legendFormat": "Charge batterie"
    },
    {
     "expr": "sort_by_label(\n  sum without(host) (\n    integrate(\n      ((chargePower_value{vehicle!=\"\", vehicle !~ \"$vehicleBlocklist\"}) default 0) [$__range:$energySampleInterval]\n    ) / -3600000\n  )\n, \"vehicle\")",
     "legendFormat": "{{vehicle}}"
    },
    {
     "expr": "sum without(host) ((integrate((chargePower_value{vehicle=\"\", loadpoint !~ \"$loadpointBlocklist\"} default 0)[$__range:$energySampleInterval]) / -3600000))",
     "legendFormat": "Invité: {{loadpoint}}"
    },
    { "expr": "1", "legendFormat": "__panel_axis" }
   ]
  },
  {
   "title": "Power distribution",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 16, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "clamp_min(avg(gridPower_value) < $peakPowerLimit,0)",
     "legendFormat": "Import réseau"
    },
    {
     "expr": "clamp_max(avg(batteryPower_value{id=\"\"}) *(-1) > (-$peakPowerLimit),0) * (-1)",
     "legendFormat": "Décharge batterie"
    },
    {
     "expr": "avg(pvPower_value{id=\"\"}) < $peakPowerLimit",
     "legendFormat": "PV"
    },
    {
     "expr": "clamp_max(avg(gridPower_value) < $peakPowerLimit,0)",
     "legendFormat": "Injection"
    },
    {
     "expr": "clamp_min(avg(batteryPower_value{id=\"\"}) *(-1) > (-$peakPowerLimit),0) * (-1)",
     "legendFormat": "Charge batterie"
    },
    {
     "expr": "avg by (loadpoint) (chargePower_value{id=\"\"}) * (-1) > (-$peakPowerLimit)",
     "legendFormat": "{{loadpoint}}"
    },
    {
     "expr": "avg(homePower_value) * (-1) > (-$peakPowerLimit)",
     "legendFormat": "Maison"
    }
   ]
  },
  {
   "title": "Coûts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_sum(avg(tariffGrid_value) * integrate(clamp_min(avg(gridPower_value), 0)) /3600000)",
     "legendFormat": "Acheté"
    },
    {
     "expr": "range_sum(avg(tariffFeedIn_value) * integrate(clamp_max(avg(gridPower_value), 0)) /3600000)",
     "legendFormat": "Vendu"
    },
    { "expression": "$boughtTotal + $soldTotal", "type": "math" }
   ]
  }
 ]
}