{
 "title": "VM: EVCC: Maand",
 "tags": [ "EVCC" ],
 "time": { "from": "now/M", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "dbLabel", "label": "DB-label", "query": "evcc" },
   { "name": "peakPowerLimit", "label": "Piekvermogenlimiet", "query": "30000" },
   { "name": "energySampleInterval", "label": "Energie sample-interval", "query": "30s" },
   { "name": "tariffPriceInterval", "label": "Tariefinterval", "query": "15m" },
   { "name": "loadpointBlocklist", "label": "Laadpunt blokkeerlijst", "query": "^none$" },
   { "name": "extBlocklist", "label": "EXT blokkeerlijst", "query": "^none$" },
   { "name": "auxBlocklist", "label": "AUX blokkeerlijst", "query": "^none$" },
   { "name": "installedWattPeak", "label": "installedWattPeak", "query": "20" },
   { "name": "evccUrl", "label": "EVCC-URL", "query": "${VAR_EVCCURL}" },
   { "name": "inverterPortalTitle", "label": "Naam omvormerportaal", "query": "${VAR_INVERTERPORTALTITLE}" },
   { "name": "inverterPortalUrl", "label": "URL omvormerportaal", "query": "${VAR_INVERTERPORTALURL}" }
  ]
 },
 "panels": [
  { "title": "PV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Maandelijkse energietotalen",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "pvMonthlyDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "gridMonthlyDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "homeMonthlyDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "loadpointMonthlyDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "feedInMonthlyDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "Energie",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "(last_over_time(evcc_pv_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000",
     "legendFormat": "PV"
    },
    {
     "expr": "(last_over_time(evcc_grid_import_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000",
     "legendFormat": "Netafname"
    },
    {
     "expr": "(last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / -1000",
     "legendFormat": "Thuis"
    },
    {
     "expr": "sort_by_label((last_over_time(evcc_loadpoint_energy_daily_wh{db=\"$dbLabel\",loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / -1000, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    },
    {
     "expr": "(last_over_time(evcc_grid_export_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / -1000",
     "legendFormat": "Teruglevering"
    }
   ]
  },
  {
   "title": "Specifieke opbrengst",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kWh/kWp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$pvEnergy / $installedWattPeak", "type": "math" }
   ]
  },
  {
   "title": "Kengetallen",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1 - $gridEnergyIn / ($homeEnergy + $loadpointEnergy)",
     "type": "math"
    },
    {
     "expression": "($pvEnergy - $gridEnergyOut) / $pvEnergy",
     "type": "math"
    }
   ]
  },
  {
   "title": "Kengetallen",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((sum((last_over_time(evcc_grid_import_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))) / 1000)) / ((sum((last_over_time(evcc_loadpoint_energy_daily_wh{db=\"$dbLabel\",loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))) / 1000) + ((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000))",
     "legendFormat": "Zelfvoorziening"
    }
   ]
  },
  { "title": "Thuis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Thuis: energieverdeling",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$homeTotalPie - $extSum - $auxSum",
     "type": "math"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time(((last_over_time(evcc_ext_energy_daily_wh{db=\"$dbLabel\",title!=\"\",title!~\"$extBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])))[$__range:1d])) by (title) / 1000, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time(((last_over_time(evcc_aux_energy_daily_wh{db=\"$dbLabel\",title!=\"\",title!~\"$auxBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])))[$__range:1d])) by (title) / 1000, \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Thuis: energieverbruik",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expression": "$homeTotalDaily - $extTotalDaily",
     "type": "math",
     "settings": { "displayName": "Overig" }
    },
    {
     "expr": "sort_by_label((last_over_time(evcc_ext_energy_daily_wh{db=\"$dbLabel\",title!=\"\",title!~\"$extBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label((last_over_time(evcc_aux_energy_daily_wh{db=\"$dbLabel\",title!=\"\",title!~\"$auxBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000, \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Totaal: energieverdeling",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000",
     "legendFormat": "Thuis"
    },
    {
     "expr": "sort_by_label((last_over_time(evcc_loadpoint_energy_daily_wh{db=\"$dbLabel\",loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    },
    {
     "expression": "$batteryChargeTotal - $batteryDischargeTotal",
     "type": "math"
    }
   ]
  },
  {
   "title": "Totaal: energieverdeling",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expression": "$batteryChargeDaily - $batteryDischargeDaily",
     "type": "math"
    },
    {
     "expr": "(last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000",
     "legendFormat": "Thuis"
    },
    {
     "expr": "sort_by_label((last_over_time(evcc_loadpoint_energy_daily_wh{db=\"$dbLabel\",loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    }
   ]
  },
  {
   "title": "Stroombalans",
   "type": "stat",
   "gridPos": { "h": 18, "w": 5, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "averagePriceDaily", "reducer": "mean", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "$purchasedTotal / $energyPurchased * 100",
     "type": "math"
    },
    {
     "expression": "$averagePrice - $weightedAveragePrice",
     "type": "math"
    },
    {
     "expression": "$averagePrice * $energyPurchased / -100",
     "type": "math"
    },
    { "expression": "$purchasedTotal * -1", "type": "math" },
    { "expression": "$soldTotalRaw * -1", "type": "math" },
    {
     "expression": "$purchasedDisplay - $potentialPurchased",
     "type": "math"
    },
    {
     "expression": "$purchasedDisplay + $soldDisplay",
     "type": "math"
    }
   ]
  },
  {
   "title": "Dynamische elektriciteitsprijs (ct/kWh)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ct" } },
   "targets": [
    {
     "expr": "(last_over_time(evcc_grid_import_price_max_daily_ct_per_kwh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))",
     "legendFormat": "Max"
    },
    {
     "expr": "(last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))",
     "legendFormat": "Gemiddelde"
    },
    {
     "expr": "(last_over_time(evcc_grid_import_price_effective_daily_ct_per_kwh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))",
     "legendFormat": "Effectieve elektriciteitsprijs"
    },
    {
     "expr": "(last_over_time(evcc_grid_import_price_min_daily_ct_per_kwh{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Elektriciteitskosten",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "(last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))",
     "legendFormat": "Aangekocht"
    }
   ]
  },
  { "title": "Batterij", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Batterij",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "batteryChargeDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "batteryDischargeDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "$batteryDischargeTotal / $batteryChargeTotal",
     "type": "math"
    },
    { "expression": "socMaxSeries", "reducer": "mean", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "socMinSeries", "reducer": "mean", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "Batterijniveaus thuis",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(((last_over_time(evcc_battery_soc_daily_max_pct{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 100) > 0)",
     "legendFormat": "SOC max"
    },
    {
     "expr": "(((last_over_time(evcc_battery_soc_daily_min_pct{db=\"$dbLabel\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 100) > 0)",
     "legendFormat": "SOC min"
    }
   ]
  }
 ]
}