{
 "title": "VM: EVCC: Vandaag - Details",
 "tags": [ "EVCC" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "peakPowerLimit",
    "label": "Filter voor maximaal vermogen / W",
    "query": "${VAR_PEAKPOWERLIMIT}"
   },
   { "name": "loadpointBlocklist", "label": "Blokkeerlijst voor laadpunten", "query": "${VAR_LOADPOINTBLOCKLIST}" },
   { "name": "extBlocklist", "query": "${VAR_EXTBLOCKLIST}" },
   { "name": "auxBlocklist", "query": "${VAR_AUXBLOCKLIST}" },
   { "name": "loadpoint", "label": "Laadpunt", "query": { "query": "label_values(loadpoint)" } },
   { "name": "energySampleInterval", "label": "Energiemonsterinterval", "query": "${VAR_ENERGYSAMPLEINTERVAL}" },
   { "name": "tariffPriceInterval", "label": "Tariefinterval", "query": "${VAR_TARIFFPRICEINTERVAL}" }
  ]
 },
 "panels": [
  { "title": "PV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PV-energie",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "sort_by_label(range_sum(integrate(avg by (title)(pvPower_value{id!=\"\"}) < $peakPowerLimit)) / 3600000, \"title\")",
     "legendFormat": "{{title}}"
    },
    { "expr": "min(chargePower_value)", "legendFormat": "Energie" },
    {
     "expr": "range_sum(integrate(avg(pvPower_value{id=\"\"}) < $peakPowerLimit)) / 3600000",
     "legendFormat": "Totaal"
    }
   ]
  },
  {
   "title": "PV-vermogen",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sort_by_label(avg by (title)(pvPower_value{title!=\"\"}), \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Laadniveau accu",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sort_by_label(avg by (title) (last_over_time(batterySoc_value{id!=\"\", title!=\"\"})), \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "last_over_time(batterySoc_value{id=\"\"})",
     "legendFormat": "Totaal"
    }
   ]
  },
  {
   "title": "Batterijvoeding",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg by (title)(batteryPower_value{id!=\"\"})",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Voorsp",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "range_sum(integrate(avg(tariffSolar_value))) / 3600000",
     "legendFormat": "Voorsp"
    },
    {
     "expr": "range_sum(integrate(avg(pvPower_value{id=\"\"}) < $peakPowerLimit)) / 3600000",
     "legendFormat": "Werkelijk"
    },
    { "expr": "min(chargePower_value)", "legendFormat": "Energie" }
   ]
  },
  {
   "title": "Voorsp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "avg(tariffSolar_value)", "legendFormat": "Voorsp" },
    {
     "expr": "avg(pvPower_value{id=\"\"})",
     "legendFormat": "Werkelijk"
    }
   ]
  },
  { "title": "Verbruik", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Huidige vermogen",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(homePower_value) - avg(sum(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))",
     "legendFormat": "Overig"
    },
    {
     "expr": "avg(homePower_value) - avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))",
     "legendFormat": "Overig"
    },
    {
     "expr": "avg(homePower_value) - avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))  - avg(sum(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))",
     "legendFormat": "Overig"
    },
    {
     "expr": "sort_by_label(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Home: Stroom",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(homePower_value) - avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))",
     "legendFormat": "Overig"
    },
    {
     "expr": "avg(homePower_value) - avg(sum(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))",
     "legendFormat": "Overig"
    },
    {
     "expr": "avg(homePower_value) - avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"})) - avg(sum(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))",
     "legendFormat": "Overig"
    },
    {
     "expr": "sort_by_label(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Energiedistributie:",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_sum(integrate(avg(homePower_value)))/3600 - range_sum(integrate(avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))))/3600 - range_sum(integrate(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"})))/3600",
     "legendFormat": "Overig"
    },
    {
     "expr": "range_sum(integrate(avg(homePower_value)))/3600 - range_sum(integrate(avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))))/3600 ",
     "legendFormat": "Overig"
    },
    {
     "expr": "range_sum(integrate(avg(homePower_value)))/3600 - range_sum(integrate(avg(sum(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))))/3600 ",
     "legendFormat": "Overig"
    },
    {
     "expr": "sort_by_label(range_sum(integrate(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"})))/3600, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(range_sum(integrate(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"})))/3600, \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Huis: Energie",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(integrate(homePower_value offset -1h))/3600 - sum(integrate(extPower_value{title!=\"\", title !~ \"$extBlocklist\"} offset -1h))/3600 - sum(integrate(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"} offset -1h))/3600",
     "legendFormat": "Overig"
    },
    {
     "expr": "sum(integrate(homePower_value offset -1h))/3600 - sum(integrate(extPower_value{title!=\"\", title !~ \"$extBlocklist\"} offset -1h))/3600",
     "legendFormat": "Overig"
    },
    {
     "expr": "sum(integrate(homePower_value offset -1h))/3600 - sum(integrate(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"} offset -1h))/3600",
     "legendFormat": "Overig"
    },
    {
     "expr": "sort_by_label(integrate(extPower_value{title!=\"\", title !~ \"$extBlocklist\"} offset -1h)/3600, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(integrate(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}offset -1h)/3600, \"title\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Totaal: Energiedistributie",
   "type": "piechart",
   "description": "De formule voor 'Overig' moet worden aangepast afhankelijk van DE beschikbaarheid van AUX- en EXT-meters. Zie https://github.com/ha-puzzles/evcc-grafana-dashboards/tree/main/dashboards#formel-für-sonstige-anpassen voor meer informatie.",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_sum(integrate(avg(homePower_value)))/3600",
     "legendFormat": "Huis"
    },
    {
     "expr": "sort_by_label(sum by (loadpoint)(range_sum (integrate(chargePower_value{loadpoint!=\"\", loadpoint !~ \"$loadpointBlocklist\"})) / 3600), \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    }
   ]
  },
  {
   "title": "Totaal: Energie",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(integrate(homePower_value offset -1h))/3600",
     "legendFormat": "Huis"
    },
    {
     "expr": "sort_by_label(avg by(loadpoint)(integrate(chargePower_value{loadpoint!=\"\"} offset -1h))/3600, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    }
   ]
  },
  { "title": "Tarieven", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "elektriciteitstarief",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(avg(tariffGrid_value)[1d])",
     "legendFormat": "Max"
    },
    {
     "expr": "avg_over_time(avg(tariffGrid_value)[1d])",
     "legendFormat": "Gemiddelde"
    },
    {
     "expr": "min_over_time(avg(tariffGrid_value)[1d])",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "elektriciteitstarief",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 56 },
   "targets": [
    {
     "expr": "avg(tariffGrid_value offset -$tariffPriceInterval)",
     "legendFormat": "Prijs"
    },
    {
     "expr": "clamp_min(avg(gridPower_value offset -$tariffPriceInterval), 0)",
     "legendFormat": "Netafname"
    }
   ]
  },
  {
   "title": "Kosten",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_sum(avg(tariffGrid_value) * integrate(clamp_min(avg(gridPower_value), 0)) /3600000)",
     "legendFormat": "Aankoop"
    },
    {
     "expr": "range_sum(avg(tariffFeedIn_value) * integrate(clamp_max(avg(gridPower_value), 0)) /3600000)",
     "legendFormat": "Verkoop"
    },
    { "expression": "$bought + $sold", "type": "math" }
   ]
  },
  {
   "title": "Kosten",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "avg(tariffGrid_value offset -$tariffPriceInterval) * integrate(clamp_min(avg(gridPower_value offset -$tariffPriceInterval), 0)) /3600000",
     "legendFormat": "Aankoop"
    },
    {
     "expr": "avg(tariffFeedIn_value offset -$tariffPriceInterval) * integrate(clamp_max(avg(gridPower_value offset -$tariffPriceInterval), 0)) /3600000",
     "legendFormat": "Verkoop"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "g/kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(avg(tariffCo2_value)[1d])",
     "legendFormat": "Max"
    },
    {
     "expr": "avg_over_time(avg(tariffCo2_value)[1d])",
     "legendFormat": "Gemiddelde"
    },
    {
     "expr": "min_over_time(avg(tariffCo2_value)[1d])",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 74 },
   "targets": [
    {
     "expr": "tariffCo2_value offset -$tariffPriceInterval",
     "legendFormat": "CO2"
    },
    { "expr": "clamp_min(gridPower_value, 0)", "legendFormat": "Netafname" }
   ]
  },
  { "title": "Net", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Stromen/fase",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(avg(gridCurrents_l1))",
     "legendFormat": "Stroom L1"
    },
    {
     "expr": "last_over_time(avg(gridCurrents_l2))",
     "legendFormat": "Stroom L2"
    },
    {
     "expr": "last_over_time(avg(gridCurrents_l3))",
     "legendFormat": "Stroom L3"
    }
   ]
  },
  {
   "title": "Stromen/fase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "avg(gridCurrents_l1)", "legendFormat": "Stroom L1" },
    { "expr": "avg(gridCurrents_l2)", "legendFormat": "Stroom L2" },
    { "expr": "avg(gridCurrents_l3)", "legendFormat": "Stroom L3" }
   ]
  },
  {
   "title": "Stroom Fases",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(avg(gridPowers_l1))",
     "legendFormat": "Vermogen L1"
    },
    {
     "expr": "last_over_time(avg(gridPowers_l2))",
     "legendFormat": "Vermogen L2"
    },
    {
     "expr": "last_over_time(avg(gridPowers_l3))",
     "legendFormat": "Vermogen L3"
    }
   ]
  },
  {
   "title": "Stroom Fases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "avg(gridPowers_l1)", "legendFormat": "Vermogen L1" },
    { "expr": "avg(gridPowers_l2)", "legendFormat": "Vermogen L2" },
    { "expr": "avg(gridPowers_l3)", "legendFormat": "Vermogen L3" }
   ]
  },
  { "title": "Laadpunt $loadpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }, "repeat": "loadpoint" },
  {
   "title": "Laadstromen/fase: $loadpoint",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(avg(chargeCurrents_l1{loadpoint=\"$loadpoint\"}))",
     "legendFormat": "Stroom L1"
    },
    {
     "expr": "last_over_time(avg(chargeCurrents_l2{loadpoint=\"$loadpoint\"}))",
     "legendFormat": "Stroom L2"
    },
    {
     "expr": "last_over_time(avg(chargeCurrents_l2{loadpoint=\"$loadpoint\"}))",
     "legendFormat": "Stroom L3"
    }
   ]
  },
  {
   "title": "Laadstromen/fase: $loadpoint",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "avg(chargeCurrents_l1 {loadpoint=\"$loadpoint\"})",
     "legendFormat": "Stroom L1"
    },
    {
     "expr": "avg(chargeCurrents_l2 {loadpoint=\"$loadpoint\"})",
     "legendFormat": "Stroom L2"
    },
    {
     "expr": "avg(chargeCurrents_l3 {loadpoint=\"$loadpoint\"})",
     "legendFormat": "Stroom L3"
    }
   ]
  },
  {
   "title": "Fasen: $loadpoint",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 112 },
   "targets": [
    {
     "expr": "avg(phasesActive_value{loadpoint=\"$loadpoint\"}) < 2",
     "legendFormat": "1 fase"
    },
    {
     "expr": "avg(phasesActive_value{loadpoint=\"$loadpoint\"}) > 2",
     "legendFormat": "3 fasen"
    }
   ]
  },
  {
   "title": "Laadvermogen: $loadpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(chargePower_value {loadpoint=\"$loadpoint\"})",
     "legendFormat": "Laadvermogen"
    }
   ]
  }
 ]
}