{
 "title": "VM: EVCC: Hele periode",
 "tags": [ "EVCC" ],
 "time": { "from": "now-2y/y", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "dbLabel", "label": "DB-label", "query": "evcc" },
   { "name": "peakPowerLimit", "label": "Piekvermogenlimiet", "query": "30000" },
   { "name": "energySampleInterval", "label": "Energie sample-interval", "query": "30s" },
   { "name": "tariffPriceInterval", "label": "Tariefinterval", "query": "15m" },
   { "name": "loadpointBlocklist", "label": "Laadpunt blokkeerlijst", "query": "^none$" },
   { "name": "extBlocklist", "label": "EXT blokkeerlijst", "query": "^none$" },
   { "name": "auxBlocklist", "label": "AUX blokkeerlijst", "query": "^none$" },
   { "name": "installedWattPeak", "label": "installedWattPeak", "query": "20" },
   { "name": "vehicleBlocklist", "label": "Voertuig blokkeerlijst", "query": "^Altherma-3$" },
   {
    "name": "vehicle",
    "label": "Voertuig",
    "query": {
     "query": "label_values(sessionPricePerKWh_value{db=\"$dbLabel\",vehicle!=\"\",vehicle!~\"$vehicleBlocklist\"}, vehicle)"
    }
   },
   {
    "name": "vVerbrauch",
    "label": "Verbrandingsmotor verbruik l/100km",
    "query": "6"
   },
   { "name": "spritKosten", "label": "Brandstofprijs/l", "query": "1.75" },
   { "name": "purchasePricePv", "label": "PV-aankoopprijs", "query": "24884" },
   { "name": "batteryPurchasePrice", "label": "Batterij aankoopprijs", "query": "5500" },
   { "name": "runningCosts", "label": "Lopende kosten", "query": "100" },
   { "name": "speicherkapazitaet", "label": "Batterijcapaciteit / Wh", "query": "9500" },
   { "name": "evccUrl", "label": "EVCC-URL", "query": "${VAR_EVCCURL}" },
   { "name": "inverterPortalTitle", "label": "Naam omvormerportaal", "query": "${VAR_INVERTERPORTALTITLE}" },
   { "name": "inverterPortalUrl", "label": "URL omvormerportaal", "query": "${VAR_INVERTERPORTALURL}" }
  ]
 },
 "panels": [
  { "title": "Energie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Energietotalen",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Netafname"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "PV"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Thuis"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{db=\"$dbLabel\",loadpoint!~\"$loadpointBlocklist\"}[1d]))[$__range:1d])) by (loadpoint) / 1000, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Teruglevering"
    }
   ]
  },
  {
   "title": "Jaarlijkse opbrengst",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Maandelijkse opbrengst/jaar",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "Kengetallen",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1 - $gridEnergyIn / ($homeEnergy + $loadpointEnergy)",
     "type": "math"
    },
    {
     "expression": "($pvEnergy - $gridEnergyOut) / $pvEnergy",
     "type": "math"
    }
   ]
  },
  {
   "title": "Jaarlijks thuisverbruik",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Maandelijks thuisverbruik/jaar",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "Jaarlijkse netafname",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Maandelijkse netafname/jaar",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "Batterij",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "batteryChargeTotal"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "batteryDischargeTotal"
    },
    {
     "expression": "$batteryDischargeTotal / $batteryChargeTotal",
     "type": "math"
    },
    {
     "expr": "sum(avg_over_time((last_over_time(evcc_battery_soc_daily_max_pct{db=\"$dbLabel\"}[1d]))[$__range:1d])) / count(avg_over_time((last_over_time(evcc_battery_soc_daily_max_pct{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "maxSoc"
    },
    {
     "expr": "sum(avg_over_time((last_over_time(evcc_battery_soc_daily_min_pct{db=\"$dbLabel\"}[1d]))[$__range:1d])) / count(avg_over_time((last_over_time(evcc_battery_soc_daily_min_pct{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "minSoc"
    }
   ]
  },
  {
   "title": "Jaarlijkse teruglevering",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Maandelijkse teruglevering/jaar",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "Dagen met hoogste opbrengst",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "max without(local_year,local_month)(evcc_pv_energy_daily_wh{db=\"$dbLabel\"}) / 1000",
     "legendFormat": "PV-energie"
    }
   ]
  },
  {
   "title": "Hoogste teruglevering",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "max without(local_year,local_month)(evcc_grid_export_daily_wh{db=\"$dbLabel\"}) / 1000",
     "legendFormat": "Teruglevering"
    }
   ]
  },
  {
   "title": "Hoogste thuisverbruik",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "max without(local_year,local_month)(evcc_home_energy_daily_wh{db=\"$dbLabel\"}) / 1000",
     "legendFormat": "Thuisverbruik"
    }
   ]
  },
  { "title": "Installatiegezondheid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Gemiddelde top 30 dagen/jaar",
   "type": "barchart",
   "description": "Gebruikt het gemiddelde rendement van de beste 30 dagen per jaar. Dit kan helpen mogelijke degradatie te herkennen, maar moet in context worden geïnterpreteerd. Afzonderlijke jaren zijn op zichzelf niet doorslaggevend.",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "last_over_time(evcc_pv_top30_mean_yearly_wh{db=\"$dbLabel\"}[$__range])",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Gemiddelde top 5 dagen/maand",
   "type": "barchart",
   "description": "Gebruikt het gemiddelde rendement van de beste 5 dagen per maand. Dit kan helpen mogelijke degradatie te herkennen, maar moet in context worden geïnterpreteerd. Afzonderlijke maanden zijn op zichzelf niet doorslaggevend.",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "last_over_time(evcc_pv_top5_mean_monthly_wh{db=\"$dbLabel\"}[$__range])",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  { "title": "Financiën", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Maandelijkse kosten",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "label_join(label_set(clamp_min((sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month) - sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)), 0), \"kind\", \"Costs\"), \"series\", \" \", \"local_year\", \"kind\") or (label_join(label_set(clamp_min((sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month) - sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)), 0), \"kind\", \"Income\"), \"series\", \" \", \"local_year\", \"kind\") and on (local_year) (sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year) > 0))"
    }
   ]
  },
  { "title": "Balans", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Stroombalans",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / sum(count_over_time((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "averagePrice"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) * -1",
     "legendFormat": "Ingekocht"
    },
    {
     "expression": "($purchased * -100) / ($energyPurchased / 1000)",
     "type": "math"
    },
    {
     "expression": "$averagePrice - $weightedAveragePrice",
     "type": "math"
    },
    {
     "expression": "$averagePrice * ($energyPurchased / 1000) / -100",
     "type": "math"
    },
    {
     "expression": "$purchased - $potentialPurchased",
     "type": "math"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "Verkocht"
    },
    { "expression": "$purchased + $sold", "type": "math" }
   ]
  },
  {
   "title": "PV-installatie afschrijving",
   "type": "stat",
   "description": "Bij minder dan 365 dagen gegevens worden waarden geëxtrapoleerd naar een volledig jaar, met een overeenkomstige onnauwkeurigheid afhankelijk van de gemeten periode.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$potentialHomePrice + $potentialLoadpointPrice",
     "type": "math"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "energyPurchasedPrice"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "energySoldPrice"
    },
    {
     "expression": "$energyPurchasedPrice - $energySoldPrice",
     "type": "math"
    },
    {
     "expression": "$potentialTotalPrice - $energyTotalPrice",
     "type": "math"
    },
    {
     "expr": "sum(count_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "numberOfMeasuredDays"
    },
    {
     "expression": "$refluxOfCapital * 365 / $numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$purchasePricePv / ($refluxOfCapitalYearly - $runningCosts)",
     "type": "math"
    },
    {
     "expression": "($refluxOfCapitalYearly - $runningCosts) / $purchasePricePv",
     "type": "math"
    }
   ]
  },
  {
   "title": "Batterij afschrijving",
   "type": "stat",
   "description": "Bij minder dan 365 dagen gegevens worden waarden geëxtrapoleerd naar een volledig jaar, met een overeenkomstige onnauwkeurigheid afhankelijk van de gemeten periode.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "chargedEnergy"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "dischargedEnergy"
    },
    {
     "expression": "1 - ($dischargedEnergy / $chargedEnergy)",
     "type": "math"
    },
    {
     "expr": "sum(count_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "numberOfMeasuredDays"
    },
    {
     "expression": "($chargedEnergy / $speicherkapazitaet) * 365 / $numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "($batteryDischargeCost - $batteryChargeFeedInCost) * 365 / $numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$batteryPurchasePrice / $batteryPayback",
     "type": "math"
    },
    {
     "expression": "$batteryPayback / $batteryPurchasePrice",
     "type": "math"
    }
   ]
  },
  { "title": "Voertuigen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Rijkosten $vehicle",
   "type": "stat",
   "description": "Waarden zijn grove schattingen op basis van gemiddelden. Externe laadsessies zijn niet inbegrepen.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 93 },
   "repeat": "vehicle",
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_vehicle_distance_daily_km{db=\"$dbLabel\",vehicle=\"$vehicle\"}[1d]))[$__range:1d]))",
     "legendFormat": "drivenKm"
    },
    {
     "expression": "$chargedEnergy / ($drivenKm / 100)",
     "type": "math"
    },
    {
     "expr": "avg(avg_over_time(sessionSolarPercentage_value{db=\"$dbLabel\",vehicle=\"$vehicle\"}[$__range]))",
     "legendFormat": "solarPercent"
    },
    {
     "expr": "avg(avg_over_time(sessionPricePerKWh_value{db=\"$dbLabel\",vehicle=\"$vehicle\"}[$__range]))",
     "legendFormat": "chargePrice"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_potential_vehicle_charge_cost_daily_eur{db=\"$dbLabel\",vehicle=\"$vehicle\"}[1d]))[$__range:1d]))",
     "legendFormat": "electricDriveCostNoPV"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_vehicle_charge_cost_daily_eur{db=\"$dbLabel\",vehicle=\"$vehicle\"}[1d]))[$__range:1d]))",
     "legendFormat": "electricDriveCost"
    },
    {
     "expression": "$electricDriveCostNoPV - $electricDriveCost",
     "type": "math"
    },
    {
     "expression": "$drivenKm / 100 * $vVerbrauch * $spritKosten",
     "type": "math"
    },
    {
     "expression": "$iceDriveCost - $electricDriveCost",
     "type": "math"
    }
   ]
  }
 ]
}