{
 "title": "EVCC: 年份",
 "tags": [ "PV" ],
 "time": { "from": "now/y", "to": "now/y" },
 "templating": {
  "list": [
   { "name": "timezone", "label": "时区", "query": "${VAR_TIMEZONE}" },
   { "name": "loadpointBlocklist", "label": "加载点的阻止列表", "query": "${VAR_LOADPOINTBLOCKLIST}" },
   { "name": "vehicleBlocklist", "label": "车辆黑名单", "query": "${VAR_VEHICLEBLOCKLIST}" }
  ]
 },
 "panels": [
  { "title": "光伏发电", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "gridPos": { "h": 12, "w": 5, "x": 0, "y": 1 } },
  {
   "title": "活力",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value as \"pv\" FROM \"pvMonthlyEnergy\" WHERE $timeFilter TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Netzbezug",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value as \"grid\" FROM \"gridMonthlyEnergy\" WHERE $timeFilter  TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Haus",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value * (-1)  as home FROM \"homeMonthlyEnergy\" WHERE $timeFilter   TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_loadpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value * (-1)  FROM \"loadpointMonthlyEnergy\" WHERE $timeFilter AND \"loadpoint\"::tag !~ $loadpointBlocklist GROUP BY (\"loadpoint\"::tag)  TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Einspeisung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value * (-1) as feedin FROM \"feedInMonthlyEnergy\" WHERE $timeFilter  TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "gridPos": { "h": 7, "w": 5, "x": 0, "y": 13 } },
  {
   "title": "指标",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "1-$zugekaufteEnergie/($energieLadepunkte+$energieHaus)",
     "type": "math"
    },
    {
     "expression": "($energiePV - $eingespeisteEnergie)/$energiePV",
     "type": "math"
    }
   ]
  },
  {
   "title": "每日平均能量",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PV/Tag",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT value FROM \"pvDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "expression": "$hausEnergie+$loadpointsEnergie",
     "type": "math"
    },
    {
     "alias": "Netzbezug/Tag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"gridDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "能量/天",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "光伏发电",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT \"value\" FROM \"pvDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "expression": "$hausEnergie+$loadpointsEnergie",
     "type": "math"
    },
    {
     "alias": "Netzbezug",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"gridDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "家", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "主页：能源分配",
   "type": "piechart",
   "description": "“其他”的公式必须根据 AUX 和 EXT 仪表的可用性进行调整。有关详细信息，请参阅 https://github.com/ha-puzzles/evcc-grafana-dashboards/tree/main/dashboards#formel-für-sonstige-anpassen。",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expression": "$homeTotal - $extEnergiesSum", "type": "math" },
    {
     "alias": "$tag_title",
     "query": "SELECT value FROM extMonthlyEnergy WHERE $timeFilter AND \"title\"::tag !~ $loadpointBlocklist GROUP BY (\"title\"::tag) tz('$timezone')"
    },
    {
     "alias": "$tag_title",
     "query": "SELECT value FROM auxMonthlyEnergy WHERE $timeFilter AND \"title\"::tag !~ $loadpointBlocklist GROUP BY (\"title\"::tag) tz('$timezone')"
    }
   ]
  },
  {
   "title": "主页：能源消耗",
   "type": "barchart",
   "description": "“其他”的公式必须根据 AUX 和 EXT 仪表的可用性进行调整。有关详细信息，请参阅 https://github.com/ha-puzzles/evcc-grafana-dashboards/tree/main/dashboards#formel-für-sonstige-anpassen。",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expression": "$homeTotal - $extEnergiesSum", "type": "math" },
    {
     "alias": "$tag_title",
     "query": "SELECT value FROM extMonthlyEnergy WHERE $timeFilter AND \"title\"::tag !~ $loadpointBlocklist GROUP BY (\"title\"::tag) tz('$timezone')"
    },
    {
     "alias": "$tag_title",
     "query": "SELECT value FROM auxMonthlyEnergy WHERE $timeFilter AND \"title\"::tag !~ $loadpointBlocklist GROUP BY (\"title\"::tag) tz('$timezone')"
    }
   ]
  },
  {
   "title": "总计：能源分配",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Haus",
     "query": "SELECT value FROM homeMonthlyEnergy WHERE $timeFilter  tz('$timezone')"
    },
    {
     "alias": "$tag_loadpoint",
     "query": "SELECT value FROM loadpointMonthlyEnergy WHERE $timeFilter AND \"loadpoint\"::tag !~ $loadpointBlocklist GROUP BY (\"loadpoint\"::tag) tz('$timezone')"
    },
    {
     "expression": "$chargeEnergy - $dischargeEnergy",
     "type": "math"
    }
   ]
  },
  {
   "title": "主页：能源分配",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expression": "$chargeEnergy-$dischargeEnergy", "type": "math" },
    {
     "alias": "Haus",
     "query": "SELECT value FROM homeMonthlyEnergy WHERE $timeFilter  tz('$timezone')"
    },
    {
     "alias": "$tag_loadpoint",
     "query": "SELECT value FROM loadpointMonthlyEnergy WHERE $timeFilter AND \"loadpoint\"::tag !~ $loadpointBlocklist GROUP BY (\"loadpoint\"::tag) tz('$timezone')"
    }
   ]
  },
  { "gridPos": { "h": 18, "w": 5, "x": 0, "y": 48 } },
  { "gridPos": { "h": 11, "w": 19, "x": 5, "y": 48 } },
  {
   "title": "电费",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "alias": "Einkauf",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvPower",
     "query": "SELECT value FROM energyPurchasedMonthlyPrice WHERE $timeFilter  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Verkauf",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvPower",
     "query": "SELECT value FROM energySoldMonthlyPrice WHERE $timeFilter  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  { "title": "电池", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  { "gridPos": { "h": 18, "w": 5, "x": 0, "y": 67 } },
  {
   "title": "电池：最大值",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 67 },
   "targets": [
    {
     "alias": "Maximaler Batterie SOC/Tag",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT \"value\" FROM \"batteryMaxSoc\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "电池充电",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Speicher laden",
     "query": "SELECT \"value\" from chargeMonthlyEnergy WHERE $timeFilter tz('$timezone')"
    },
    {
     "alias": "Speicher entladen",
     "query": "SELECT \"value\" from dischargeMonthlyEnergy WHERE $timeFilter tz('$timezone')"
    }
   ]
  },
  {
   "title": "电池：最小值",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 76 },
   "targets": [
    {
     "alias": "Minimaler Batterie SOC/Tag",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT \"value\" FROM \"batteryMinSoc\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "电池效率",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expression": "$entladen/$laden", "type": "math" }
   ]
  },
  { "title": "车辆", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "车辆",
   "type": "stat",
   "description": "消费需要几个月的时间才能变得有意义。外部充电被忽略并扭曲结果。",
   "gridPos": { "h": 16, "w": 5, "x": 0, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Kilometerstand: $tag_vehicle",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vehicle1Odometer",
     "query": "SELECT \"value\" FROM \"vehicleOdometerDailyMax\" WHERE $timeFilter AND value > 0 AND \"vehicle\"::tag !~ $vehicleBlocklist GROUP BY \"vehicle\"::tag tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    },
    {
     "alias": "Gefahren: $tag_vehicle",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vehicle1Odometer",
     "query": "SELECT spread(\"value\") FROM \"vehicleOdometerDailyMax\" WHERE $timeFilter AND value > 0 AND \"vehicle\"::tag !~ $vehicleBlocklist GROUP BY \"vehicle\"::tag tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    },
    {
     "alias": "Energie: $tag_vehicle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")/1000 FROM \"vehicleMonthlyEnergy\" WHERE $timeFilter  AND value > 0 AND \"vehicle\"::tag !~ $vehicleBlocklist GROUP BY \"vehicle\" tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "$vehicleChargedEnergy/($vehicleDrivenKm/100)",
     "type": "math"
    }
   ]
  },
  {
   "title": "每月行驶公里数",
   "type": "barchart",
   "description": "仅当车辆插入电源时才会捕获公里数。如果很少插入电源，公里数可能会丢失。",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "targets": [
    {
     "alias": "Gefahren: $tag_vehicle",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vehicle1Odometer",
     "query": "SELECT \"value\" FROM \"vehicleMonthlyDrivenKm\" WHERE $timeFilter AND value > 0 AND \"vehicle\"::tag !~ $vehicleBlocklist GROUP BY \"vehicle\"::tag  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "每月充电电量",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Energie: $tag_vehicle",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vehicle1Odometer",
     "query": "SELECT \"value\" FROM \"vehicleMonthlyEnergy\" WHERE $timeFilter AND value>0 AND \"vehicle\"::tag !~ $vehicleBlocklist GROUP BY \"vehicle\"::tag  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "消耗量（千瓦时/100公里）",
   "type": "barchart",
   "description": "数值为近似值。不包括外部充电，捕获的公里数取决于车辆充电的频率。",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 102 },
   "targets": [
    {
     "expression": "($vehiclesEnergy/1000)/($vehiclesKm/100)",
     "type": "math"
    }
   ]
  }
 ]
}