{
 "title": "EVCC: 所有时间",
 "tags": [ "PV" ],
 "time": { "from": "2023-02-28T23:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   { "name": "purchasePricePv", "label": "光伏总投资成本", "query": "24884" },
   { "name": "batteryPurchasePrice", "label": "电池投资成本", "query": "5500" },
   { "name": "runningCosts", "label": "持续成本", "query": "100" },
   { "name": "vVerbrauch", "label": "ICE 消耗 l/100km", "query": "6" },
   { "name": "spritKosten", "label": "燃油价格/升", "query": "1.75" },
   { "name": "timezone", "query": "Europe/Berlin" },
   { "name": "speicherkapazitaet", "label": "家用电池容量/Wh", "query": "${VAR_SPEICHERKAPAZITAET}" },
   {
    "name": "vehicle",
    "label": "车辆",
    "query": {
     "query": "show tag values from vehicleMonthlyEnergy with key = \"vehicle\" where \"vehicle\" !~ $vehicleBlocklist"
    }
   },
   { "name": "vehicleBlocklist", "label": "车辆黑名单", "query": "${VAR_VEHICLEBLOCKLIST}" },
   { "name": "loadpointBlocklist", "label": "加载点的阻止列表", "query": "${VAR_LOADPOINTBLOCKLIST}" }
  ]
 },
 "panels": [
  { "title": "活力", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "gridPos": { "h": 11, "w": 3, "x": 0, "y": 1 } },
  {
   "title": "年产量",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "year::tag" ], "type": "tag" }
     ],
     "measurement": "pvMonthlyEnergy",
     "query": "SELECT value, year FROM \"pvMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "月收益率/年",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_month]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT year, month, value FROM \"pvMonthlyEnergy\" tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "gridPos": { "h": 12, "w": 3, "x": 0, "y": 12 } },
  {
   "title": "年家庭消费",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "year::tag" ], "type": "tag" }
     ],
     "measurement": "pvMonthlyEnergy",
     "query": "SELECT value, year FROM \"homeMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "每月家庭消费/年",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT year, month, value FROM \"homeMonthlyEnergy\"  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "每年网格导入",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "year::tag" ], "type": "tag" }
     ],
     "measurement": "pvMonthlyEnergy",
     "query": "SELECT value, year FROM \"gridMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "每月网格导入/年",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT year, month, value FROM \"gridMonthlyEnergy\"  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 } },
  {
   "title": "每年馈电",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "year::tag" ], "type": "tag" }
     ],
     "measurement": "pvMonthlyEnergy",
     "query": "SELECT value, year FROM \"feedInMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "每月馈电/年",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT year, month, value FROM \"feedInMonthlyEnergy\"  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "产量最高的日子",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "PV Energie",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvPower",
     "query": "SELECT value FROM \"pvDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value::field", "operator": "<", "value": "10000" }
     ]
    }
   ]
  },
  {
   "title": "最高馈电",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Einspeisung",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gridPower",
     "query": "SELECT value FROM \"feedInDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / -3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value::field", "operator": "<", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "最高家庭消费",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Hausverbrauch",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "homePower",
     "query": "SELECT value FROM \"homeDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value::field", "operator": "<", "value": "10000" }
     ]
    }
   ]
  },
  { "title": "金融", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "每月费用",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "SELECT value FROM energyPurchasedMonthlyPrice WHERE $timeFilter  tz('$timezone')"
    },
    {
     "query": "SELECT value FROM energySoldMonthlyPrice WHERE $timeFilter  tz('$timezone')"
    },
    {
     "expression": "(abs($purchased + $sold) + ($purchased + $sold)) /2",
     "type": "math"
    },
    {
     "expression": "-(abs($purchased + $sold)- ($purchased + $sold)) /2",
     "type": "math"
    }
   ]
  },
  { "gridPos": { "h": 9, "w": 8, "x": 0, "y": 55 } },
  {
   "title": "光伏系统摊销",
   "type": "stat",
   "description": "对于少于 365 天的数据，值会外推至全年，并根据捕获的时间段产生相应的误差。",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$potentialHomePrice + $potentialLoadpointPrice",
     "type": "math"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyPurchasedDailyPrice",
     "query": "SELECT sum(\"value\") FROM \"energyPurchasedDailyPrice\" WHERE $timeFilter TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyPurchasedDailyPrice",
     "query": "SELECT sum(\"value\") * (-1) FROM \"energySoldDailyPrice\" WHERE $timeFilter TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "$energyPurchasedPrice - $energySoldPrice",
     "type": "math"
    },
    {
     "expression": "$potentialTotalPrice - $energyTotalPrice",
     "type": "math"
    },
    { "expression": "dailyMeasurement", "reducer": "count", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "$refluxOfCapital*365/$numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$purchasePricePv / ($refluxOfCapitalYearly - $runningCosts)",
     "type": "math"
    },
    {
     "expression": "($refluxOfCapitalYearly - $runningCosts) / $purchasePricePv",
     "type": "math"
    }
   ]
  },
  {
   "title": "电池摊销",
   "type": "stat",
   "description": "对于少于 365 天的数据，值会外推至全年，并根据捕获的时间段产生相应的误差。",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") from chargeDailyEnergy WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") from dischargeDailyEnergy WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "1-($dischargedEnergy/$chargedEnergy)",
     "type": "math"
    },
    {
     "expression": "($chargedEnergy/$speicherkapazitaet) * 365/$numberOfMeasuredDays",
     "type": "math"
    },
    { "expression": "dailyMeasurement", "reducer": "count", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "($batteryDischargeCost - $batteryChargeFeedInCost) * 365/$numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$batteryPurchasePrice/$batteryPayback",
     "type": "math"
    },
    {
     "expression": "$batteryPayback/$batteryPurchasePrice",
     "type": "math"
    }
   ]
  },
  {
   "title": "出行费用 $车辆",
   "type": "stat",
   "description": "数值是基于平均值的粗略估计。\n\n假设：车辆主要在家里充电。不包括外部充电。",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "repeat": "vehicle",
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "drivenKm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT spread(\"value\") FROM \"vehicleOdometerDailyMax\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expression": "$chargedEnergy/($drivenKm/100)", "type": "math" },
    {
     "alias": "Solaranteil",
     "measurement": "sessionSolarPercentage",
     "query": "SELECT mean(\"value\") FROM \"sessionSolarPercentage\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Effektiver, durchschnittlicher Preis",
     "measurement": "sessionPricePerKWh",
     "query": "SELECT mean(\"value\") FROM \"sessionPricePerKWh\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"potentialVehicleChargeDailyPrice\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"vehicleChargeDailyPrice\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "$electricDriveCostNoPV - $electricDriveCost",
     "type": "math"
    },
    {
     "expression": "$drivenKm / 100 * $vVerbrauch * $spritKosten",
     "type": "math"
    },
    {
     "expression": "$iceDriveCost - $electricDriveCost",
     "type": "math"
    }
   ]
  },
  { "title": "系统健康状况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "每年平均前 30 天",
   "type": "barchart",
   "description": "使用每年最好的 30 天的平均产量。可以帮助检测潜在的退化，但必须进行整体解释。单身年份并无定论。",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(value, 30) FROM (\n        SELECT * FROM \"pvDailyEnergy\"  TZ('$timezone')\n) GROUP BY year TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "每月平均前 5 天",
   "type": "barchart",
   "description": "使用每月最佳 5 天的平均产量。可以帮助检测潜在的退化，但必须进行整体解释。单月并不能得出结论。",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(top) FROM (\n    SELECT top(value, 5) FROM (\n        SELECT year, month, value FROM \"pvDailyEnergy\"  TZ('$timezone')\n    ) GROUP BY month, year TZ('$timezone')\n) GROUP BY month, year TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}