{
 "title": "VM: EVCC: 月",
 "tags": [ "EVCC" ],
 "time": { "from": "now/M", "to": "now/M" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "dashboardBuild", "label": "Build", "query": "info" },
   { "name": "loadpointBlocklist", "label": "充电点屏蔽列表", "query": "^none$" },
   {
    "name": "heatPumpLoadpointRegex",
    "label": "热泵负载点匹配",
    "query": "(?i).*(daikin-wp|wp|warmepumpe|wärmepumpe|heat pump).*"
   },
   { "name": "extBlocklist", "label": "EXT 屏蔽列表", "query": "^none$" },
   { "name": "auxBlocklist", "label": "AUX 屏蔽列表", "query": "^none$" },
   { "name": "installedWattPeak", "label": "installedWattPeak", "query": "20" },
   { "name": "evccUrl", "label": "EVCC 网址", "query": "${VAR_EVCCURL}" },
   { "name": "inverterPortalTitle", "label": "逆变器门户名称", "query": "${VAR_INVERTERPORTALTITLE}" },
   { "name": "inverterPortalUrl", "label": "逆变器门户网址", "query": "${VAR_INVERTERPORTALURL}" }
  ]
 },
 "panels": [
  { "title": "光伏发电", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "每月能源总计",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "pvMonthlyDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "gridMonthlyDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "homeMonthlyDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "loadpointMonthlyDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "feedInMonthlyDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "能源",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "(last_over_time(evcc_pv_energy_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000",
     "legendFormat": "光伏发电"
    },
    {
     "expr": "(last_over_time(evcc_grid_import_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000",
     "legendFormat": "电网输入"
    },
    {
     "expr": "(last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / -1000",
     "legendFormat": "家庭"
    },
    {
     "expr": "sort_by_label((last_over_time(evcc_loadpoint_energy_daily_wh{loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / -1000, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    },
    {
     "expr": "(last_over_time(evcc_grid_export_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / -1000",
     "legendFormat": "馈电"
    }
   ]
  },
  {
   "title": "单位收益",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kWh/kWp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$pvEnergy / $installedWattPeak", "type": "math" }
   ]
  },
  {
   "title": "指标仪表",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1 - $gridEnergyIn / ($homeEnergy + $loadpointEnergy)",
     "type": "math"
    },
    {
     "expression": "($pvEnergy - $gridEnergyOut) / $pvEnergy",
     "type": "math"
    }
   ]
  },
  {
   "title": "指标",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((sum((last_over_time(evcc_grid_import_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))) / 1000)) / ((sum((last_over_time(evcc_loadpoint_energy_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))) / 1000) + ((last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000))",
     "legendFormat": "自给率"
    }
   ]
  },
  { "title": "家庭", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "家庭：能源分配",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$homeTotalPie - $extSum - $auxSum",
     "type": "math"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time(((last_over_time(evcc_ext_energy_daily_wh{title!=\"\",title!~\"$extBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])))[$__range:1d])) by (title) / 1000, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time(((last_over_time(evcc_aux_energy_daily_wh{title!=\"\",title!~\"$auxBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])))[$__range:1d])) by (title) / 1000, \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "家庭：能源消耗",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expression": "$homeTotalDaily - $extTotalDaily",
     "type": "math",
     "settings": { "displayName": "其他" }
    },
    {
     "expr": "sort_by_label((last_over_time(evcc_ext_energy_daily_wh{title!=\"\",title!~\"$extBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label((last_over_time(evcc_aux_energy_daily_wh{title!=\"\",title!~\"$auxBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000, \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "总计：能源分配",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000",
     "legendFormat": "家庭"
    },
    {
     "expr": "sort_by_label((last_over_time(evcc_loadpoint_energy_daily_wh{loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    },
    {
     "expression": "$batteryChargeTotal - $batteryDischargeTotal",
     "type": "math"
    }
   ]
  },
  {
   "title": "总计：能源分配",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "WITH (\n  batteryNet = ((last_over_time(evcc_battery_charge_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) - (last_over_time(evcc_battery_discharge_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))) / 1000,\n  batteryCharge = label_set((batteryNet > 0), \"series\", \"Battery charge\"),\n  batteryDischarge = label_set((batteryNet < 0), \"series\", \"Battery discharge\"),\n  home = label_set((last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000, \"series\", \"Home\"),\n  loadpoints = label_copy((last_over_time(evcc_loadpoint_energy_daily_wh{loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000, \"loadpoint\", \"series\")\n)\nhome or sort_by_label(loadpoints, \"series\") or batteryCharge or batteryDischarge",
     "legendFormat": "{{series}}"
    }
   ]
  },
  {
   "title": "功率平衡",
   "type": "stat",
   "gridPos": { "h": 18, "w": 5, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "averagePriceDaily", "reducer": "mean", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "$purchasedTotal / $energyPurchased * 100",
     "type": "math"
    },
    {
     "expression": "$averagePrice - $weightedAveragePrice",
     "type": "math"
    },
    {
     "expression": "$averagePrice * $energyPurchased / -100",
     "type": "math"
    },
    { "expression": "$purchasedTotal * -1", "type": "math" },
    { "expression": "$soldTotalRaw * -1", "type": "math" },
    {
     "expression": "$purchasedDisplay - $potentialPurchased",
     "type": "math"
    },
    {
     "expression": "$purchasedDisplay + $soldDisplay",
     "type": "math"
    }
   ]
  },
  {
   "title": "动态电价 (ct/kWh)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ct" } },
   "targets": [
    {
     "expr": "(last_over_time(evcc_grid_import_price_max_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))",
     "legendFormat": "Max"
    },
    {
     "expr": "(last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))",
     "legendFormat": "平均值"
    },
    {
     "expr": "(last_over_time(evcc_grid_import_price_effective_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))",
     "legendFormat": "实际电价"
    },
    {
     "expr": "(last_over_time(evcc_grid_import_price_min_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "电力成本",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "(last_over_time(evcc_grid_import_cost_daily_eur{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))",
     "legendFormat": "购入"
    }
   ]
  },
  { "title": "电池", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "电池摘要",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "batteryChargeDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "batteryDischargeDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "$batteryDischargeTotal / $batteryChargeTotal",
     "type": "math"
    },
    { "expression": "socMaxSeries", "reducer": "mean", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "socMinSeries", "reducer": "mean", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "家庭电池水平",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(((last_over_time(evcc_battery_soc_daily_max_pct{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 100) > 0)",
     "legendFormat": "SOC 最高"
    },
    {
     "expr": "(((last_over_time(evcc_battery_soc_daily_min_pct{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 100) > 0)",
     "legendFormat": "SOC 最低"
    }
   ]
  },
  { "title": "用能设备", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "热泵总量",
   "type": "stat",
   "description": "匹配负载点上的年度热泵能耗。",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($hpPvWh + $hpBatteryWh + $hpGridWh) / 1000",
     "type": "math"
    }
   ]
  },
  {
   "title": "热泵来源占比",
   "type": "bargauge",
   "description": "热泵负载点的光伏、电池放电和电网供电估算占比。",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$hpPvKwh / $hpTotalKwh", "type": "math" },
    { "expression": "$hpBatteryKwh / $hpTotalKwh", "type": "math" },
    { "expression": "$hpGridKwh / $hpTotalKwh", "type": "math" }
   ]
  },
  {
   "title": "充电桩总量",
   "type": "stat",
   "description": "可见充电负载点的年度充电能耗，不含热泵负载点。",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($lpPvWh + $lpBatteryWh + $lpGridWh) / 1000",
     "type": "math"
    }
   ]
  },
  {
   "title": "充电桩来源占比",
   "type": "bargauge",
   "description": "可见充电负载点的光伏、电池放电和电网供电估算占比，不含热泵。",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$lpPvKwh / $lpTotalKwh", "type": "math" },
    { "expression": "$lpBatteryKwh / $lpTotalKwh", "type": "math" },
    { "expression": "$lpGridKwh / $lpTotalKwh", "type": "math" }
   ]
  }
 ]
}