{
 "title": "VM: EVCC: 年",
 "tags": [ "EVCC" ],
 "time": { "from": "now/y", "to": "now/y" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "dashboardBuild", "label": "构建", "query": "info" },
   { "name": "loadpointBlocklist", "label": "充电点屏蔽列表", "query": "^none$" },
   { "name": "vehicleBlocklist", "label": "车辆屏蔽列表", "query": "^none$" },
   { "name": "extBlocklist", "label": "EXT 屏蔽列表", "query": "^none$" },
   { "name": "auxBlocklist", "label": "AUX 屏蔽列表", "query": "^none$" },
   {
    "name": "heatPumpLoadpointRegex",
    "label": "热泵负载点匹配",
    "query": "(?i).*(daikin-wp|wp|warmepumpe|wärmepumpe|heat pump).*"
   },
   { "name": "installedWattPeak", "label": "installedWattPeak", "query": "20" },
   { "name": "evccUrl", "label": "EVCC 网址", "query": "${VAR_EVCCURL}" },
   { "name": "inverterPortalTitle", "label": "逆变器门户名称", "query": "${VAR_INVERTERPORTALTITLE}" },
   { "name": "inverterPortalUrl", "label": "逆变器门户网址", "query": "${VAR_INVERTERPORTALURL}" }
  ]
 },
 "panels": [
  { "title": "光伏发电", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "能源总计",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "家庭"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "光伏发电"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "电网输入"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "馈电"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (loadpoint) / 1000, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    }
   ]
  },
  {
   "title": "能源",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "label_set((sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)) /1000, \"series\", \"PV\") or label_set((sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)) /1000, \"series\", \"Grid import\") or label_set(((sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)) * -1) /1000, \"series\", \"Home\") or label_copy(((sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{local_year=\"${__from:date:YYYY}\",loadpoint!~\"$loadpointBlocklist\"}[1d]))[$__range:1d])) by (local_month, loadpoint)) * -1) /1000, \"loadpoint\", \"series\") or label_set(((sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)) * -1) /1000, \"series\", \"Feed-in\")"
    }
   ]
  },
  {
   "title": "单位收益",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kWh/kWp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$pvEnergy / $installedWattPeak", "type": "math" }
   ]
  },
  {
   "title": "指标仪表",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1 - $gridEnergyIn / ($homeEnergy + $loadpointEnergy)",
     "type": "math"
    },
    {
     "expression": "($pvEnergy - $gridEnergyOut) / $pvEnergy",
     "type": "math"
    }
   ]
  },
  {
   "title": "指标",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "WITH (\n  gridImport = sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month),\n  homeEnergy = sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month),\n  loadpointEnergy = sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month),\n  pvEnergy = sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month),\n  gridExport = sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month),\n  autarky = label_set(1 - gridImport / (homeEnergy + loadpointEnergy), \"series\", \"Autarky\"),\n  selfConsumption = label_set((pvEnergy - gridExport) / pvEnergy, \"series\", \"Self-consumption\")\n)\nautarky or selfConsumption"
    }
   ]
  },
  {
   "title": "日均能量",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_set((avg(avg_over_time((last_over_time(evcc_pv_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000), \"series\", \"PV/day\")",
     "legendFormat": "{{series}}"
    },
    {
     "expr": "label_set(((avg(avg_over_time((last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) + avg(avg_over_time(sum(last_over_time(evcc_loadpoint_energy_daily_wh{loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))) / 1000), \"series\", \"Consumption/day\")",
     "legendFormat": "{{series}}"
    },
    {
     "expr": "label_set((avg(avg_over_time((last_over_time(evcc_grid_import_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000), \"series\", \"Grid import/day\")",
     "legendFormat": "{{series}}"
    }
   ]
  },
  {
   "title": "每日能源",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "max without(local_year,local_month)(evcc_pv_energy_daily_wh{local_year=\"${__from:date:YYYY}\"})",
     "legendFormat": "光伏发电"
    },
    { "expression": "$homeEnergy + $loadpointEnergy", "type": "math" },
    {
     "expr": "max without(local_year,local_month)(evcc_grid_import_daily_wh{local_year=\"${__from:date:YYYY}\"})",
     "legendFormat": "电网输入"
    }
   ]
  },
  { "title": "家庭", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "家庭：能源分配",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$homeTotalPie - $extSum", "type": "math" },
    {
     "expr": "sort_by_label(sum(sum_over_time(((last_over_time(evcc_ext_energy_daily_wh{title!=\"\",title!~\"$extBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d])))[$__range:1d])) by (title) / 1000, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time(((last_over_time(evcc_aux_energy_daily_wh{title!=\"\",title!~\"$auxBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d])))[$__range:1d])) by (title) / 1000, \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "家庭：能源消耗",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "WITH (\n  other = label_set((sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month) - sum(sum_over_time((last_over_time(evcc_ext_energy_daily_wh{title!=\"\",title!~\"$extBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)) / 1000, \"series\", \"Other\"),\n  ext = label_copy((sum(sum_over_time((last_over_time(evcc_ext_energy_daily_wh{local_year=\"${__from:date:YYYY}\",title!=\"\",title!~\"$extBlocklist\"}[1d]))[$__range:1d])) by (local_month, title)) / 1000, \"title\", \"series\"),\n  aux = label_copy((sum(sum_over_time((last_over_time(evcc_aux_energy_daily_wh{local_year=\"${__from:date:YYYY}\",title!=\"\",title!~\"$auxBlocklist\"}[1d]))[$__range:1d])) by (local_month, title)) / 1000, \"title\", \"series\")\n)\nother or ext or aux"
    }
   ]
  },
  {
   "title": "总计：能源分配",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "家庭"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (loadpoint) / 1000, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    },
    {
     "expression": "$chargeEnergy - $dischargeEnergy",
     "type": "math",
     "settings": { "displayName": "电池" }
    }
   ]
  },
  {
   "title": "家庭：能源分配",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "WITH (\n  batteryNet = ((sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)) - (sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month))) / 1000,\n  batteryCharge = label_set((batteryNet > 0), \"series\", \"Battery charge\"),\n  batteryDischarge = label_set((batteryNet < 0), \"series\", \"Battery discharge\"),\n  home = label_set((sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)) / 1000, \"series\", \"Home\"),\n  loadpoints = label_copy((sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{local_year=\"${__from:date:YYYY}\",loadpoint!~\"$loadpointBlocklist\"}[1d]))[$__range:1d])) by (local_month, loadpoint)) / 1000, \"loadpoint\", \"series\")\n)\nhome or sort_by_label(loadpoints, \"series\") or batteryCharge or batteryDischarge"
    }
   ]
  },
  {
   "title": "功率平衡",
   "type": "stat",
   "gridPos": { "h": 18, "w": 5, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / sum(count_over_time((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))",
     "legendFormat": "averagePrice"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) * -1",
     "legendFormat": "购电"
    },
    {
     "expression": "($purchased * -100) / ($energyPurchased / 1000)",
     "type": "math"
    },
    {
     "expression": "$averagePrice - $weightedAveragePrice",
     "type": "math"
    },
    {
     "expression": "$averagePrice * ($energyPurchased / 1000) / -100",
     "type": "math"
    },
    {
     "expression": "$purchased - $potentialPurchased",
     "type": "math"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))",
     "legendFormat": "售电"
    },
    { "expression": "$purchased + $sold", "type": "math" }
   ]
  },
  {
   "title": "动态电价",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ct" } },
   "targets": [
    {
     "expr": "sum without (local_month) ((last_over_time(evcc_grid_import_price_max_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\"}[1d])))",
     "legendFormat": "Max"
    },
    {
     "expr": "sum without (local_month) ((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\"}[1d])))",
     "legendFormat": "平均值"
    },
    {
     "expr": "sum without (local_month) ((last_over_time(evcc_grid_import_price_effective_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\"}[1d])))",
     "legendFormat": "实际电价"
    },
    {
     "expr": "sum without (local_month) ((last_over_time(evcc_grid_import_price_min_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\"}[1d])))",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "电力成本",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "label_set((sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)), \"series\", \"Purchased\")"
    },
    {
     "expr": "label_set((sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)), \"series\", \"Sold\") and on() (sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) > 0)"
    }
   ]
  },
  { "title": "电池", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "电池摘要",
   "type": "stat",
   "gridPos": { "h": 18, "w": 5, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))",
     "legendFormat": "batteryChargeTotal"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))",
     "legendFormat": "batteryDischargeTotal"
    },
    {
     "expression": "$batteryDischargeTotal / $batteryChargeTotal",
     "type": "math"
    },
    {
     "expr": "sum(avg_over_time((last_over_time(evcc_battery_soc_daily_max_pct{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / count(avg_over_time((last_over_time(evcc_battery_soc_daily_max_pct{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))",
     "legendFormat": "maxSoc"
    },
    {
     "expr": "sum(avg_over_time((last_over_time(evcc_battery_soc_daily_min_pct{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) / count(avg_over_time((last_over_time(evcc_battery_soc_daily_min_pct{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d]))",
     "legendFormat": "minSoc"
    }
   ]
  },
  {
   "title": "电池：最大值",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 67 },
   "targets": [
    {
     "expr": "max without(local_month)(evcc_battery_soc_daily_max_pct{local_year=\"${__from:date:YYYY}\"})",
     "legendFormat": "最高 SOC"
    }
   ]
  },
  {
   "title": "电池充电",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "WITH (\n  charge = label_set(sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month) / 1000, \"series\", \"Charge\"),\n  discharge = label_set(sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month) / 1000, \"series\", \"Discharge\")\n)\ncharge or discharge"
    }
   ]
  },
  {
   "title": "电池：最小值",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 76 },
   "targets": [
    {
     "expr": "min without(local_month)(evcc_battery_soc_daily_min_pct{local_year=\"${__from:date:YYYY}\"})",
     "legendFormat": "最低 SOC"
    }
   ]
  },
  {
   "title": "电池效率",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_set((sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)) / (sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month)), \"series\", \"Battery efficiency\")"
    }
   ]
  },
  { "title": "用能设备", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "热泵总量",
   "type": "stat",
   "description": "匹配负载点上的年度热泵能耗。",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($hpPvWh + $hpBatteryWh + $hpGridWh) / 1000",
     "type": "math"
    }
   ]
  },
  {
   "title": "热泵来源占比",
   "type": "bargauge",
   "description": "热泵负载点的光伏、电池放电和电网供电估算占比。",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$hpPvKwh / $hpTotalKwh", "type": "math" },
    { "expression": "$hpBatteryKwh / $hpTotalKwh", "type": "math" },
    { "expression": "$hpGridKwh / $hpTotalKwh", "type": "math" }
   ]
  },
  {
   "title": "充电桩总量",
   "type": "stat",
   "description": "可见充电负载点的年度充电能耗，不含热泵负载点。",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($lpPvWh + $lpBatteryWh + $lpGridWh) / 1000",
     "type": "math"
    }
   ]
  },
  {
   "title": "充电桩来源占比",
   "type": "bargauge",
   "description": "可见充电负载点的光伏、电池放电和电网供电估算占比，不含热泵。",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$lpPvKwh / $lpTotalKwh", "type": "math" },
    { "expression": "$lpBatteryKwh / $lpTotalKwh", "type": "math" },
    { "expression": "$lpGridKwh / $lpTotalKwh", "type": "math" }
   ]
  },
  { "title": "车辆", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "车辆",
   "type": "stat",
   "description": "消费数据需要数月后才有意义。外部充电被忽略，会扭曲结果。",
   "gridPos": { "h": 24, "w": 5, "x": 0, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(max by (vehicle) (max_over_time(vehicleOdometer_value{vehicle!=\"\",vehicle!~\"$vehicleBlocklist\"}[10y])), \"vehicle\")",
     "legendFormat": "最大里程表：{{vehicle}}"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_vehicle_distance_daily_km{vehicle!=\"\",vehicle!~\"$vehicleBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (vehicle)",
     "legendFormat": "已行驶：{{vehicle}}"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_vehicle_energy_daily_wh{vehicle!=\"\",vehicle!~\"$vehicleBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (vehicle) / 1000",
     "legendFormat": "能量：{{vehicle}}"
    },
    {
     "expression": "$vehicleChargedEnergy / $vehicleDrivenKm * 100",
     "type": "math"
    }
   ]
  },
  {
   "title": "每月行驶公里",
   "type": "barchart",
   "description": "只有在车辆接入时才会记录公里数。如果接入频率较低，公里数可能会缺失。",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_copy(sum(sum_over_time((last_over_time(evcc_vehicle_distance_daily_km{vehicle!=\"\",vehicle!~\"$vehicleBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month, vehicle), \"vehicle\", \"series\")"
    }
   ]
  },
  {
   "title": "每月充电能量",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "label_copy(sum(sum_over_time((last_over_time(evcc_vehicle_energy_daily_wh{vehicle!=\"\",vehicle!~\"$vehicleBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month, vehicle) / 1000, \"vehicle\", \"series\")"
    }
   ]
  },
  {
   "title": "能耗 (kWh/100km)",
   "type": "barchart",
   "description": "这些值为近似值。不包含外部充电，记录到的公里数取决于车辆接入的频率。",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "label_copy((sum(sum_over_time((last_over_time(evcc_vehicle_energy_daily_wh{vehicle!=\"\",vehicle!~\"$vehicleBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month, vehicle) / 1000) / (sum(sum_over_time((last_over_time(evcc_vehicle_distance_daily_km{vehicle!=\"\",vehicle!~\"$vehicleBlocklist\",local_year=\"${__from:date:YYYY}\"}[1d]))[$__range:1d])) by (local_month, vehicle)) * 100, \"vehicle\", \"series\")"
    }
   ]
  }
 ]
}