{
 "title": "VM: EVCC: Monat",
 "tags": [ "EVCC" ],
 "time": { "from": "now/M", "to": "now/M" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "dashboardBuild", "label": "Build", "query": "info" },
   { "name": "loadpointBlocklist", "label": "Loadpoint Blocklist", "query": "^none$" },
   {
    "name": "heatPumpLoadpointRegex",
    "label": "Wärmepumpen-Loadpoint-Muster",
    "query": "(?i).*(daikin-wp|wp|warmepumpe|wärmepumpe|heat pump).*"
   },
   { "name": "extBlocklist", "label": "EXT Blocklist", "query": "^none$" },
   { "name": "auxBlocklist", "label": "AUX Blocklist", "query": "^none$" },
   { "name": "installedWattPeak", "label": "installedWattPeak", "query": "20" },
   { "name": "evccUrl", "label": "EVCC URL", "query": "${VAR_EVCCURL}" },
   { "name": "inverterPortalTitle", "label": "Name, Wechselrichterportal", "query": "${VAR_INVERTERPORTALTITLE}" },
   { "name": "inverterPortalUrl", "label": "URL, Wechselrichterportal", "query": "${VAR_INVERTERPORTALURL}" }
  ]
 },
 "panels": [
  { "title": "PV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Monatliche Gesamtenergie",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "homeMonthlyDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "pvMonthlyDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "gridMonthlyDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "feedInMonthlyDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "loadpointMonthlyDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "Energie",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "(last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / -1000",
     "legendFormat": "Haus"
    },
    {
     "expr": "(last_over_time(evcc_pv_energy_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000",
     "legendFormat": "PV"
    },
    {
     "expr": "(last_over_time(evcc_grid_import_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000",
     "legendFormat": "Netzbezug"
    },
    {
     "expr": "(last_over_time(evcc_grid_export_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / -1000",
     "legendFormat": "Einspeisung"
    },
    {
     "expr": "sort_by_label((last_over_time(evcc_loadpoint_energy_daily_wh{loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / -1000, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    }
   ]
  },
  {
   "title": "Spezifischer Ertrag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kWh/kWp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$pvEnergy / $installedWattPeak", "type": "math" }
   ]
  },
  {
   "title": "Kennzahlen Gauges",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1 - $gridEnergyIn / ($homeEnergy + $loadpointEnergy)",
     "type": "math"
    },
    {
     "expression": "($pvEnergy - $gridEnergyOut) / $pvEnergy",
     "type": "math"
    }
   ]
  },
  {
   "title": "Kennzahlen",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((sum((last_over_time(evcc_grid_import_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))) / 1000)) / ((sum((last_over_time(evcc_loadpoint_energy_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))) / 1000) + ((last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000))",
     "legendFormat": "Autarkie"
    }
   ]
  },
  { "title": "Haus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Haus: Energieverteilung",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$homeTotalPie - $extSum - $auxSum",
     "type": "math"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time(((last_over_time(evcc_ext_energy_daily_wh{title!=\"\",title!~\"$extBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])))[$__range:1d])) by (title) / 1000, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time(((last_over_time(evcc_aux_energy_daily_wh{title!=\"\",title!~\"$auxBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])))[$__range:1d])) by (title) / 1000, \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Haus: Energieverbrauch",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expression": "$homeTotalDaily - $extTotalDaily",
     "type": "math",
     "settings": { "displayName": "Sonstiges" }
    },
    {
     "expr": "sort_by_label((last_over_time(evcc_ext_energy_daily_wh{title!=\"\",title!~\"$extBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label((last_over_time(evcc_aux_energy_daily_wh{title!=\"\",title!~\"$auxBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000, \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Gesamt: Energieverteilung",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000",
     "legendFormat": "Haus"
    },
    {
     "expr": "sort_by_label((last_over_time(evcc_loadpoint_energy_daily_wh{loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    },
    {
     "expression": "$batteryChargeTotal - $batteryDischargeTotal",
     "type": "math"
    }
   ]
  },
  {
   "title": "Gesamt: Energieverteilung",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "WITH (\n  batteryNet = ((last_over_time(evcc_battery_charge_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) - (last_over_time(evcc_battery_discharge_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))) / 1000,\n  batteryCharge = label_set((batteryNet > 0), \"series\", \"Battery charge\"),\n  batteryDischarge = label_set((batteryNet < 0), \"series\", \"Battery discharge\"),\n  home = label_set((last_over_time(evcc_home_energy_daily_wh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000, \"series\", \"Home\"),\n  loadpoints = label_copy((last_over_time(evcc_loadpoint_energy_daily_wh{loadpoint!~\"$loadpointBlocklist\",local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 1000, \"loadpoint\", \"series\")\n)\nhome or sort_by_label(loadpoints, \"series\") or batteryCharge or batteryDischarge",
     "legendFormat": "{{series}}"
    }
   ]
  },
  {
   "title": "Strombilanz",
   "type": "stat",
   "gridPos": { "h": 18, "w": 5, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "averagePriceDaily", "reducer": "mean", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "$purchasedTotal / $energyPurchased * 100",
     "type": "math"
    },
    {
     "expression": "$averagePrice - $weightedAveragePrice",
     "type": "math"
    },
    {
     "expression": "$averagePrice * $energyPurchased / -100",
     "type": "math"
    },
    { "expression": "$purchasedTotal * -1", "type": "math" },
    { "expression": "$soldTotalRaw * -1", "type": "math" },
    {
     "expression": "$purchasedDisplay - $potentialPurchased",
     "type": "math"
    },
    {
     "expression": "$purchasedDisplay + $soldDisplay",
     "type": "math"
    }
   ]
  },
  {
   "title": "Dynamischer Strompreis (ct/kWh)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ct" } },
   "targets": [
    {
     "expr": "(last_over_time(evcc_grid_import_price_max_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))",
     "legendFormat": "Max"
    },
    {
     "expr": "(last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))",
     "legendFormat": "Durchschnitt"
    },
    {
     "expr": "(last_over_time(evcc_grid_import_price_effective_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))",
     "legendFormat": "Effektiver Strompreis"
    },
    {
     "expr": "(last_over_time(evcc_grid_import_price_min_daily_ct_per_kwh{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Stromkosten",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "(last_over_time(evcc_grid_import_cost_daily_eur{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d]))",
     "legendFormat": "Einkauf"
    }
   ]
  },
  { "title": "Speicher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Speicher",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "batteryChargeDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "batteryDischargeDaily", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "$batteryDischargeTotal / $batteryChargeTotal",
     "type": "math"
    },
    { "expression": "socMaxSeries", "reducer": "mean", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "socMinSeries", "reducer": "mean", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "Batteriestände",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(((last_over_time(evcc_battery_soc_daily_max_pct{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 100) > 0)",
     "legendFormat": "SOC Max"
    },
    {
     "expr": "(((last_over_time(evcc_battery_soc_daily_min_pct{local_year=\"${__from:date:YYYY}\",local_month=\"${__from:date:MM}\"}[1d])) / 100) > 0)",
     "legendFormat": "SOC Min"
    }
   ]
  },
  { "title": "Verbraucher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Wärmepumpe gesamt",
   "type": "stat",
   "description": "Jährliche Wärmepumpenenergie über passende Loadpoints.",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($hpPvWh + $hpBatteryWh + $hpGridWh) / 1000",
     "type": "math"
    }
   ]
  },
  {
   "title": "Versorgungsmix Wärmepumpe",
   "type": "bargauge",
   "description": "Geschätzter Anteil von PV, Batterieentladung und Netzversorgung für den Wärmepumpen-Loadpoint.",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$hpPvKwh / $hpTotalKwh", "type": "math" },
    { "expression": "$hpBatteryKwh / $hpTotalKwh", "type": "math" },
    { "expression": "$hpGridKwh / $hpTotalKwh", "type": "math" }
   ]
  },
  {
   "title": "Ladestationen gesamt",
   "type": "stat",
   "description": "Jährliche Ladeenergie über sichtbare Lade-Loadpoints ohne den Wärmepumpen-Loadpoint.",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($lpPvWh + $lpBatteryWh + $lpGridWh) / 1000",
     "type": "math"
    }
   ]
  },
  {
   "title": "Versorgungsmix Ladestationen",
   "type": "bargauge",
   "description": "Geschätzter Anteil von PV, Batterieentladung und Netzversorgung für sichtbare Lade-Loadpoints ohne Wärmepumpe.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$lpPvKwh / $lpTotalKwh", "type": "math" },
    { "expression": "$lpBatteryKwh / $lpTotalKwh", "type": "math" },
    { "expression": "$lpGridKwh / $lpTotalKwh", "type": "math" }
   ]
  }
 ]
}