{
 "title": "EVCC: di tutti i tempi",
 "tags": [ "PV" ],
 "time": { "from": "2023-02-28T23:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "purchasePricePv",
    "label": "Costi totali di investimento nel fotovoltaico",
    "query": "24884"
   },
   {
    "name": "batteryPurchasePrice",
    "label": "Costo di investimento della batteria",
    "query": "5500"
   },
   { "name": "runningCosts", "label": "Costi correnti", "query": "100" },
   { "name": "vVerbrauch", "label": "Consumo GHIACCIO l/100km", "query": "6" },
   { "name": "spritKosten", "label": "Prezzo carburante/litro", "query": "1.75" },
   { "name": "timezone", "query": "Europe/Berlin" },
   {
    "name": "speicherkapazitaet",
    "label": "Capacità della batteria domestica / Wh",
    "query": "${VAR_SPEICHERKAPAZITAET}"
   },
   {
    "name": "vehicle",
    "label": "Veicolo",
    "query": {
     "query": "show tag values from vehicleMonthlyEnergy with key = \"vehicle\" where \"vehicle\" !~ $vehicleBlocklist"
    }
   },
   { "name": "vehicleBlocklist", "label": "Blocklist per veicoli", "query": "${VAR_VEHICLEBLOCKLIST}" },
   {
    "name": "loadpointBlocklist",
    "label": "Blocklist per punti di caricamento",
    "query": "${VAR_LOADPOINTBLOCKLIST}"
   }
  ]
 },
 "panels": [
  { "title": "Energia", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "gridPos": { "h": 11, "w": 3, "x": 0, "y": 1 } },
  {
   "title": "Rendimento annuale",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "year::tag" ], "type": "tag" }
     ],
     "measurement": "pvMonthlyEnergy",
     "query": "SELECT value, year FROM \"pvMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rendimento mensile/anno",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_month]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT year, month, value FROM \"pvMonthlyEnergy\" tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "gridPos": { "h": 12, "w": 3, "x": 0, "y": 12 } },
  {
   "title": "Consumo domestico annuo",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "year::tag" ], "type": "tag" }
     ],
     "measurement": "pvMonthlyEnergy",
     "query": "SELECT value, year FROM \"homeMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumo domestico mensile/anno",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT year, month, value FROM \"homeMonthlyEnergy\"  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Importazione annuale della griglia",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "year::tag" ], "type": "tag" }
     ],
     "measurement": "pvMonthlyEnergy",
     "query": "SELECT value, year FROM \"gridMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Importazione griglia mensile/anno",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT year, month, value FROM \"gridMonthlyEnergy\"  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 } },
  {
   "title": "Contributo annuale",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "year::tag" ], "type": "tag" }
     ],
     "measurement": "pvMonthlyEnergy",
     "query": "SELECT value, year FROM \"feedInMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Contributo mensile/anno",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT year, month, value FROM \"feedInMonthlyEnergy\"  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Giorni con il rendimento più alto",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "PV Energie",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvPower",
     "query": "SELECT value FROM \"pvDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value::field", "operator": "<", "value": "10000" }
     ]
    }
   ]
  },
  {
   "title": "Alimentazione più alta",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Einspeisung",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gridPower",
     "query": "SELECT value FROM \"feedInDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / -3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value::field", "operator": "<", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Consumi domestici più elevati",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Hausverbrauch",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "homePower",
     "query": "SELECT value FROM \"homeDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value::field", "operator": "<", "value": "10000" }
     ]
    }
   ]
  },
  { "title": "Finanza", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Costi mensili",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "SELECT value FROM energyPurchasedMonthlyPrice WHERE $timeFilter  tz('$timezone')"
    },
    {
     "query": "SELECT value FROM energySoldMonthlyPrice WHERE $timeFilter  tz('$timezone')"
    },
    {
     "expression": "(abs($purchased + $sold) + ($purchased + $sold)) /2",
     "type": "math"
    },
    {
     "expression": "-(abs($purchased + $sold)- ($purchased + $sold)) /2",
     "type": "math"
    }
   ]
  },
  { "gridPos": { "h": 9, "w": 8, "x": 0, "y": 55 } },
  {
   "title": "Ammortamento impianto fotovoltaico",
   "type": "stat",
   "description": "Per meno di 365 giorni di dati, i valori vengono estrapolati a un anno intero con la corrispondente imprecisione a seconda del periodo acquisito.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$potentialHomePrice + $potentialLoadpointPrice",
     "type": "math"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyPurchasedDailyPrice",
     "query": "SELECT sum(\"value\") FROM \"energyPurchasedDailyPrice\" WHERE $timeFilter TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyPurchasedDailyPrice",
     "query": "SELECT sum(\"value\") * (-1) FROM \"energySoldDailyPrice\" WHERE $timeFilter TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "$energyPurchasedPrice - $energySoldPrice",
     "type": "math"
    },
    {
     "expression": "$potentialTotalPrice - $energyTotalPrice",
     "type": "math"
    },
    { "expression": "dailyMeasurement", "reducer": "count", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "$refluxOfCapital*365/$numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$purchasePricePv / ($refluxOfCapitalYearly - $runningCosts)",
     "type": "math"
    },
    {
     "expression": "($refluxOfCapitalYearly - $runningCosts) / $purchasePricePv",
     "type": "math"
    }
   ]
  },
  {
   "title": "Ammortamento della batteria",
   "type": "stat",
   "description": "Per meno di 365 giorni di dati, i valori vengono estrapolati a un anno intero con la corrispondente imprecisione a seconda del periodo acquisito.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") from chargeDailyEnergy WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") from dischargeDailyEnergy WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "1-($dischargedEnergy/$chargedEnergy)",
     "type": "math"
    },
    {
     "expression": "($chargedEnergy/$speicherkapazitaet) * 365/$numberOfMeasuredDays",
     "type": "math"
    },
    { "expression": "dailyMeasurement", "reducer": "count", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "($batteryDischargeCost - $batteryChargeFeedInCost) * 365/$numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$batteryPurchasePrice/$batteryPayback",
     "type": "math"
    },
    {
     "expression": "$batteryPayback/$batteryPurchasePrice",
     "type": "math"
    }
   ]
  },
  {
   "title": "Il viaggio costa $ veicolo",
   "type": "stat",
   "description": "I valori sono stime approssimative basate sulle medie.\n\nIpotesi: il veicolo viene ricaricato principalmente a casa. La ricarica esterna non è inclusa.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "repeat": "vehicle",
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "drivenKm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT spread(\"value\") FROM \"vehicleOdometerDailyMax\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expression": "$chargedEnergy/($drivenKm/100)", "type": "math" },
    {
     "alias": "Solaranteil",
     "measurement": "sessionSolarPercentage",
     "query": "SELECT mean(\"value\") FROM \"sessionSolarPercentage\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Effektiver, durchschnittlicher Preis",
     "measurement": "sessionPricePerKWh",
     "query": "SELECT mean(\"value\") FROM \"sessionPricePerKWh\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"potentialVehicleChargeDailyPrice\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"vehicleChargeDailyPrice\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "$electricDriveCostNoPV - $electricDriveCost",
     "type": "math"
    },
    {
     "expression": "$drivenKm / 100 * $vVerbrauch * $spritKosten",
     "type": "math"
    },
    {
     "expression": "$iceDriveCost - $electricDriveCost",
     "type": "math"
    }
   ]
  },
  { "title": "Salute del sistema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Media dei primi 30 giorni/anno",
   "type": "barchart",
   "description": "Utilizza la resa media dei migliori 30 giorni all'anno. Può aiutare a rilevare il potenziale degrado, ma deve essere interpretato in modo olistico. I singoli anni non sono conclusivi.",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(value, 30) FROM (\n        SELECT * FROM \"pvDailyEnergy\"  TZ('$timezone')\n) GROUP BY year TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Media dei primi 5 giorni al mese",
   "type": "barchart",
   "description": "Utilizza la resa media dei migliori 5 giorni al mese. Può aiutare a rilevare il potenziale degrado, ma deve essere interpretato in modo olistico. I singoli mesi non sono conclusivi.",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(top) FROM (\n    SELECT top(value, 5) FROM (\n        SELECT year, month, value FROM \"pvDailyEnergy\"  TZ('$timezone')\n    ) GROUP BY month, year TZ('$timezone')\n) GROUP BY month, year TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}