{
 "title": "VM: EVCC: Oggi - Dettagli",
 "tags": [ "EVCC" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "dashboardBuild", "label": "Build", "query": "info" },
   { "name": "peakPowerLimit", "label": "Filtro potenza massima / W", "query": "30000" },
   { "name": "loadpointBlocklist", "label": "Blocklist punti di ricarica", "query": "^none$" },
   { "name": "extBlocklist", "query": "^none$" },
   { "name": "auxBlocklist", "query": "^none$" },
   {
    "name": "loadpoint",
    "label": "Punto di ricarica",
    "query": "label_values(chargePower_value, loadpoint)"
   },
   {
    "name": "energySampleInterval",
    "label": "Intervallo di campionamento energia",
    "query": "30s"
   },
   { "name": "tariffPriceInterval", "label": "Intervallo tariffa", "query": "15m" },
   { "name": "evccUrl", "label": "URL dell'EVCC", "query": "${VAR_EVCCURL}" },
   { "name": "inverterPortalTitle", "label": "Nome portale inverter", "query": "${VAR_INVERTERPORTALTITLE}" },
   { "name": "inverterPortalUrl", "label": "URL portale inverter", "query": "${VAR_INVERTERPORTALURL}" }
  ]
 },
 "panels": [
  { "title": "PV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Energia FV",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "sort_by_label(range_sum(integrate((avg by (title) (pvPower_value{id!=\"\",title!=\"\"}) or label_copy(avg by (id) (pvPower_value{id!=\"\",title=\"\"}), \"id\", \"title\")) < $peakPowerLimit)) / 3600000, \"title\")",
     "legendFormat": "{{title}}"
    },
    { "expr": "min(chargePower_value)", "legendFormat": "__panel_axis" },
    {
     "expr": "range_sum(integrate(avg(pvPower_value{id=\"\"}) < $peakPowerLimit)) / 3600000",
     "legendFormat": "Totale"
    }
   ]
  },
  {
   "title": "Potenza FV",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sort_by_label((avg by (title) (pvPower_value{id!=\"\",title!=\"\"}) or label_copy(avg by (id) (pvPower_value{id!=\"\",title=\"\"}), \"id\", \"title\")), \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Livello batteria",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(avg by (title) (batterySoc_value{id!=\"\", title!=\"\"}), \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "avg(batterySoc_value{id=\"\"})",
     "legendFormat": "Totale"
    }
   ]
  },
  {
   "title": "Potenza batteria",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg by (title)(batteryPower_value{id!=\"\"})",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Previsione",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "range_sum(integrate(avg(tariffSolar_value))) / 3600000",
     "legendFormat": "Previsione"
    },
    { "expr": "min(chargePower_value)", "legendFormat": "__panel_axis" },
    {
     "expr": "range_sum(integrate(avg(pvPower_value{id=\"\"}) < $peakPowerLimit)) / 3600000",
     "legendFormat": "Reale"
    }
   ]
  },
  {
   "title": "Previsione",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "avg(tariffSolar_value)", "legendFormat": "Previsione" },
    {
     "expr": "avg(pvPower_value{id=\"\"})",
     "legendFormat": "Reale"
    }
   ]
  },
  { "title": "Consumo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Casa: potenza attuale",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(homePower_value) - sum(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))",
     "legendFormat": "Altro"
    },
    {
     "expr": "avg(homePower_value) - sum(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))",
     "legendFormat": "Altro"
    },
    {
     "expr": "avg(homePower_value) - sum(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"})) - sum(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))",
     "legendFormat": "Altro"
    },
    {
     "expr": "sort_by_label(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Casa: potenza",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(homePower_value) - sum(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))",
     "legendFormat": "Altro"
    },
    {
     "expr": "avg(homePower_value) - sum(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))",
     "legendFormat": "Altro"
    },
    {
     "expr": "avg(homePower_value) - sum(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"})) - sum(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))",
     "legendFormat": "Altro"
    },
    {
     "expr": "sort_by_label(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Casa: distribuzione energia",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_sum(integrate(avg(homePower_value)))/3600 - range_sum(integrate(sum(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))))/3600 - range_sum(integrate(sum(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))))/3600",
     "legendFormat": "Altro"
    },
    {
     "expr": "range_sum(integrate(avg(homePower_value)))/3600 - range_sum(integrate(sum(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}))))/3600 ",
     "legendFormat": "Altro"
    },
    {
     "expr": "range_sum(integrate(avg(homePower_value)))/3600 - range_sum(integrate(sum(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}))))/3600 ",
     "legendFormat": "Altro"
    },
    {
     "expr": "sort_by_label(range_sum(integrate(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"})))/3600, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(range_sum(integrate(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"})))/3600, \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Casa: energia",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(integrate(avg(homePower_value) offset -1h))/3600 - sum(integrate(extPower_value{title!=\"\", title !~ \"$extBlocklist\"} offset -1h))/3600 - sum(integrate(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"} offset -1h))/3600",
     "legendFormat": "Altro"
    },
    {
     "expr": "sum(integrate(avg(homePower_value) offset -1h))/3600 - sum(integrate(extPower_value{title!=\"\", title !~ \"$extBlocklist\"} offset -1h))/3600",
     "legendFormat": "Altro"
    },
    {
     "expr": "sum(integrate(avg(homePower_value) offset -1h))/3600 - sum(integrate(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"} offset -1h))/3600",
     "legendFormat": "Altro"
    },
    {
     "expr": "sort_by_label(integrate(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}) offset -1h)/3600, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(integrate(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}) offset -1h)/3600, \"title\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Totale: distribuzione energia",
   "type": "piechart",
   "description": "La formula per 'Altro' deve essere modificata in base alla disponibilità dei contatori AUX ed EXT. Vedi https://github.com/ha-puzzles/evcc-grafana-dashboards/tree/main/dashboards#formel-für-sonstige-anpassen per i dettagli.",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_sum(integrate(avg(homePower_value)))/3600",
     "legendFormat": "Casa"
    },
    {
     "expr": "sort_by_label(sum by (loadpoint)(range_sum (integrate(chargePower_value{loadpoint!=\"\", loadpoint !~ \"$loadpointBlocklist\"})) / 3600), \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    }
   ]
  },
  {
   "title": "Totale: energia",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(integrate(avg(homePower_value) offset -1h))/3600",
     "legendFormat": "Casa"
    },
    {
     "expr": "sort_by_label(avg by(loadpoint)(integrate(chargePower_value{loadpoint!=\"\"} offset -1h))/3600, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    }
   ]
  },
  { "title": "Tariffe", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Prezzo dell'elettricità",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(avg(tariffGrid_value)[1d])",
     "legendFormat": "Max"
    },
    {
     "expr": "avg_over_time(avg(tariffGrid_value)[1d])",
     "legendFormat": "Media"
    },
    {
     "expr": "min_over_time(avg(tariffGrid_value)[1d])",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Prezzo dell'elettricità",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 56 },
   "targets": [
    {
     "expr": "avg(tariffGrid_value offset -$tariffPriceInterval)",
     "legendFormat": "Prezzo"
    },
    {
     "expr": "clamp_min(avg(gridPower_value offset -$tariffPriceInterval), 0)",
     "legendFormat": "Prelievo rete"
    }
   ]
  },
  {
   "title": "Costi",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_sum(avg(tariffGrid_value) * integrate(clamp_min(avg(gridPower_value), 0)) /3600000)",
     "legendFormat": "Acquistato"
    },
    {
     "expr": "range_sum(avg(tariffFeedIn_value) * integrate(clamp_max(avg(gridPower_value), 0)) /3600000)",
     "legendFormat": "Venduto"
    },
    { "expression": "$bought + $sold", "type": "math" }
   ]
  },
  {
   "title": "Costi",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "avg(tariffGrid_value offset -$tariffPriceInterval) * integrate(clamp_min(avg(gridPower_value offset -$tariffPriceInterval), 0)) /3600000",
     "legendFormat": "Acquistato"
    },
    {
     "expr": "avg(tariffFeedIn_value offset -$tariffPriceInterval) * integrate(clamp_max(avg(gridPower_value offset -$tariffPriceInterval), 0)) /3600000",
     "legendFormat": "Venduto"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "g/kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(avg(tariffCo2_value)[1d])",
     "legendFormat": "Max"
    },
    {
     "expr": "avg_over_time(avg(tariffCo2_value)[1d])",
     "legendFormat": "Media"
    },
    {
     "expr": "min_over_time(avg(tariffCo2_value)[1d])",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 74 },
   "targets": [
    {
     "expr": "avg(tariffCo2_value offset -$tariffPriceInterval)",
     "legendFormat": "CO2"
    },
    {
     "expr": "clamp_min(avg(gridPower_value), 0)",
     "legendFormat": "Prelievo rete"
    }
   ]
  },
  { "title": "Rete", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Correnti/fase",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(avg(gridCurrents_l1))",
     "legendFormat": "Corrente L1"
    },
    {
     "expr": "last_over_time(avg(gridCurrents_l2))",
     "legendFormat": "Corrente L2"
    },
    {
     "expr": "last_over_time(avg(gridCurrents_l3))",
     "legendFormat": "Corrente L3"
    }
   ]
  },
  {
   "title": "Correnti/fase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "avg(gridCurrents_l1)", "legendFormat": "Corrente L1" },
    { "expr": "avg(gridCurrents_l2)", "legendFormat": "Corrente L2" },
    { "expr": "avg(gridCurrents_l3)", "legendFormat": "Corrente L3" }
   ]
  },
  {
   "title": "Potenza/fase",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(avg(gridPowers_l1))",
     "legendFormat": "Potenza L1"
    },
    {
     "expr": "last_over_time(avg(gridPowers_l2))",
     "legendFormat": "Potenza L2"
    },
    {
     "expr": "last_over_time(avg(gridPowers_l3))",
     "legendFormat": "Potenza L3"
    }
   ]
  },
  {
   "title": "Potenza/fase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "avg(gridPowers_l1)", "legendFormat": "Potenza L1" },
    { "expr": "avg(gridPowers_l2)", "legendFormat": "Potenza L2" },
    { "expr": "avg(gridPowers_l3)", "legendFormat": "Potenza L3" }
   ]
  },
  { "title": "Punto di ricarica $loadpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }, "repeat": "loadpoint" },
  {
   "title": "Correnti di carica/fase: $loadpoint",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(avg(chargeCurrents_l1{loadpoint=\"$loadpoint\"}))",
     "legendFormat": "Corrente L1"
    },
    {
     "expr": "last_over_time(avg(chargeCurrents_l2{loadpoint=\"$loadpoint\"}))",
     "legendFormat": "Corrente L2"
    },
    {
     "expr": "last_over_time(avg(chargeCurrents_l3{loadpoint=\"$loadpoint\"}))",
     "legendFormat": "Corrente L3"
    }
   ]
  },
  {
   "title": "Correnti di carica/fase: $loadpoint",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "avg(chargeCurrents_l1{loadpoint=\"$loadpoint\"})",
     "legendFormat": "Corrente L1"
    },
    {
     "expr": "avg(chargeCurrents_l2{loadpoint=\"$loadpoint\"})",
     "legendFormat": "Corrente L2"
    },
    {
     "expr": "avg(chargeCurrents_l3{loadpoint=\"$loadpoint\"})",
     "legendFormat": "Corrente L3"
    }
   ]
  },
  {
   "title": "Fasi: $loadpoint",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 112 },
   "targets": [
    {
     "expr": "((avg(chargeCurrents_l1{loadpoint=\"$loadpoint\"}) > bool 0.1) + (avg(chargeCurrents_l2{loadpoint=\"$loadpoint\"}) > bool 0.1) + (avg(chargeCurrents_l3{loadpoint=\"$loadpoint\"}) > bool 0.1))",
     "legendFormat": "Fasi attive"
    }
   ]
  },
  {
   "title": "Potenza di carica: $loadpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(chargePower_value {loadpoint=\"$loadpoint\"})",
     "legendFormat": "Potenza di carica"
    }
   ]
  }
 ]
}