{
 "title": "EVCC: सर्वकालिक",
 "tags": [ "PV" ],
 "time": { "from": "2023-02-28T23:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   { "name": "purchasePricePv", "label": "पीवी कुल निवेश लागत", "query": "24884" },
   { "name": "batteryPurchasePrice", "label": "बैटरी निवेश लागत", "query": "5500" },
   { "name": "runningCosts", "label": "चल रही लागत", "query": "100" },
   { "name": "vVerbrauch", "label": "आईसीई खपत एल/100 किमी", "query": "6" },
   { "name": "spritKosten", "label": "ईंधन की कीमत/लीटर", "query": "1.75" },
   { "name": "timezone", "query": "Europe/Berlin" },
   { "name": "speicherkapazitaet", "label": "घरेलू बैटरी क्षमता / क", "query": "${VAR_SPEICHERKAPAZITAET}" },
   {
    "name": "vehicle",
    "label": "वाहन",
    "query": {
     "query": "show tag values from vehicleMonthlyEnergy with key = \"vehicle\" where \"vehicle\" !~ $vehicleBlocklist"
    }
   },
   { "name": "vehicleBlocklist", "label": "वाहनों के लिए ब्लॉकलिस्ट", "query": "${VAR_VEHICLEBLOCKLIST}" },
   { "name": "loadpointBlocklist", "label": "लोडप्वाइंट के लिए ब्लॉकलिस्ट", "query": "${VAR_LOADPOINTBLOCKLIST}" }
  ]
 },
 "panels": [
  { "title": "ऊर्जा", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "gridPos": { "h": 11, "w": 3, "x": 0, "y": 1 } },
  {
   "title": "वार्षिक उपज",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "year::tag" ], "type": "tag" }
     ],
     "measurement": "pvMonthlyEnergy",
     "query": "SELECT value, year FROM \"pvMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "मासिक उपज/वर्ष",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_month]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT year, month, value FROM \"pvMonthlyEnergy\" tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "gridPos": { "h": 12, "w": 3, "x": 0, "y": 12 } },
  {
   "title": "वार्षिक घरेलू खपत",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "year::tag" ], "type": "tag" }
     ],
     "measurement": "pvMonthlyEnergy",
     "query": "SELECT value, year FROM \"homeMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "मासिक घरेलू खपत/वर्ष",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT year, month, value FROM \"homeMonthlyEnergy\"  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "वार्षिक ग्रिड आयात",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "year::tag" ], "type": "tag" }
     ],
     "measurement": "pvMonthlyEnergy",
     "query": "SELECT value, year FROM \"gridMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "मासिक ग्रिड आयात/वर्ष",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT year, month, value FROM \"gridMonthlyEnergy\"  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 } },
  {
   "title": "वार्षिक फीड-इन",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "year::tag" ], "type": "tag" }
     ],
     "measurement": "pvMonthlyEnergy",
     "query": "SELECT value, year FROM \"feedInMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "मासिक फीड-इन/वर्ष",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT year, month, value FROM \"feedInMonthlyEnergy\"  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "सर्वाधिक उपज वाले दिन",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "PV Energie",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvPower",
     "query": "SELECT value FROM \"pvDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value::field", "operator": "<", "value": "10000" }
     ]
    }
   ]
  },
  {
   "title": "उच्चतम फ़ीड-इन",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Einspeisung",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gridPower",
     "query": "SELECT value FROM \"feedInDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / -3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value::field", "operator": "<", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "उच्चतम घरेलू खपत",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Hausverbrauch",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "homePower",
     "query": "SELECT value FROM \"homeDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value::field", "operator": "<", "value": "10000" }
     ]
    }
   ]
  },
  { "title": "वित्त", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "मासिक लागत",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "SELECT value FROM energyPurchasedMonthlyPrice WHERE $timeFilter  tz('$timezone')"
    },
    {
     "query": "SELECT value FROM energySoldMonthlyPrice WHERE $timeFilter  tz('$timezone')"
    },
    {
     "expression": "(abs($purchased + $sold) + ($purchased + $sold)) /2",
     "type": "math"
    },
    {
     "expression": "-(abs($purchased + $sold)- ($purchased + $sold)) /2",
     "type": "math"
    }
   ]
  },
  { "gridPos": { "h": 9, "w": 8, "x": 0, "y": 55 } },
  {
   "title": "पीवी प्रणाली परिशोधन",
   "type": "stat",
   "description": "365 दिनों से कम के डेटा के लिए, कैप्चर की गई अवधि के आधार पर मानों को संबंधित अशुद्धि के साथ पूरे वर्ष के लिए एक्सट्रपलेशन किया जाता है।",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$potentialHomePrice + $potentialLoadpointPrice",
     "type": "math"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyPurchasedDailyPrice",
     "query": "SELECT sum(\"value\") FROM \"energyPurchasedDailyPrice\" WHERE $timeFilter TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyPurchasedDailyPrice",
     "query": "SELECT sum(\"value\") * (-1) FROM \"energySoldDailyPrice\" WHERE $timeFilter TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "$energyPurchasedPrice - $energySoldPrice",
     "type": "math"
    },
    {
     "expression": "$potentialTotalPrice - $energyTotalPrice",
     "type": "math"
    },
    { "expression": "dailyMeasurement", "reducer": "count", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "$refluxOfCapital*365/$numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$purchasePricePv / ($refluxOfCapitalYearly - $runningCosts)",
     "type": "math"
    },
    {
     "expression": "($refluxOfCapitalYearly - $runningCosts) / $purchasePricePv",
     "type": "math"
    }
   ]
  },
  {
   "title": "बैटरी परिशोधन",
   "type": "stat",
   "description": "365 दिनों से कम के डेटा के लिए, कैप्चर की गई अवधि के आधार पर मानों को संबंधित अशुद्धि के साथ पूरे वर्ष के लिए एक्सट्रपलेशन किया जाता है।",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") from chargeDailyEnergy WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") from dischargeDailyEnergy WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "1-($dischargedEnergy/$chargedEnergy)",
     "type": "math"
    },
    {
     "expression": "($chargedEnergy/$speicherkapazitaet) * 365/$numberOfMeasuredDays",
     "type": "math"
    },
    { "expression": "dailyMeasurement", "reducer": "count", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "($batteryDischargeCost - $batteryChargeFeedInCost) * 365/$numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$batteryPurchasePrice/$batteryPayback",
     "type": "math"
    },
    {
     "expression": "$batteryPayback/$batteryPurchasePrice",
     "type": "math"
    }
   ]
  },
  {
   "title": "यात्रा लागत $वाहन",
   "type": "stat",
   "description": "मान औसत पर आधारित अनुमानित अनुमान हैं।\n\nधारणा: वाहन को मुख्य रूप से घर पर चार्ज किया जाता है। बाहरी चार्जिंग शामिल नहीं है.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "repeat": "vehicle",
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "drivenKm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT spread(\"value\") FROM \"vehicleOdometerDailyMax\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expression": "$chargedEnergy/($drivenKm/100)", "type": "math" },
    {
     "alias": "Solaranteil",
     "measurement": "sessionSolarPercentage",
     "query": "SELECT mean(\"value\") FROM \"sessionSolarPercentage\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Effektiver, durchschnittlicher Preis",
     "measurement": "sessionPricePerKWh",
     "query": "SELECT mean(\"value\") FROM \"sessionPricePerKWh\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"potentialVehicleChargeDailyPrice\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"vehicleChargeDailyPrice\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "$electricDriveCostNoPV - $electricDriveCost",
     "type": "math"
    },
    {
     "expression": "$drivenKm / 100 * $vVerbrauch * $spritKosten",
     "type": "math"
    },
    {
     "expression": "$iceDriveCost - $electricDriveCost",
     "type": "math"
    }
   ]
  },
  { "title": "सिस्टम स्वास्थ्य", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "औसत शीर्ष 30 दिन/वर्ष",
   "type": "barchart",
   "description": "प्रति वर्ष सर्वोत्तम 30 दिनों की औसत उपज का उपयोग करता है। संभावित गिरावट का पता लगाने में मदद मिल सकती है, लेकिन इसकी व्याख्या समग्र रूप से की जानी चाहिए। एकल वर्ष निर्णायक नहीं हैं.",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "[[tag_year]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(value, 30) FROM (\n        SELECT * FROM \"pvDailyEnergy\"  TZ('$timezone')\n) GROUP BY year TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "औसत शीर्ष 5 दिन/माह",
   "type": "barchart",
   "description": "प्रति माह सर्वोत्तम 5 दिनों की औसत उपज का उपयोग करता है। संभावित गिरावट का पता लगाने में मदद मिल सकती है, लेकिन इसकी व्याख्या समग्र रूप से की जानी चाहिए। एक महीना निर्णायक नहीं होता.",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(top) FROM (\n    SELECT top(value, 5) FROM (\n        SELECT year, month, value FROM \"pvDailyEnergy\"  TZ('$timezone')\n    ) GROUP BY month, year TZ('$timezone')\n) GROUP BY month, year TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}