{
 "title": "EVCC: आज - विवरण",
 "tags": [ "PV" ],
 "time": { "from": "2026-01-29T23:00:00.000Z", "to": "2026-01-30T22:59:59.000Z" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "timezone", "label": "समयक्षेत्र", "query": "${VAR_TIMEZONE}" },
   {
    "name": "peakPowerLimit",
    "label": "अधिकतम शक्ति/डब्ल्यू के लिए फ़िल्टर",
    "query": "${VAR_PEAKPOWERLIMIT}"
   },
   { "name": "loadpointBlocklist", "label": "लोडप्वाइंट के लिए ब्लॉकलिस्ट", "query": "${VAR_LOADPOINTBLOCKLIST}" },
   {
    "name": "loadpoint",
    "label": "चार्जिंग पॉइंट",
    "query": {
     "query": "show tag values from chargePower with key = \"loadpoint\" where \"loadpoint\" !~ $loadpointBlocklist"
    }
   },
   { "name": "energySampleInterval", "label": "ऊर्जा नमूना अंतराल", "query": "${VAR_ENERGYSAMPLEINTERVAL}" },
   { "name": "tariffPriceInterval", "label": "टैरिफ अंतराल", "query": "${VAR_TARIFFPRICEINTERVAL}" }
  ]
 },
 "panels": [
  { "title": "पीवी", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "पीवी ऊर्जा",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\") /3600000 FROM \"pvPower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"id\"::tag = '')\n              AND $timeFilter \nGROUP BY time(1d) tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_title",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\") /3600000 FROM \"pvPower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"title\"::tag <> '') \n              AND $timeFilter \nGROUP BY time(1d), \"title\"::tag fill(none) TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "पीवी शक्ति",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_title",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") FROM \"pvPower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"title\"::tag <> '')\n              AND $timeFilter \nGROUP BY time(1m), \"title\"::tag fill(none)  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "बैटरी स्तर",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"batterySoc\" \nWHERE (\"id\"::tag = '')\n              AND $timeFilter \nGROUP BY time(1d) tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_title",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"batterySoc\" \nWHERE (\"title\"::tag <> '')\n              AND $timeFilter \nGROUP BY time(1d), \"title\"::tag fill(none)  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "बैटरी पावर",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_title",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"batteryPower\" \nWHERE (\"title\"::tag <> '')\n              AND $timeFilter \nGROUP BY time(1m), \"title\"::tag fill(none)  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "पूर्वानुमान",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Vorhersage",
     "query": "SELECT integral(\"value\") / 3600000 FROM \"tariffSolar\" WHERE $timeFilter GROUP BY time(1d) tz('$timezone')"
    },
    {
     "alias": "Tatsächlich",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"subquery\") / 3600000 FROM (SELECT max(\"value\") AS \"subquery\" FROM \"pvPower\" WHERE $timeFilter and value >=0 AND value < $peakPowerLimit AND (\"id\"::tag = '') GROUP BY time($energySampleInterval) fill(0) tz('$timezone')) WHERE $timeFilter GROUP BY time(1d) fill(0)  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "पूर्वानुमान",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Vorhersage",
     "query": "SELECT max(\"value\") FROM \"tariffSolar\" WHERE $timeFilter GROUP BY time(1h) tz('$timezone')"
    },
    {
     "alias": "Tatsächlich",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") FROM \"pvPower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"id\"::tag = '')\n              AND $timeFilter \nGROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "उपभोग", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "घर: वर्तमान शक्ति",
   "type": "piechart",
   "description": "AUX और EXT मीटर की उपलब्धता के आधार पर 'अन्य' का फॉर्मूला समायोजित किया जाना चाहिए। विवरण के लिए https://github.com/ha-puzzles/evcc-grafana-dashboards/tree/main/dashboards#formel-für-sonstge-anpassen देखें।",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$totalHomePower-$extPowersSum", "type": "math" },
    {
     "alias": "$tag_title",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\")  FROM \"extPower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"title\"::tag <> '') \n              AND $timeFilter \nGROUP BY time(1m), \"title\"::tag fill(none) TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_title",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\")  FROM \"auxPower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"title\"::tag <> '') \n              AND $timeFilter \nGROUP BY time(1m), \"title\"::tag fill(none) TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "घर: शक्ति",
   "type": "timeseries",
   "description": "AUX और EXT मीटर की उपलब्धता के आधार पर 'अन्य' का फॉर्मूला समायोजित किया जाना चाहिए। विवरण के लिए https://github.com/ha-puzzles/evcc-grafana-dashboards/tree/main/dashboards#formel-für-sonstge-anpassen देखें।",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\")  FROM \"homePower\" \nWHERE  $timeFilter \nGROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expression": "$totalHomePower-$extPowersSum", "type": "math" },
    {
     "alias": "$tag_title",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\")  FROM \"extPower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"title\"::tag <> '') \n              AND $timeFilter \nGROUP BY time(1m), \"title\"::tag fill(none) TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_title",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\")  FROM \"auxPower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"title\"::tag <> '') \n              AND $timeFilter \nGROUP BY time(1m), \"title\"::tag fill(none) TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "होम: ऊर्जा वितरण",
   "type": "piechart",
   "description": "AUX और EXT मीटर की उपलब्धता के आधार पर 'अन्य' का फॉर्मूला समायोजित किया जाना चाहिए। विवरण के लिए https://github.com/ha-puzzles/evcc-grafana-dashboards/tree/main/dashboards#formel-für-sonstge-anpassen देखें।",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$totalHomeEnergy - $extEnergiesSum",
     "type": "math"
    },
    {
     "alias": "$tag_title",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\") /3600 FROM \"extPower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"title\"::tag <> '') \n              AND $timeFilter \nGROUP BY time(1d), \"title\"::tag fill(none) TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_title",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\") /3600 FROM \"auxPower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"title\"::tag <> '') \n              AND $timeFilter \nGROUP BY time(1d), \"title\"::tag fill(none) TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "घर: ऊर्जा की खपत",
   "type": "timeseries",
   "description": "AUX और EXT मीटर की उपलब्धता के आधार पर 'अन्य' का फॉर्मूला समायोजित किया जाना चाहिए। विवरण के लिए https://github.com/ha-puzzles/evcc-grafana-dashboards/tree/main/dashboards#formel-für-sonstge-anpassen देखें।",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\") /3600 FROM \"homePower\" \nWHERE  $timeFilter \nGROUP BY time(1h) tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "$totalHomeEnergy - $extEnergiesSum",
     "type": "math"
    },
    {
     "alias": "$tag_title",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\") /3600 FROM \"extPower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"title\"::tag <> '') \n              AND $timeFilter \nGROUP BY \"title\"::tag, time(1h) fill(0) TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_title",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\") /3600 FROM \"auxPower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"title\"::tag <> '') \n              AND $timeFilter \nGROUP BY \"title\"::tag, time(1h) fill(0) TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "कुल: ऊर्जा वितरण",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Haus",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\") /3600 FROM \"homePower\" \nWHERE  $timeFilter \nGROUP BY time(1d) tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_loadpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\") /3600 FROM \"chargePower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"loadpoint\"::tag <> '') \n              AND $timeFilter \nGROUP BY time(1d), \"loadpoint\"::tag fill(none) TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "कुल: ऊर्जा खपत",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Haus",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\") /3600 FROM \"homePower\" \nWHERE  $timeFilter \nGROUP BY time(1h) tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_loadpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\") /3600 FROM \"chargePower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"loadpoint\"::tag <> '') \n              AND $timeFilter \nGROUP BY \"loadpoint\"::tag, time(1h) fill(none) TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "शुल्क", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "बिजली की कीमत",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Max",
     "query": "SELECT max(\"value\") FROM \"tariffGrid\" WHERE $timeFilter GROUP BY time(1d) tz('$timezone')"
    },
    {
     "alias": "Durchschnitt",
     "query": "SELECT mean(\"value\") FROM \"tariffGrid\" WHERE $timeFilter GROUP BY time(1d) tz('$timezone')"
    },
    {
     "alias": "Min",
     "query": "SELECT min(\"value\") FROM \"tariffGrid\" WHERE $timeFilter GROUP BY time(1d) tz('$timezone')"
    }
   ]
  },
  {
   "title": "बिजली की कीमत",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 56 },
   "targets": [
    {
     "alias": "Preis",
     "query": "SELECT last(\"value\") FROM \"tariffGrid\" WHERE $timeFilter GROUP BY time($tariffPriceInterval) fill(previous) tz('$timezone')"
    },
    {
     "alias": "Netzbezug",
     "query": "SELECT mean(\"value\") AS \"subquery\" FROM \"gridPower\" WHERE $timeFilter and value >=0 GROUP BY time($energySampleInterval) fill(0) tz('$timezone')"
    }
   ]
  },
  {
   "title": "लागत",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "bought", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "sold", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "$boughtTotal + $soldTotal", "type": "math" }
   ]
  },
  {
   "title": "लागत",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    { "expression": "$tariffGrid * $grid", "type": "math" },
    { "expression": "$feedIn * $tariffFeedIn", "type": "math" }
   ]
  },
  {
   "title": "सीओ 2",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "g/kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Max",
     "query": "SELECT max(\"value\") FROM \"tariffCo2\" WHERE $timeFilter GROUP BY time(1d) tz('$timezone')"
    },
    {
     "alias": "Durchschnitt",
     "query": "SELECT mean(\"value\") FROM \"tariffCo2\" WHERE $timeFilter GROUP BY time(1d) tz('$timezone')"
    },
    {
     "alias": "Min",
     "query": "SELECT min(\"value\") FROM \"tariffCo2\" WHERE $timeFilter GROUP BY time(1d) tz('$timezone')"
    }
   ]
  },
  {
   "title": "सीओ 2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 74 },
   "targets": [
    {
     "alias": "CO2",
     "query": "SELECT last(\"value\") FROM \"tariffCo2\" WHERE $timeFilter GROUP BY time(1h) tz('$timezone')"
    },
    {
     "alias": "Netzbezug",
     "query": "SELECT mean(\"value\") AS \"subquery\" FROM \"gridPower\" WHERE $timeFilter and value >=0 GROUP BY time($energySampleInterval) fill(0) tz('$timezone')"
    }
   ]
  },
  { "title": "नेटवर्क", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "धाराएँ/चरण",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Strom L1",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "gridCurrents",
     "query": "SELECT last(\"l1\") FROM \"gridCurrents\" WHERE $timeFilter  tz('$timezone')",
     "select": [
      [
       { "params": [ "l1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$timezone"
    },
    {
     "alias": "Strom L2",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "gridCurrents",
     "query": "SELECT last(\"l2\") FROM \"gridCurrents\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "l2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$timezone"
    },
    {
     "alias": "Strom L3",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "gridCurrents",
     "query": "SELECT mean(\"l3\") FROM \"gridCurrents\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "l3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$timezone"
    }
   ]
  },
  {
   "title": "धाराएँ/चरण",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Strom L1",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "gridCurrents",
     "query": "SELECT mean(\"l1\") FROM \"gridCurrents\" WHERE $timeFilter GROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "l1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$timezone"
    },
    {
     "alias": "Strom L2",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "gridCurrents",
     "query": "SELECT mean(\"l2\") FROM \"gridCurrents\" WHERE $timeFilter GROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "l2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$timezone"
    },
    {
     "alias": "Strom L3",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "gridCurrents",
     "query": "SELECT mean(\"l3\") FROM \"gridCurrents\" WHERE $timeFilter GROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "l3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$timezone"
    }
   ]
  },
  {
   "title": "शक्ति/चरण",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Leistung L1",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "gridPowers",
     "query": "SELECT last(\"l1\") FROM \"gridPowers\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "l1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$timezone"
    },
    {
     "alias": "Leistung L2",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "gridPowers",
     "query": "SELECT last(\"l2\") FROM \"gridPowers\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "l2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$timezone"
    },
    {
     "alias": "Leistung L3",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "gridPowers",
     "query": "SELECT last(\"l3\") FROM \"gridPowers\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "l3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$timezone"
    }
   ]
  },
  {
   "title": "शक्ति/चरण",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Leistung L1",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "gridPowers",
     "query": "SELECT mean(\"l1\") FROM \"gridPowers\" WHERE $timeFilter GROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "l1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Leistung L2",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "gridPowers",
     "query": "SELECT mean(\"l2\") FROM \"gridPowers\" WHERE $timeFilter GROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "l2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Leistung L3",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "gridPowers",
     "query": "SELECT mean(\"l3\") FROM \"gridPowers\" WHERE $timeFilter GROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "l3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "लोडपॉइंट $लोडपॉइंट", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }, "repeat": "loadpoint" },
  {
   "title": "चार्जिंग धाराएँ/चरण",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "L1 $loadpoint",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "chargeCurrents",
     "query": "SELECT last(\"l1\") FROM \"chargeCurrents\" WHERE (\"loadpoint\"::tag = '$loadpoint') AND $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "l1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "loadpoint::tag", "operator": "=", "value": "Garage" }
     ],
     "tz": "$timezone"
    },
    {
     "alias": "L2 $loadpoint",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "chargeCurrents",
     "query": "SELECT last(\"l2\") FROM \"chargeCurrents\" WHERE (\"loadpoint\"::tag = '$loadpoint') AND $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "l2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "loadpoint::tag", "operator": "=", "value": "Garage" }
     ],
     "tz": "$timezone"
    },
    {
     "alias": "L3 $loadpoint",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "chargeCurrents",
     "query": "SELECT last(\"l3\") FROM \"chargeCurrents\" WHERE (\"loadpoint\"::tag = '$loadpoint') AND $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "l3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "loadpoint::tag", "operator": "=", "value": "Garage" }
     ],
     "tz": "$timezone"
    },
    {
     "alias": "Strom $loadpoint",
     "query": "SELECT last(\"value\") FROM \"chargeCurrent\" WHERE (\"loadpoint\"::tag = '$loadpoint') AND $timeFilter tz('$timezone')"
    }
   ]
  },
  {
   "title": "चार्जिंग धाराएँ/चरण",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "L1 $loadpoint",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "chargeCurrents",
     "query": "SELECT mean(\"l1\") FROM \"chargeCurrents\" WHERE (\"loadpoint\"::tag = '$loadpoint') AND $timeFilter GROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "l1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "loadpoint::tag", "operator": "=", "value": "Garage" }
     ],
     "tz": "$timezone"
    },
    {
     "alias": "L2 $loadpoint",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "chargeCurrents",
     "query": "SELECT mean(\"l2\") FROM \"chargeCurrents\" WHERE (\"loadpoint\"::tag = '$loadpoint') AND $timeFilter GROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "l2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "loadpoint::tag", "operator": "=", "value": "Garage" }
     ],
     "tz": "$timezone"
    },
    {
     "alias": "L3 $loadpoint",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "chargeCurrents",
     "query": "SELECT mean(\"l3\") FROM \"chargeCurrents\" WHERE (\"loadpoint\"::tag = '$loadpoint') AND $timeFilter GROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "l3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "loadpoint::tag", "operator": "=", "value": "Garage" }
     ],
     "tz": "$timezone"
    },
    {
     "alias": "Strom $loadpoint",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "chargeCurrents",
     "query": "SELECT mean(\"value\") FROM \"chargeCurrent\" WHERE (\"loadpoint\"::tag = '$loadpoint') AND $timeFilter GROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "l3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "loadpoint::tag", "operator": "=", "value": "Garage" }
     ],
     "tz": "$timezone"
    }
   ]
  },
  {
   "title": "के चरण",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 112 },
   "targets": [
    {
     "alias": "1 phasig: $loadpoint",
     "query": "SELECT max(\"value\") FROM \"phasesActive\" WHERE $timeFilter AND (\"loadpoint\"::tag = '$loadpoint') AND value = 1 GROUP BY time(1m), \"loadpoint\"::tag fill(none) tz('$timezone')"
    },
    {
     "alias": "3 phasig: $loadpoint",
     "query": "SELECT max(\"value\") FROM \"phasesActive\" WHERE $timeFilter AND (\"loadpoint\"::tag = '$loadpoint') AND value = 3 GROUP BY time(1m), \"loadpoint\"::tag fill(none) tz('$timezone')"
    }
   ]
  },
  {
   "title": "चार्जिंग पावर",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Ladeleistung $loadpoint",
     "query": "SELECT max(\"value\") FROM \"chargePower\" WHERE $timeFilter AND (\"loadpoint\"::tag = '$loadpoint') GROUP BY time(1m), \"loadpoint\"::tag fill(none) tz('$timezone')"
    }
   ]
  }
 ]
}