{
 "title": "VM: EVCC: ऑल-टाइम",
 "tags": [ "EVCC" ],
 "time": { "from": "now-2y/y", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "dbLabel", "label": "DB लेबल", "query": "evcc" },
   { "name": "peakPowerLimit", "label": "अधिकतम शक्ति सीमा", "query": "30000" },
   { "name": "energySampleInterval", "label": "ऊर्जा सैंपल अंतराल", "query": "30s" },
   { "name": "tariffPriceInterval", "label": "टैरिफ अंतराल", "query": "15m" },
   { "name": "loadpointBlocklist", "label": "लोडपॉइंट ब्लॉकलिस्ट", "query": "^none$" },
   { "name": "extBlocklist", "label": "EXT ब्लॉकलिस्ट", "query": "^none$" },
   { "name": "auxBlocklist", "label": "AUX ब्लॉकलिस्ट", "query": "^none$" },
   { "name": "installedWattPeak", "label": "installedWattPeak", "query": "20" },
   { "name": "vehicleBlocklist", "label": "वाहन ब्लॉकलिस्ट", "query": "^Altherma-3$" },
   {
    "name": "vehicle",
    "label": "वाहन",
    "query": {
     "query": "label_values(sessionPricePerKWh_value{db=\"$dbLabel\",vehicle!=\"\",vehicle!~\"$vehicleBlocklist\"}, vehicle)"
    }
   },
   { "name": "vVerbrauch", "label": "इंजन खपत l/100km", "query": "6" },
   { "name": "spritKosten", "label": "ईंधन मूल्य/लीटर", "query": "1.75" },
   { "name": "purchasePricePv", "label": "PV खरीद मूल्य", "query": "24884" },
   { "name": "batteryPurchasePrice", "label": "बैटरी खरीद मूल्य", "query": "5500" },
   { "name": "runningCosts", "label": "चालू लागत", "query": "100" },
   { "name": "speicherkapazitaet", "label": "बैटरी क्षमता / Wh", "query": "9500" }
  ]
 },
 "panels": [
  { "title": "ऊर्जा", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ऊर्जा कुल",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "ग्रिड आयात"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "पीवी"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "घर"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{db=\"$dbLabel\",loadpoint!~\"$loadpointBlocklist\"}[1d]))[$__range:1d])) by (loadpoint) / 1000, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / 1000",
     "legendFormat": "ग्रिड में आपूर्ति"
    }
   ]
  },
  {
   "title": "वार्षिक उपज",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "मासिक उपज/वर्ष",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "मेट्रिक गेज",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1 - $gridEnergyIn / ($homeEnergy + $loadpointEnergy)",
     "type": "math"
    },
    {
     "expression": "($pvEnergy - $gridEnergyOut) / $pvEnergy",
     "type": "math"
    }
   ]
  },
  {
   "title": "वार्षिक घरेलू खपत",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "मासिक घरेलू खपत/वर्ष",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "वार्षिक ग्रिड आयात",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "मासिक ग्रिड आयात/वर्ष",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "बैटरी सारांश",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "batteryChargeTotal"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "batteryDischargeTotal"
    },
    {
     "expression": "$batteryDischargeTotal / $batteryChargeTotal",
     "type": "math"
    },
    {
     "expr": "sum(avg_over_time((last_over_time(evcc_battery_soc_daily_max_pct{db=\"$dbLabel\"}[1d]))[$__range:1d])) / count(avg_over_time((last_over_time(evcc_battery_soc_daily_max_pct{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "maxSoc"
    },
    {
     "expr": "sum(avg_over_time((last_over_time(evcc_battery_soc_daily_min_pct{db=\"$dbLabel\"}[1d]))[$__range:1d])) / count(avg_over_time((last_over_time(evcc_battery_soc_daily_min_pct{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "minSoc"
    }
   ]
  },
  {
   "title": "वार्षिक आपूर्ति",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "मासिक आपूर्ति/वर्ष",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "सबसे अधिक उपज वाले दिन",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "max without(local_year,local_month)(evcc_pv_energy_daily_wh{db=\"$dbLabel\"}) / 1000",
     "legendFormat": "PV ऊर्जा"
    }
   ]
  },
  {
   "title": "सबसे अधिक आपूर्ति",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "max without(local_year,local_month)(evcc_grid_export_daily_wh{db=\"$dbLabel\"}) / 1000",
     "legendFormat": "ग्रिड में आपूर्ति"
    }
   ]
  },
  {
   "title": "सबसे अधिक घरेलू खपत",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "max without(local_year,local_month)(evcc_home_energy_daily_wh{db=\"$dbLabel\"}) / 1000",
     "legendFormat": "घरेलू खपत"
    }
   ]
  },
  { "title": "प्लांट स्वास्थ्य", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "प्रति वर्ष शीर्ष 30 दिनों का औसत",
   "type": "barchart",
   "description": "यह प्रति वर्ष सर्वोत्तम 30 दिनों की औसत उत्पादन का उपयोग करता है। इससे संभावित गिरावट का संकेत मिल सकता है, लेकिन इसे संदर्भ में समझना चाहिए। केवल एक वर्ष अपने आप में निर्णायक नहीं होता।",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "last_over_time(evcc_pv_top30_mean_yearly_wh{db=\"$dbLabel\"}[$__range])",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "प्रति माह शीर्ष 5 दिनों का औसत",
   "type": "barchart",
   "description": "यह प्रति माह सर्वोत्तम 5 दिनों की औसत उत्पादन का उपयोग करता है। इससे संभावित गिरावट का संकेत मिल सकता है, लेकिन इसे संदर्भ में समझना चाहिए। केवल एक महीना अपने आप में निर्णायक नहीं होता।",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "last_over_time(evcc_pv_top5_mean_monthly_wh{db=\"$dbLabel\"}[$__range])",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  { "title": "वित्त", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "मासिक लागत",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "label_join(label_set(clamp_min((sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month) - sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)), 0), \"kind\", \"Costs\"), \"series\", \" \", \"local_year\", \"kind\") or (label_join(label_set(clamp_min((sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month) - sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year, local_month)), 0), \"kind\", \"Income\"), \"series\", \" \", \"local_year\", \"kind\") and on (local_year) (sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) by (local_year) > 0))"
    }
   ]
  },
  { "title": "संतुलन", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "शक्ति संतुलन",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{db=\"$dbLabel\"}[1d]))[$__range:1d])) / sum(count_over_time((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "averagePrice"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d])) * -1",
     "legendFormat": "खरीदा गया"
    },
    {
     "expression": "($purchased * -100) / ($energyPurchased / 1000)",
     "type": "math"
    },
    {
     "expression": "$averagePrice - $weightedAveragePrice",
     "type": "math"
    },
    {
     "expression": "$averagePrice * ($energyPurchased / 1000) / -100",
     "type": "math"
    },
    {
     "expression": "$purchased - $potentialPurchased",
     "type": "math"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "बेचा गया"
    },
    { "expression": "$purchased + $sold", "type": "math" }
   ]
  },
  {
   "title": "PV सिस्टम अमोर्टाइजेशन",
   "type": "stat",
   "description": "यदि डेटा 365 दिनों से कम है, तो मानों को पूरे वर्ष के लिए एक्सट्रपलेट किया जाता है और सटीकता दर्ज अवधि पर निर्भर करती है।",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$potentialHomePrice + $potentialLoadpointPrice",
     "type": "math"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "energyPurchasedPrice"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "energySoldPrice"
    },
    {
     "expression": "$energyPurchasedPrice - $energySoldPrice",
     "type": "math"
    },
    {
     "expression": "$potentialTotalPrice - $energyTotalPrice",
     "type": "math"
    },
    {
     "expr": "sum(count_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "numberOfMeasuredDays"
    },
    {
     "expression": "$refluxOfCapital * 365 / $numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$purchasePricePv / ($refluxOfCapitalYearly - $runningCosts)",
     "type": "math"
    },
    {
     "expression": "($refluxOfCapitalYearly - $runningCosts) / $purchasePricePv",
     "type": "math"
    }
   ]
  },
  {
   "title": "बैटरी अमोर्टाइजेशन",
   "type": "stat",
   "description": "यदि डेटा 365 दिनों से कम है, तो मानों को पूरे वर्ष के लिए एक्सट्रपलेट किया जाता है और सटीकता दर्ज अवधि पर निर्भर करती है।",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "chargedEnergy"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "dischargedEnergy"
    },
    {
     "expression": "1 - ($dischargedEnergy / $chargedEnergy)",
     "type": "math"
    },
    {
     "expr": "sum(count_over_time((last_over_time(evcc_home_energy_daily_wh{db=\"$dbLabel\"}[1d]))[$__range:1d]))",
     "legendFormat": "numberOfMeasuredDays"
    },
    {
     "expression": "($chargedEnergy / $speicherkapazitaet) * 365 / $numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "($batteryDischargeCost - $batteryChargeFeedInCost) * 365 / $numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$batteryPurchasePrice / $batteryPayback",
     "type": "math"
    },
    {
     "expression": "$batteryPayback / $batteryPurchasePrice",
     "type": "math"
    }
   ]
  },
  { "title": "वाहन", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "$vehicle ड्राइविंग लागत",
   "type": "stat",
   "description": "मान औसतों पर आधारित मोटे अनुमान हैं। बाहरी चार्जिंग सत्र शामिल नहीं हैं。",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 93 },
   "repeat": "vehicle",
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_vehicle_distance_daily_km{db=\"$dbLabel\",vehicle=\"$vehicle\"}[1d]))[$__range:1d]))",
     "legendFormat": "drivenKm"
    },
    {
     "expression": "$chargedEnergy / ($drivenKm / 100)",
     "type": "math"
    },
    {
     "expr": "avg(avg_over_time(sessionSolarPercentage_value{db=\"$dbLabel\",vehicle=\"$vehicle\"}[$__range]))",
     "legendFormat": "solarPercent"
    },
    {
     "expr": "avg(avg_over_time(sessionPricePerKWh_value{db=\"$dbLabel\",vehicle=\"$vehicle\"}[$__range]))",
     "legendFormat": "chargePrice"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_potential_vehicle_charge_cost_daily_eur{db=\"$dbLabel\",vehicle=\"$vehicle\"}[1d]))[$__range:1d]))",
     "legendFormat": "electricDriveCostNoPV"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_vehicle_charge_cost_daily_eur{db=\"$dbLabel\",vehicle=\"$vehicle\"}[1d]))[$__range:1d]))",
     "legendFormat": "electricDriveCost"
    },
    {
     "expression": "$electricDriveCostNoPV - $electricDriveCost",
     "type": "math"
    },
    {
     "expression": "$drivenKm / 100 * $vVerbrauch * $spritKosten",
     "type": "math"
    },
    {
     "expression": "$iceDriveCost - $electricDriveCost",
     "type": "math"
    }
   ]
  }
 ]
}