{
 "title": "VM: EVCC: All-time",
 "tags": [ "EVCC" ],
 "time": { "from": "now-2y/y", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "peakPowerLimit", "label": "Peak Power Limit", "query": "30000" },
   { "name": "energySampleInterval", "label": "Energy Sample Interval", "query": "30s" },
   { "name": "tariffPriceInterval", "label": "Tariff Price Interval", "query": "15m" },
   { "name": "loadpointBlocklist", "label": "Loadpoint Blocklist", "query": "^none$" },
   { "name": "extBlocklist", "label": "EXT Blocklist", "query": "^none$" },
   { "name": "auxBlocklist", "label": "AUX Blocklist", "query": "^none$" },
   { "name": "installedWattPeak", "label": "installedWattPeak", "query": "20" },
   { "name": "vehicleBlocklist", "label": "Vehicle Blocklist", "query": "^Altherma-3$" },
   {
    "name": "vehicle",
    "label": "Vehicle",
    "query": {
     "query": "label_values(sessionPricePerKWh_value{vehicle!=\"\",vehicle!~\"$vehicleBlocklist\"}, vehicle)"
    }
   },
   { "name": "vVerbrauch", "label": "ICE consumption l/100km", "query": "6" },
   { "name": "spritKosten", "label": "Fuel price/l", "query": "1.75" },
   { "name": "purchasePricePv", "label": "PV purchase price", "query": "24884" },
   { "name": "batteryPurchasePrice", "label": "Battery purchase price", "query": "5500" },
   { "name": "runningCosts", "label": "Running costs", "query": "100" },
   { "name": "speicherkapazitaet", "label": "Battery capacity / Wh", "query": "9500" },
   { "name": "evccUrl", "label": "EVCC URL", "query": "${VAR_EVCCURL}" },
   { "name": "inverterPortalTitle", "label": "Inverter portal name", "query": "${VAR_INVERTERPORTALTITLE}" },
   { "name": "inverterPortalUrl", "label": "Inverter portal URL", "query": "${VAR_INVERTERPORTALURL}" }
  ]
 },
 "panels": [
  { "title": "Energy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Energy totals",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Grid import"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh[1d]))[$__range:1d])) / 1000",
     "legendFormat": "PV"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Home"
    },
    {
     "expr": "sort_by_label(sum(sum_over_time((last_over_time(evcc_loadpoint_energy_daily_wh{loadpoint!~\"$loadpointBlocklist\"}[1d]))[$__range:1d])) by (loadpoint) / 1000, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh[1d]))[$__range:1d])) / 1000",
     "legendFormat": "Feed-in"
    }
   ]
  },
  {
   "title": "Yearly yield",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Monthly yield/year",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_pv_energy_daily_wh[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "Metric gauges",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1 - $gridEnergyIn / ($homeEnergy + $loadpointEnergy)",
     "type": "math"
    },
    {
     "expression": "($pvEnergy - $gridEnergyOut) / $pvEnergy",
     "type": "math"
    }
   ]
  },
  {
   "title": "Yearly home consumption",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Monthly home consumption/year",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_home_energy_daily_wh[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "Yearly grid import",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Monthly grid import/year",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_daily_wh[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "Battery summary",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh[1d]))[$__range:1d]))",
     "legendFormat": "batteryChargeTotal"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh[1d]))[$__range:1d]))",
     "legendFormat": "batteryDischargeTotal"
    },
    {
     "expression": "$batteryDischargeTotal / $batteryChargeTotal",
     "type": "math"
    },
    {
     "expr": "sum(avg_over_time((last_over_time(evcc_battery_soc_daily_max_pct[1d]))[$__range:1d])) / count(avg_over_time((last_over_time(evcc_battery_soc_daily_max_pct[1d]))[$__range:1d]))",
     "legendFormat": "maxSoc"
    },
    {
     "expr": "sum(avg_over_time((last_over_time(evcc_battery_soc_daily_min_pct[1d]))[$__range:1d])) / count(avg_over_time((last_over_time(evcc_battery_soc_daily_min_pct[1d]))[$__range:1d]))",
     "legendFormat": "minSoc"
    }
   ]
  },
  {
   "title": "Yearly feed-in",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh[1d]))[$__range:1d])) by (local_year)",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Monthly feed-in/year",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_daily_wh[1d]))[$__range:1d])) by (local_year, local_month)",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  {
   "title": "Days with highest yield",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "max without(local_year,local_month)(evcc_pv_energy_daily_wh) / 1000",
     "legendFormat": "pvEnergy"
    }
   ]
  },
  {
   "title": "Highest feed-in",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "max without(local_year,local_month)(evcc_grid_export_daily_wh) / 1000",
     "legendFormat": "feedIn"
    }
   ]
  },
  {
   "title": "Highest home consumption",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "max without(local_year,local_month)(evcc_home_energy_daily_wh) / 1000",
     "legendFormat": "homeConsumption"
    }
   ]
  },
  { "title": "Plant health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Average top 30 days/year",
   "type": "barchart",
   "description": "Uses the average yield of the best 30 days per year. This can help identify possible degradation, but must be interpreted in context. Individual years are not conclusive on their own.",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "last_over_time(evcc_pv_top30_mean_yearly_wh[$__range])",
     "legendFormat": "{{local_year}}"
    }
   ]
  },
  {
   "title": "Average top 5 days/month",
   "type": "barchart",
   "description": "Uses the average yield of the best 5 days per month. This can help identify possible degradation, but must be interpreted in context. Individual months are not conclusive on their own.",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "last_over_time(evcc_pv_top5_mean_monthly_wh[$__range])",
     "legendFormat": "{{local_month}}"
    }
   ]
  },
  { "title": "Finances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Monthly costs",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "WITH (\n  monthlyImport = sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur[1d]))[$__range:1d])) by (local_year, local_month),\n  monthlyExport = sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur[1d]))[$__range:1d])) by (local_year, local_month),\n)\nlabel_join(\n  label_set(clamp_min(monthlyImport - monthlyExport, 0), \"kind\", \"Costs\"),\n  \"series\", \" \", \"local_year\", \"kind\"\n)"
    },
    {
     "expr": "WITH (\n  monthlyImport = sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur[1d]))[$__range:1d])) by (local_year, local_month),\n  monthlyExport = sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur[1d]))[$__range:1d])) by (local_year, local_month),\n  yearlyExport = sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur[1d]))[$__range:1d])) by (local_year),\n)\nlabel_join(\n  label_set(clamp_min(monthlyExport - monthlyImport, 0), \"kind\", \"Income\"),\n  \"series\", \" \", \"local_year\", \"kind\"\n)\nand on (local_year) (yearlyExport > 0)"
    }
   ]
  },
  { "title": "Balance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Power balance",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh[1d]))[$__range:1d])) / sum(count_over_time((last_over_time(evcc_grid_import_price_avg_daily_ct_per_kwh[1d]))[$__range:1d]))",
     "legendFormat": "averagePrice"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur[1d]))[$__range:1d])) * -1",
     "legendFormat": "purchased"
    },
    {
     "expression": "($purchased * -100) / ($energyPurchased / 1000)",
     "type": "math"
    },
    {
     "expression": "$averagePrice - $weightedAveragePrice",
     "type": "math"
    },
    {
     "expression": "$averagePrice * ($energyPurchased / 1000) / -100",
     "type": "math"
    },
    {
     "expression": "$purchased - $potentialPurchased",
     "type": "math"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur[1d]))[$__range:1d]))",
     "legendFormat": "sold"
    },
    { "expression": "$purchased + $sold", "type": "math" }
   ]
  },
  {
   "title": "PV Anlage Amortisation",
   "type": "stat",
   "description": "For less than 365 days of data, values are extrapolated to a full year with corresponding inaccuracy depending on the captured period.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$potentialHomePrice + $potentialLoadpointPrice",
     "type": "math"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_import_cost_daily_eur[1d]))[$__range:1d]))",
     "legendFormat": "energyPurchasedPrice"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_grid_export_credit_daily_eur[1d]))[$__range:1d]))",
     "legendFormat": "energySoldPrice"
    },
    {
     "expression": "$energyPurchasedPrice - $energySoldPrice",
     "type": "math"
    },
    {
     "expression": "$potentialTotalPrice - $energyTotalPrice",
     "type": "math"
    },
    {
     "expr": "sum(count_over_time((last_over_time(evcc_home_energy_daily_wh[1d]))[$__range:1d]))",
     "legendFormat": "numberOfMeasuredDays"
    },
    {
     "expression": "$refluxOfCapital * 365 / $numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$purchasePricePv / ($refluxOfCapitalYearly - $runningCosts)",
     "type": "math"
    },
    {
     "expression": "($refluxOfCapitalYearly - $runningCosts) / $purchasePricePv",
     "type": "math"
    }
   ]
  },
  {
   "title": "Speicher Amortisation",
   "type": "stat",
   "description": "For less than 365 days of data, values are extrapolated to a full year with corresponding inaccuracy depending on the captured period.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_charge_daily_wh[1d]))[$__range:1d]))",
     "legendFormat": "chargedEnergy"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_battery_discharge_daily_wh[1d]))[$__range:1d]))",
     "legendFormat": "dischargedEnergy"
    },
    {
     "expression": "1 - ($dischargedEnergy / $chargedEnergy)",
     "type": "math"
    },
    {
     "expr": "sum(count_over_time((last_over_time(evcc_home_energy_daily_wh[1d]))[$__range:1d]))",
     "legendFormat": "numberOfMeasuredDays"
    },
    {
     "expression": "($chargedEnergy / $speicherkapazitaet) * 365 / $numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "($batteryDischargeCost - $batteryChargeFeedInCost) * 365 / $numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$batteryPurchasePrice / $batteryPayback",
     "type": "math"
    },
    {
     "expression": "$batteryPayback / $batteryPurchasePrice",
     "type": "math"
    }
   ]
  },
  { "title": "Fahrzeuge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Driving costs $vehicle",
   "type": "stat",
   "description": "Values are rough estimates based on averages. External charging sessions are not included.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 93 },
   "repeat": "vehicle",
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_vehicle_distance_daily_km{vehicle=\"$vehicle\"}[1d]))[$__range:1d]))",
     "legendFormat": "drivenKm"
    },
    {
     "expression": "$chargedEnergy / ($drivenKm / 100)",
     "type": "math"
    },
    {
     "expr": "avg(avg_over_time(sessionSolarPercentage_value{vehicle=\"$vehicle\"}[$__range]))",
     "legendFormat": "solarPercent"
    },
    {
     "expr": "avg(avg_over_time(sessionPricePerKWh_value{vehicle=\"$vehicle\"}[$__range]))",
     "legendFormat": "chargePrice"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_potential_vehicle_charge_cost_daily_eur{vehicle=\"$vehicle\"}[1d]))[$__range:1d]))",
     "legendFormat": "electricDriveCostNoPV"
    },
    {
     "expr": "sum(sum_over_time((last_over_time(evcc_vehicle_charge_cost_daily_eur{vehicle=\"$vehicle\"}[1d]))[$__range:1d]))",
     "legendFormat": "electricDriveCost"
    },
    {
     "expression": "$electricDriveCostNoPV - $electricDriveCost",
     "type": "math"
    },
    {
     "expression": "$drivenKm / 100 * $vVerbrauch * $spritKosten",
     "type": "math"
    },
    {
     "expression": "$iceDriveCost - $electricDriveCost",
     "type": "math"
    }
   ]
  }
 ]
}